import { appendAuditLogLocked, type AuditInput } from "@/lib/security/audit";
import { createId } from "@/lib/ids";
import { DuplicateCardCodeError, cleanCardPrefix, generateCardCodes, normalizeCardCode } from "@/lib/cards/codes";
import { readJsonFile, updateJsonFile, withDocumentLock, writeJsonFile } from "@/lib/dataDir";
import { AUTH_DOCUMENT_KEY, applyLiveTopUp, findUserById } from "@/lib/auth/store";
import { planIdToSubscriptionType } from "@/lib/auth/tiers";

const FILE = "billing.json";

/** The billing document key (mm_documents.key on Postgres). */
export const BILLING_DOCUMENT_KEY = FILE;

export type LedgerKind = "activation" | "topup" | "live_booking" | "ai_grant";

export type LedgerEntry = {
  id: string;
  userId: string;
  kind: LedgerKind;
  hoursDelta: number;
  code?: string;
  description: string;
  descriptionAr: string;
  relatedId?: string;
  createdAt: string;
};

export type TopUpCode = {
  code: string;
  liveHours: number;
  used: boolean;
  usedBy?: string;
  usedUserId?: string;
  createdAt: string;
  expiresAt?: string;
  note?: string;
  createdBy?: string;
};

type BillingStore = { codes: TopUpCode[]; ledger: LedgerEntry[] };

/** No demo codes or demo ledger rows: codes are generated by staff (createTopUpCodes). */
function seed(): BillingStore {
  return { codes: [], ledger: [] };
}

function normalizeBilling(data: Partial<BillingStore> | null | undefined): BillingStore {
  if (!data || !Array.isArray(data.codes) || !Array.isArray(data.ledger)) return seed();
  return data as BillingStore;
}

async function readBilling(): Promise<BillingStore> {
  return normalizeBilling(await readJsonFile<BillingStore>(FILE, seed()));
}

async function writeBilling(store: BillingStore) {
  await writeJsonFile(FILE, store);
}

/** Locked append (re-entrant inside redeemCode's lock, so the ledger row commits with the redeem). */
export async function addLedger(entry: Omit<LedgerEntry, "id" | "createdAt"> & { id?: string }) {
  const record: LedgerEntry = {
    ...entry,
    id: entry.id ?? createId("led"),
    createdAt: new Date().toISOString(),
  };
  await updateJsonFile<BillingStore>(FILE, seed(), (current) => {
    const store = normalizeBilling(current);
    store.ledger.unshift(record);
    return store;
  });
  return record;
}

export async function listLedger(userId?: string) {
  const store = await readBilling();
  return userId ? store.ledger.filter((item) => item.userId === userId) : store.ledger;
}

export async function listTopUpCodes() {
  const store = await readBilling();
  return store.codes;
}

/** Admin-only (enforced by /api/billing/topup). Codes come from node:crypto (cards/codes.ts). */
export async function createTopUpCodes(input: {
  prefix?: string;
  liveHours: number;
  count?: number;
  note?: string;
  expiresAt?: string;
  createdBy?: string;
  code?: string;
}, options?: { audit?: (created: TopUpCode[]) => AuditInput }) {
  return withDocumentLock(FILE, async () => {
    const store = await readBilling();
    const count = Math.min(Math.max(Math.floor(Number(input.count ?? 1)) || 1, 1), 50);
    const hours = Math.max(1, Math.round(input.liveHours));
    const existing = store.codes.map((item) => item.code);
    let codes: string[];
    if (count === 1 && input.code?.trim()) {
      const custom = normalizeCardCode(input.code);
      if (existing.some((code) => code.toUpperCase() === custom)) throw new DuplicateCardCodeError();
      codes = [custom];
    } else {
      codes = generateCardCodes(cleanCardPrefix(input.prefix, "MUNZER-HRS"), count, existing);
    }
    const createdAt = new Date().toISOString();
    const created: TopUpCode[] = codes.map((code) => ({
      code,
      liveHours: hours,
      used: false,
      createdAt,
      expiresAt: input.expiresAt,
      note: input.note,
      createdBy: input.createdBy,
    }));
    store.codes.unshift(...created);
    await writeBilling(store);
    // Same transaction as the cards on Postgres: no card exists without its audit row.
    if (options?.audit) await appendAuditLogLocked(options.audit(created));
    return created;
  });
}

export type TopUpRedeemResult =
  | { ok: true; hours: number; liveCredits: number; code: string }
  | { ok: false; error: string; errorEn: string; reason: "unknown" | "used" | "expired" | "user_not_found" };

/**
 * Claim one live-hour top-up code and credit the student. Atomic: billing.json and auth.json are
 * locked together (withDocumentLock: in-process mutex; on Postgres advisory + row locks in ONE
 * transaction), the card is checked, the credits are added relative to the locked balance and the
 * ledger row is written — all commit together, so a code can never be redeemed twice and two
 * concurrent top-ups never overwrite each other's balance.
 */
export async function redeemTopUp(code: string, userId: string, studentName: string): Promise<TopUpRedeemResult> {
  return withDocumentLock([AUTH_DOCUMENT_KEY, FILE], async () => {
    const store = await readBilling();
    const wanted = code.trim().toLowerCase();
    const card = store.codes.find((item) => item.code.toLowerCase() === wanted);
    if (!card) return { ok: false as const, reason: "unknown" as const, error: "رمز الشحن غير صحيح", errorEn: "Unknown top-up code." };
    if (card.used) return { ok: false as const, reason: "used" as const, error: "هذا الرمز مستخدم", errorEn: "This top-up code was already used." };
    if (card.expiresAt && Date.parse(card.expiresAt) < Date.now()) {
      return { ok: false as const, reason: "expired" as const, error: "انتهت صلاحية الرمز", errorEn: "This top-up code has expired." };
    }
    const user = await applyLiveTopUp(userId, card.liveHours);
    if (!user) {
      return { ok: false as const, reason: "user_not_found" as const, error: "الحساب غير موجود", errorEn: "Account not found." };
    }
    card.used = true;
    card.usedBy = studentName;
    card.usedUserId = userId;
    const record: LedgerEntry = {
      id: createId("led"),
      userId,
      kind: "topup",
      hoursDelta: card.liveHours,
      code: card.code,
      description: `Redeemed live-hour top-up (+${card.liveHours} h)`,
      descriptionAr: `شحن حصص مباشرة (+${card.liveHours} ساعات)`,
      createdAt: new Date().toISOString(),
    };
    store.ledger.unshift(record);
    await writeBilling(store);
    return { ok: true as const, hours: card.liveHours, liveCredits: user.liveCredits, code: card.code };
  });
}

export async function recordLiveBookingDebit(userId: string, bookingId: string, studentName: string) {
  return addLedger({
    userId,
    kind: "live_booking",
    hoursDelta: -1,
    relatedId: bookingId,
    description: `Booked live 1-on-1 (${studentName})`,
    descriptionAr: `حجز حصة مباشرة (${studentName})`,
  });
}

export async function recordActivation(userId: string, planId: string, code: string) {
  const type = planIdToSubscriptionType(planId);
  const hours = type === "BOTH" ? 8 : type === "LIVE_TIER" ? 4 : 0;
  return addLedger({
    userId,
    kind: type === "LIVE_TIER" ? "topup" : type === "AI_TIER" ? "ai_grant" : "activation",
    hoursDelta: hours,
    code,
    description: `Activation card ${code} (${planId})`,
    descriptionAr: `بطاقة تفعيل ${code} (${planId})`,
  });
}

export async function walletSnapshot(userId: string) {
  const user = await findUserById(userId);
  if (!user) return undefined;
  const expired = Boolean(user.aiExpiresAt && Date.parse(user.aiExpiresAt) < Date.now());
  const type = user.subscriptionType;
  const hasAiPlan = type === "AI_TIER" || type === "BOTH";
  const aiStatus = !hasAiPlan ? "none" : expired ? "expired" : "active";
  const ledger = await listLedger(userId);
  return {
    name: user.name,
    phone: user.phone,
    email: user.email,
    subscriptionType: type ?? null,
    aiStatus,
    aiExpiresAt: user.aiExpiresAt ?? null,
    liveCredits: user.liveCredits ?? 0,
    ledger,
  };
}
