import type { TypedPractice } from "./typedAnswer";

export type InteractivePractice = { question: string; arabicQuestion: string; options: string[]; answer: string; explanation: string; arabicExplanation: string; difficulty: "guided" | "standard" | "challenge" };
export type InteractiveExample = { question: string; arabicQuestion: string; solution: string[]; arabicSolution: string[]; label: string; arabicLabel: string };
export type InteractiveLesson = {
  slug: string;
  steps: { en: string; ar: string }[];
  example: { question: string; arabicQuestion: string; solution: string[]; arabicSolution: string[] };
  practice: { question: string; arabicQuestion: string; options: string[]; answer: string; explanation: string; arabicExplanation: string };
  examples?: InteractiveExample[];
  practiceSet?: InteractivePractice[];
  typedPracticeSet?: TypedPractice[];
};

const lesson = (slug: string, steps: string[], arabicSteps: string[], question: string, arabicQuestion: string, solution: string[], arabicSolution: string[], practiceQuestion: string, arabicPracticeQuestion: string, options: string[], answer: string, explanation: string, arabicExplanation: string): InteractiveLesson => ({ slug, steps: steps.map((en, index) => ({ en, ar: arabicSteps[index] })), example: { question, arabicQuestion, solution, arabicSolution }, practice: { question: practiceQuestion, arabicQuestion: arabicPracticeQuestion, options, answer, explanation, arabicExplanation } });

export const interactiveLessons: InteractiveLesson[] = [
  lesson("functions", ["Name the input and output.", "Substitute the input into the rule.", "Check the output in context."], ["حدّد المدخل والمخرج.", "عوّض المدخل في القاعدة.", "تحقق من المخرج ضمن السياق."], "If f(x) = 2x + 1, find f(3).", "إذا كانت f(x) = 2x + 1، أوجد f(3).", ["Replace x with 3: f(3) = 2(3) + 1.", "Multiply: 6 + 1 = 7.", "Therefore f(3) = 7."], ["نعوّض x بالعدد 3: f(3) = 2(3) + 1.", "نحسب: 6 + 1 = 7.", "إذن f(3) = 7."], "If g(x) = 3x - 2, find g(4).", "إذا كانت g(x) = 3x - 2، أوجد g(4).", ["8", "10", "12", "14"], "10", "Substitute 4: 3(4) - 2 = 10.", "نعوّض 4: ‏3(4) - 2 = 10."),
  lesson("limits", ["Try direct substitution.", "Factor or simplify an indeterminate form.", "Substitute again and state the limit."], ["جرّب التعويض المباشر.", "حلّل أو بسّط الصيغة غير المحددة.", "عوّض مجددًا واكتب النهاية."], "Evaluate lim(x→2) (x² - 4)/(x - 2).", "احسب lim(x→2) (x² - 4)/(x - 2).", ["Factor x² - 4 = (x - 2)(x + 2).", "Cancel x - 2 for x ≠ 2.", "Substitute x = 2: the limit is 4."], ["نحلل x² - 4 = (x - 2)(x + 2).", "نختصر x - 2 عندما x ≠ 2.", "نعوّض x = 2: النهاية تساوي 4."], "lim(x→3) (x² - 9)/(x - 3) = ?", "lim(x→3) (x² - 9)/(x - 3) = ؟", ["3", "6", "9", "12"], "6", "Factor to x + 3, then substitute 3.", "نحلل إلى x + 3 ثم نعوّض 3."),
  lesson("derivatives", ["Identify the derivative rule.", "Differentiate term by term.", "Interpret the derivative as a rate or slope."], ["حدّد قاعدة الاشتقاق.", "اشتق كل حد على حدة.", "فسّر المشتقة كمعدل تغير أو ميل."], "Find the derivative of f(x) = x³ - 4x.", "أوجد مشتقة f(x) = x³ - 4x.", ["Use the power rule: (x³)' = 3x².", "The derivative of -4x is -4.", "So f'(x) = 3x² - 4."], ["نستخدم قاعدة القوة: مشتقة x³ هي 3x².", "مشتقة -4x هي -4.", "إذن f'(x) = 3x² - 4."], "If h(x) = x² + 5x, what is h'(1)?", "إذا كانت h(x) = x² + 5x، فما قيمة h'(1)؟", ["5", "6", "7", "8"], "7", "h'(x)=2x+5, so h'(1)=7.", "h'(x)=2x+5، ولذلك h'(1)=7."),
  lesson("integration", ["Recognize the antiderivative rule.", "Integrate term by term.", "Add C for an indefinite integral and check by differentiating."], ["تعرّف قاعدة الدالة الأصلية.", "كامل كل حد على حدة.", "أضف C للتكامل غير المحدد وتحقق بالاشتقاق."], "Find ∫(3x² + 2) dx.", "أوجد ∫(3x² + 2) dx.", ["Integrate 3x² to x³.", "Integrate 2 to 2x.", "The answer is x³ + 2x + C."], ["تكامل 3x² هو x³.", "تكامل 2 هو 2x.", "النتيجة x³ + 2x + C."], "∫2x dx = ?", "∫2x dx = ؟", ["x", "x²", "2x²", "x² + C"], "x² + C", "The power rule gives x², plus C.", "تعطي قاعدة التكامل x² مع إضافة C."),
  lesson("probability", ["Define the sample space.", "Choose a complement, union, or conditional rule.", "Check that the probability is between 0 and 1."], ["حدّد فضاء العينة.", "اختر قاعدة المتمم أو الاتحاد أو الاحتمال المشروط.", "تحقق أن الاحتمال بين 0 و1."], "A fair die is rolled. What is P(even)?", "رُمي حجر نرد عادل. ما احتمال ظهور عدد زوجي؟", ["The even outcomes are 2, 4, and 6.", "There are 3 favorable outcomes out of 6.", "P(even) = 3/6 = 1/2."], ["النتائج الزوجية هي 2 و4 و6.", "هناك 3 نتائج مناسبة من أصل 6.", "P(زوجي) = 3/6 = 1/2."], "A fair die is rolled. What is P(odd)?", "رُمي حجر نرد عادل. ما احتمال ظهور عدد فردي؟", ["1/6", "1/3", "1/2", "2/3"], "1/2", "Three of six outcomes are odd.", "ثلاث نتائج من أصل ست هي فردية."),
  lesson("statistics", ["Identify the data set and its units.", "Compute the measure carefully.", "Interpret it in the original context."], ["حدّد مجموعة البيانات ووحداتها.", "احسب المقياس بدقة.", "فسّر النتيجة ضمن السياق الأصلي."], "Find the mean of 4, 6, and 8.", "أوجد متوسط 4 و6 و8.", ["Add the values: 4 + 6 + 8 = 18.", "There are 3 values.", "Mean = 18/3 = 6."], ["نجمع القيم: 4 + 6 + 8 = 18.", "عدد القيم هو 3.", "المتوسط = 18/3 = 6."], "Find the median of 2, 5, and 9.", "أوجد الوسيط للأعداد 2 و5 و9.", ["2", "5", "9", "16"], "5", "The middle ordered value is 5.", "القيمة الوسطى بعد الترتيب هي 5."),
  lesson("percentages-and-finance", ["Identify the base amount.", "Convert the rate to a decimal.", "Apply the increase or decrease and label the result."], ["حدّد المبلغ الأساسي.", "حوّل المعدل إلى عدد عشري.", "طبّق الزيادة أو النقصان وسمِّ النتيجة."], "A $80 item has a 25% discount. Find the sale price.", "ثمن سلعة 80 دولارًا عليها خصم 25%. أوجد سعر البيع.", ["Discount = 0.25 × 80 = 20.", "Subtract the discount: 80 - 20 = 60.", "The sale price is $60."], ["الخصم = 0.25 × 80 = 20.", "نطرح الخصم: 80 - 20 = 60.", "سعر البيع هو 60 دولارًا."], "A $50 item increases by 10%. New price?", "زاد سعر سلعة 50 دولارًا بنسبة 10%. ما السعر الجديد؟", ["$50", "$55", "$60", "$65"], "$55", "10% of 50 is 5, so the new price is 55.", "10% من 50 تساوي 5، لذلك السعر الجديد 55."),
  lesson("linear-models", ["Find the rate of change.", "Identify the initial value.", "Write and interpret y = mx + b."], ["أوجد معدل التغير.", "حدّد القيمة الابتدائية.", "اكتب وفسّر y = mx + b."], "A taxi charges $4 plus $2 per kilometer. Cost for 6 km?", "تتقاضى سيارة أجرة 4 دولارات زائد دولارين لكل كيلومتر. ما الكلفة لـ6 كم؟", ["The model is C = 2d + 4.", "Substitute d = 6: C = 12 + 4.", "The cost is $16."], ["النموذج هو C = 2d + 4.", "نعوّض d = 6: C = 12 + 4.", "الكلفة هي 16 دولارًا."], "A plan costs $10 plus $3 per month. Cost after 4 months?", "خطة كلفتها 10 دولارات زائد 3 دولارات شهريًا. ما الكلفة بعد 4 أشهر؟", ["$12", "$18", "$22", "$40"], "$22", "10 + 3(4) = 22.", "10 + 3(4) = 22."),
  lesson("sequences", ["Compare consecutive differences or ratios.", "Select the arithmetic or geometric formula.", "Substitute the requested term or number of terms."], ["قارن الفروق أو النسب المتتالية.", "اختر صيغة المتتالية الحسابية أو الهندسية.", "عوّض عن الحد أو عدد الحدود المطلوب."], "Find the fifth term of 3, 7, 11, …", "أوجد الحد الخامس للمتتالية 3، 7، 11، …", ["The common difference is 4.", "a₅ = a₁ + 4d = 3 + 4(4).", "a₅ = 19."], ["الفرق المشترك هو 4.", "a₅ = a₁ + 4d = 3 + 4(4).", "a₅ = 19."], "Find the fourth term of 2, 6, 18, …", "أوجد الحد الرابع للمتتالية 2، 6، 18، …", ["36", "54", "72", "108"], "54", "The ratio is 3, so a₄ = 18 × 3 = 54.", "النسبة هي 3، لذلك a₄ = 18 × 3 = 54."),
  lesson("complex-numbers", ["Separate real and imaginary parts.", "Use i² = −1.", "Simplify and report a + bi."], ["افصل الجزأين الحقيقي والتخيلي.", "استخدم i² = −1.", "بسّط واكتب النتيجة a + bi."], "Simplify (2 + i)(3 - i).", "بسّط (2 + i)(3 - i).", ["Expand: 6 - 2i + 3i - i².", "Since i² = -1, replace -i² with +1.", "The result is 7 + i."], ["نوسع: 6 - 2i + 3i - i².", "بما أن i² = -1، يصبح -i² = +1.", "النتيجة هي 7 + i."], "What is |3 + 4i|?", "ما قيمة |3 + 4i|؟", ["3", "4", "5", "7"], "5", "The modulus is √(3² + 4²) = 5.", "المعيار هو √(3² + 4²) = 5."),
  lesson("trigonometry", ["Identify the sides or angle relationship.", "Choose sine, cosine, tangent, or an identity.", "Check the quadrant and units."], ["حدّد الأضلاع أو علاقة الزاوية.", "اختر الجيب أو جيب التمام أو الظل أو متطابقة.", "تحقق من الربع ووحدات الزاوية."], "In a right triangle, opposite = 3 and hypotenuse = 5. Find sin θ.", "في مثلث قائم، المقابل = 3 والوتر = 5. أوجد sin θ.", ["Use sin θ = opposite/hypotenuse.", "Substitute: sin θ = 3/5.", "So sin θ = 0.6."], ["نستخدم sin θ = المقابل/الوتر.", "نعوّض: sin θ = 3/5.", "إذن sin θ = 0.6."], "If cos θ = 4/5 in a right triangle, find the adjacent side when hypotenuse = 10.", "إذا كان cos θ = 4/5 في مثلث قائم، أوجد الضلع المجاور عندما الوتر = 10.", ["4", "6", "8", "10"], "8", "Adjacent = (4/5) × 10 = 8.", "المجاور = (4/5) × 10 = 8."),
  lesson("exponential-models", ["Find the initial value.", "Identify the growth or decay multiplier.", "Substitute the elapsed time and interpret."], ["حدّد القيمة الابتدائية.", "حدّد مضاعف النمو أو التناقص.", "عوّض الزمن المنقضي وفسّر النتيجة."], "A population starts at 200 and doubles each year. Model it after t years.", "يبدأ عدد السكان بـ200 ويتضاعف كل سنة. نمذجه بعد t سنوات.", ["Initial value is 200.", "Doubling gives multiplier 2.", "P(t) = 200·2ᵗ."], ["القيمة الابتدائية هي 200.", "التضاعف يعطي المضاعف 2.", "P(t) = 200·2ᵗ."], "A value of 500 decreases by 10% each period. Multiplier?", "قيمة 500 تنخفض 10% في كل فترة. ما المضاعف؟", ["0.1", "0.9", "1.1", "10"], "0.9", "Decay multiplier = 1 - 0.10 = 0.90.", "مضاعف التناقص = 1 - 0.10 = 0.90."),
  lesson("random-variables", ["List each value and probability.", "Check probabilities sum to one.", "Use E(X) = ΣxP(x) when needed."], ["اكتب كل قيمة واحتمالها.", "تحقق أن مجموع الاحتمالات يساوي واحدًا.", "استخدم E(X) = ΣxP(x) عند الحاجة."], "X takes 0 and 2 with probabilities 0.25 and 0.75. Find E(X).", "يأخذ X القيمتين 0 و2 باحتمالين 0.25 و0.75. أوجد E(X).", ["Multiply each value by its probability.", "E(X) = 0(0.25) + 2(0.75).", "E(X) = 1.5."], ["نضرب كل قيمة باحتمالها.", "E(X) = 0(0.25) + 2(0.75).", "E(X) = 1.5."], "X takes 1 and 3 with equal probabilities. Find E(X).", "يأخذ X القيمتين 1 و3 باحتمالين متساويين. أوجد E(X).", ["1", "2", "3", "4"], "2", "E(X) = 1(0.5) + 3(0.5) = 2.", "E(X) = 1(0.5) + 3(0.5) = 2."),
  lesson("correlation", ["Describe the direction.", "Assess the strength from the pattern or coefficient.", "Avoid claiming causation without evidence."], ["صف الاتجاه.", "قيّم القوة من النمط أو المعامل.", "لا تدّع السببية دون دليل."], "A scatter plot rises tightly from left to right. Describe the association.", "يرتفع مخطط التشتت بشكل متقارب من اليسار إلى اليمين. صف العلاقة.", ["The direction is positive.", "The tight pattern indicates strong association.", "It is a strong positive correlation, not proof of causation."], ["الاتجاه موجب.", "النمط المتقارب يدل على علاقة قوية.", "إنها علاقة ارتباط موجبة قوية وليست دليلًا على السببية."], "A correlation coefficient r = -0.85 indicates…", "ماذا يدل معامل الارتباط r = -0.85؟", ["Weak positive", "Strong positive", "Weak negative", "Strong negative"], "Strong negative", "The magnitude is close to 1 and the sign is negative.", "المقدار قريب من 1 والإشارة سالبة."),
  lesson("quadratic-models", ["Choose a useful quadratic form.", "Find roots, vertex, or discriminant as requested.", "Check the result in the original equation."], ["اختر صيغة تربيعية مفيدة.", "أوجد الجذور أو الرأس أو المميز حسب المطلوب.", "تحقق من النتيجة في المعادلة الأصلية."], "Find the roots of x² - 5x + 6 = 0.", "أوجد جذور x² - 5x + 6 = 0.", ["Factor: (x - 2)(x - 3) = 0.", "Set each factor to zero.", "The roots are x = 2 and x = 3."], ["نحلل: (x - 2)(x - 3) = 0.", "نجعل كل عامل مساويًا للصفر.", "الجذور هي x = 2 وx = 3."], "What is the vertex x-coordinate of y = x² - 4x + 1?", "ما إحداثي x لرأس y = x² - 4x + 1؟", ["-4", "-2", "2", "4"], "2", "x = -b/(2a) = 4/2 = 2.", "x = -b/(2a) = 4/2 = 2."),
  lesson("certificate-revision", ["Write the known values.", "Select a matching method.", "Check the answer with a second representation."], ["اكتب المعطيات.", "اختر الطريقة المناسبة.", "تحقق من الجواب بتمثيل ثانٍ."], "How should you begin a mixed revision question?", "كيف تبدأ مسألة مراجعة مختلطة؟", ["Copy numbers randomly.", "Identify the given values and goal.", "Skip the units.", "Guess the formula."], ["انسخ الأعداد عشوائيًا.", "حدّد المعطيات والمطلوب.", "تجاهل الوحدات.", "خمّن الصيغة."], "Which first step is most reliable?", "ما الخطوة الأولى الأكثر موثوقية؟", ["Guess", "List givens and goal", "Round everything", "Skip reading"], "List givens and goal", "Organizing the information prevents choosing the wrong method.", "تنظيم المعلومات يمنع اختيار الطريقة الخاطئة."),
];

const expansionBySlug: Record<string, { extraExample: InteractiveExample; extraPractice: InteractivePractice[] }> = {
  functions: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "A phone plan costs 12 + 4m. Find the cost for 5 months.", arabicQuestion: "كلفة خطة هاتف هي 12 + 4m. أوجد الكلفة لـ5 أشهر.", solution: ["Substitute m = 5.", "12 + 4(5) = 32.", "The plan costs 32 units."], arabicSolution: ["نعوّض m = 5.", "12 + 4(5) = 32.", "كلفة الخطة 32 وحدة."] }, extraPractice: [{ question: "If p(x)=5x+1, find p(2).", arabicQuestion: "إذا كانت p(x)=5x+1، أوجد p(2).", options: ["6", "10", "11", "12"], answer: "11", explanation: "5(2)+1=11.", arabicExplanation: "5(2)+1=11.", difficulty: "guided" }, { question: "Which input gives f(x)=9 for f(x)=2x+3?", arabicQuestion: "أي مدخل يعطي f(x)=9 للدالة f(x)=2x+3؟", options: ["2", "3", "4", "6"], answer: "3", explanation: "2x+3=9 gives x=3.", arabicExplanation: "2x+3=9، ومنه x=3.", difficulty: "challenge" }] },
  limits: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Evaluate lim(x→1) (x² - 1)/(x - 1).", arabicQuestion: "احسب lim(x→1) (x² - 1)/(x - 1).", solution: ["Factor x²-1=(x-1)(x+1).", "Cancel x-1.", "Substitute 1: the limit is 2."], arabicSolution: ["نحلل x²-1=(x-1)(x+1).", "نختصر x-1.", "نعوّض 1: النهاية تساوي 2."] }, extraPractice: [{ question: "lim(x→4) (x²-16)/(x-4) = ?", arabicQuestion: "lim(x→4) (x²-16)/(x-4) = ؟", options: ["4", "8", "12", "16"], answer: "8", explanation: "Factor to x+4, then substitute 4.", arabicExplanation: "نحلل إلى x+4 ثم نعوّض 4.", difficulty: "guided" }, { question: "lim(x→2) (x+5) = ?", arabicQuestion: "lim(x→2) (x+5) = ؟", options: ["5", "6", "7", "10"], answer: "7", explanation: "Direct substitution gives 2+5.", arabicExplanation: "التعويض المباشر يعطي 2+5.", difficulty: "standard" }] },
  derivatives: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "The position is s(t)=t²+3t. Find the velocity at t=2.", arabicQuestion: "الموضع s(t)=t²+3t. أوجد السرعة عند t=2.", solution: ["Velocity is s'(t)=2t+3.", "Evaluate at t=2.", "v(2)=7 units per time."], arabicSolution: ["السرعة هي s'(t)=2t+3.", "نعوّض t=2.", "v(2)=7 وحدة زمنية."] }, extraPractice: [{ question: "Find d/dx(4x³).", arabicQuestion: "أوجد d/dx(4x³).", options: ["4x²", "7x²", "12x²", "12x³"], answer: "12x²", explanation: "Use the power rule.", arabicExplanation: "نستخدم قاعدة القوة.", difficulty: "guided" }, { question: "For f'(x)=2x-6, where is the slope zero?", arabicQuestion: "للدالة f'(x)=2x-6، أين يساوي الميل صفرًا؟", options: ["0", "2", "3", "6"], answer: "3", explanation: "2x-6=0 gives x=3.", arabicExplanation: "2x-6=0، ومنه x=3.", difficulty: "challenge" }] },
  integration: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Find the area under y=2x from x=0 to x=3.", arabicQuestion: "أوجد المساحة تحت y=2x من x=0 إلى x=3.", solution: ["Integrate: ∫2x dx=x².", "Evaluate x² from 0 to 3.", "Area = 9 square units."], arabicSolution: ["نكامل: ∫2x dx=x².", "نحسب x² بين 0 و3.", "المساحة = 9 وحدات مربعة."] }, extraPractice: [{ question: "∫(3x²)dx = ?", arabicQuestion: "∫(3x²)dx = ؟", options: ["x³+C", "3x³+C", "x²+C", "6x+C"], answer: "x³+C", explanation: "Increase the power and divide by the new power.", arabicExplanation: "نرفع الأس ونقسم على الأس الجديد.", difficulty: "guided" }, { question: "∫₀² x dx = ?", arabicQuestion: "∫₀² x dx = ؟", options: ["1", "2", "4", "8"], answer: "2", explanation: "Evaluate x²/2 from 0 to 2.", arabicExplanation: "نحسب x²/2 بين 0 و2.", difficulty: "challenge" }] },
  probability: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "A bag has 3 red and 2 blue balls. Find P(red).", arabicQuestion: "كيس فيه 3 كرات حمراء و2 زرقاء. أوجد P(حمراء).", solution: ["Total outcomes = 5.", "Favorable red outcomes = 3.", "P(red)=3/5."], arabicSolution: ["عدد النتائج الكلي = 5.", "النتائج المناسبة الحمراء = 3.", "P(حمراء)=3/5."] }, extraPractice: [{ question: "A coin is tossed twice. P(two heads)?", arabicQuestion: "رُميت قطعة نقد مرتين. ما احتمال ظهور صورتين؟", options: ["1/2", "1/3", "1/4", "3/4"], answer: "1/4", explanation: "Independent heads: 1/2 × 1/2.", arabicExplanation: "الحدثان مستقلان: 1/2 × 1/2.", difficulty: "guided" }, { question: "If P(A)=0.3, P(not A)=?", arabicQuestion: "إذا كان P(A)=0.3، فما P(ليس A)؟", options: ["0.3", "0.5", "0.7", "1.3"], answer: "0.7", explanation: "Use the complement: 1-0.3.", arabicExplanation: "نستخدم المتمم: 1-0.3.", difficulty: "challenge" }] },
  statistics: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Find the range of 5, 8, 11, and 14.", arabicQuestion: "أوجد المدى للأعداد 5 و8 و11 و14.", solution: ["Maximum = 14 and minimum = 5.", "Subtract: 14-5.", "Range = 9."], arabicSolution: ["القيمة العظمى = 14 والصغرى = 5.", "نطرح: 14-5.", "المدى = 9."] }, extraPractice: [{ question: "Mean of 3, 3, 9?", arabicQuestion: "ما متوسط 3 و3 و9؟", options: ["3", "4", "5", "6"], answer: "5", explanation: "(3+3+9)/3=5.", arabicExplanation: "(3+3+9)/3=5.", difficulty: "guided" }, { question: "Which measure is least affected by an outlier?", arabicQuestion: "أي مقياس يتأثر أقل بالقيمة الشاذة؟", options: ["Mean", "Median", "Sum", "Range"], answer: "Median", explanation: "The median depends on order, not extreme distance.", arabicExplanation: "الوسيط يعتمد على الترتيب لا على بُعد القيم المتطرفة.", difficulty: "challenge" }] },
  "percentages-and-finance": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "An $120 bill has 15% tax. Find the total.", arabicQuestion: "فاتورة 120 دولارًا عليها ضريبة 15%. أوجد المجموع.", solution: ["Tax = 0.15×120 = 18.", "Add tax to the base.", "Total = $138."], arabicSolution: ["الضريبة = 0.15×120 = 18.", "نضيف الضريبة إلى المبلغ الأساسي.", "المجموع = 138 دولارًا."] }, extraPractice: [{ question: "20% of $90 = ?", arabicQuestion: "ما قيمة 20% من 90 دولارًا؟", options: ["9", "18", "20", "72"], answer: "18", explanation: "0.20×90=18.", arabicExplanation: "0.20×90=18.", difficulty: "guided" }, { question: "$200 discounted 30% becomes?", arabicQuestion: "سلعة بـ200 دولار خُفّضت 30%. ما السعر؟", options: ["$60", "$140", "$170", "$230"], answer: "$140", explanation: "Keep 70%: 0.70×200=140.", arabicExplanation: "نحتفظ بـ70%: 0.70×200=140.", difficulty: "standard" }] },
  "linear-models": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "A gym charges $25 joining fee plus $15 per visit. Cost for 4 visits?", arabicQuestion: "نادٍ رياضي يتقاضى 25 دولارًا للتسجيل و15 لكل زيارة. ما كلفة 4 زيارات؟", solution: ["Model C=15v+25.", "Substitute v=4.", "C=$85."], arabicSolution: ["النموذج C=15v+25.", "نعوّض v=4.", "C=85 دولارًا."] }, extraPractice: [{ question: "Slope through (1,3) and (3,7)?", arabicQuestion: "ما ميل المستقيم المار بـ(1,3) و(3,7)؟", options: ["1", "2", "3", "4"], answer: "2", explanation: "(7-3)/(3-1)=2.", arabicExplanation: "(7-3)/(3-1)=2.", difficulty: "guided" }, { question: "In y=4x+9, the intercept is…", arabicQuestion: "في y=4x+9، ما الجزء المقطوع؟", options: ["4", "5", "9", "13"], answer: "9", explanation: "The constant is the y-intercept.", arabicExplanation: "الحد الثابت هو الجزء المقطوع على محور y.", difficulty: "standard" }] },
  sequences: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Find the sum of the first 4 terms of 2, 5, 8, …", arabicQuestion: "أوجد مجموع أول 4 حدود للمتتالية 2 و5 و8…", solution: ["The terms are 2,5,8,11.", "Add them: 2+5+8+11.", "The sum is 26."], arabicSolution: ["الحدود هي 2 و5 و8 و11.", "نجمعها: 2+5+8+11.", "المجموع هو 26."] }, extraPractice: [{ question: "Common difference of 10, 6, 2?", arabicQuestion: "ما الفرق المشترك للمتتالية 10 و6 و2؟", options: ["-8", "-4", "2", "4"], answer: "-4", explanation: "Subtract consecutive terms.", arabicExplanation: "نطرح حدين متتاليين.", difficulty: "guided" }, { question: "Next term: 3, 6, 12, …", arabicQuestion: "ما الحد التالي: 3 و6 و12…؟", options: ["15", "18", "21", "24"], answer: "24", explanation: "Multiply by 2.", arabicExplanation: "نضرب في 2.", difficulty: "standard" }] },
  "complex-numbers": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Find the conjugate of 5-2i.", arabicQuestion: "أوجد مرافق 5-2i.", solution: ["Keep the real part.", "Change the sign of the imaginary part.", "The conjugate is 5+2i."], arabicSolution: ["نحافظ على الجزء الحقيقي.", "نغيّر إشارة الجزء التخيلي.", "المرافق هو 5+2i."] }, extraPractice: [{ question: "i² = ?", arabicQuestion: "ما قيمة i²؟", options: ["-1", "0", "1", "i"], answer: "-1", explanation: "This is the defining relation for i.", arabicExplanation: "هذه هي العلاقة الأساسية للعدد i.", difficulty: "guided" }, { question: "|6+8i| = ?", arabicQuestion: "ما قيمة |6+8i|؟", options: ["8", "10", "12", "14"], answer: "10", explanation: "√(6²+8²)=10.", arabicExplanation: "√(6²+8²)=10.", difficulty: "standard" }] },
  trigonometry: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "If tan θ=3/4 and adjacent=8, find opposite.", arabicQuestion: "إذا كان tan θ=3/4 والمجاور=8، أوجد المقابل.", solution: ["tan θ=opposite/adjacent.", "opposite=(3/4)×8.", "Opposite=6."], arabicSolution: ["tan θ=المقابل/المجاور.", "المقابل=(3/4)×8.", "المقابل=6."] }, extraPractice: [{ question: "sin 30° = ?", arabicQuestion: "ما قيمة sin 30°؟", options: ["0", "1/2", "√2/2", "1"], answer: "1/2", explanation: "Use the special-angle table.", arabicExplanation: "نستخدم جدول الزوايا الخاصة.", difficulty: "guided" }, { question: "If sin θ=0.6 and hypotenuse=10, opposite=?", arabicQuestion: "إذا كان sin θ=0.6 والوتر=10، فما المقابل؟", options: ["4", "6", "8", "10"], answer: "6", explanation: "opposite=0.6×10.", arabicExplanation: "المقابل=0.6×10.", difficulty: "standard" }] },
  "exponential-models": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "A $400 investment grows 5% per year. Write its value after t years.", arabicQuestion: "استثمار 400 دولار ينمو 5% سنويًا. اكتب قيمته بعد t سنوات.", solution: ["Initial value=400.", "Growth multiplier=1.05.", "V(t)=400(1.05)^t."], arabicSolution: ["القيمة الابتدائية=400.", "مضاعف النمو=1.05.", "V(t)=400(1.05)^t."] }, extraPractice: [{ question: "10% growth multiplier?", arabicQuestion: "ما مضاعف نمو 10%؟", options: ["0.1", "0.9", "1.1", "10"], answer: "1.1", explanation: "1+0.10=1.10.", arabicExplanation: "1+0.10=1.10.", difficulty: "guided" }, { question: "A value 800 halves each period. After 2 periods?", arabicQuestion: "قيمة 800 تنخفض إلى النصف كل فترة. بعد فترتين؟", options: ["100", "200", "400", "600"], answer: "200", explanation: "800(1/2)^2=200.", arabicExplanation: "800(1/2)^2=200.", difficulty: "standard" }] },
  "random-variables": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "X=1,2 with probabilities .4,.6. Find E(X).", arabicQuestion: "X=1 و2 باحتمالين 0.4 و0.6. أوجد E(X).", solution: ["Multiply each value by its probability.", "E(X)=1(.4)+2(.6).", "E(X)=1.6."], arabicSolution: ["نضرب كل قيمة باحتمالها.", "E(X)=1(.4)+2(.6).", "E(X)=1.6."] }, extraPractice: [{ question: "Probabilities .2,.3,? sum to 1. Missing?", arabicQuestion: "احتمالات 0.2 و0.3 و؟ مجموعها 1. ما الناقص؟", options: ["0.3", "0.4", "0.5", "0.6"], answer: "0.5", explanation: "1-.2-.3=.5.", arabicExplanation: "1-.2-.3=.5.", difficulty: "guided" }, { question: "If X always equals 4, E(X)=?", arabicQuestion: "إذا كان X يساوي 4 دائمًا، فما E(X)؟", options: ["0", "1", "2", "4"], answer: "4", explanation: "A constant has expected value equal to itself.", arabicExplanation: "القيمة الثابتة تساوي قيمتها المتوقعة.", difficulty: "standard" }] },
  correlation: { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "r=0.2 describes what kind of association?", arabicQuestion: "ماذا يصف r=0.2؟", solution: ["The sign is positive.", "The magnitude is close to zero.", "It is a weak positive association."], arabicSolution: ["الإشارة موجبة.", "المقدار قريب من الصفر.", "إنها علاقة موجبة ضعيفة."] }, extraPractice: [{ question: "r=-1 means…", arabicQuestion: "ماذا يعني r=-1؟", options: ["Perfect positive", "No relation", "Weak negative", "Perfect negative"], answer: "Perfect negative", explanation: "The magnitude is 1 and the sign is negative.", arabicExplanation: "المقدار 1 والإشارة سالبة.", difficulty: "guided" }, { question: "Correlation alone proves…", arabicQuestion: "الارتباط وحده يثبت…", options: ["Causation", "Association only", "No pattern", "An experiment"], answer: "Association only", explanation: "Correlation does not establish causation.", arabicExplanation: "الارتباط لا يثبت السببية.", difficulty: "challenge" }] },
  "quadratic-models": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "Find the vertex x-coordinate of y=x²+6x+2.", arabicQuestion: "أوجد إحداثي x لرأس y=x²+6x+2.", solution: ["Use x=-b/(2a).", "x=-6/2.", "The x-coordinate is -3."], arabicSolution: ["نستخدم x=-b/(2a).", "x=-6/2.", "إحداثي x هو -3."] }, extraPractice: [{ question: "Discriminant of x²-4x+4?", arabicQuestion: "ما مميز x²-4x+4؟", options: ["0", "4", "8", "16"], answer: "0", explanation: "b²-4ac=16-16=0.", arabicExplanation: "b²-4ac=16-16=0.", difficulty: "guided" }, { question: "Roots of x²-9=0?", arabicQuestion: "ما جذرا x²-9=0؟", options: ["0,9", "-3,3", "3,9", "-9,9"], answer: "-3,3", explanation: "x²=9 gives x=±3.", arabicExplanation: "x²=9، ومنه x=±3.", difficulty: "standard" }] },
  "certificate-revision": { extraExample: { label: "Applied example", arabicLabel: "مثال تطبيقي", question: "A word problem gives rate 5 and starting value 12. Write a linear model.", arabicQuestion: "مسألة تعطي معدلًا 5 وقيمة ابتدائية 12. اكتب نموذجًا خطيًا.", solution: ["Rate is the slope m=5.", "Starting value is b=12.", "The model is y=5x+12."], arabicSolution: ["المعدل هو الميل m=5.", "القيمة الابتدائية b=12.", "النموذج y=5x+12."] }, extraPractice: [{ question: "What should you do before choosing a formula?", arabicQuestion: "ماذا تفعل قبل اختيار الصيغة؟", options: ["Guess", "List givens and goal", "Skip units", "Round"], answer: "List givens and goal", explanation: "Organize the information first.", arabicExplanation: "نظّم المعطيات والمطلوب أولًا.", difficulty: "guided" }, { question: "A reliable final check is…", arabicQuestion: "ما التحقق النهائي الموثوق؟", options: ["Ignore units", "Substitute back", "Erase work", "Guess again"], answer: "Substitute back", explanation: "Substitution checks consistency.", arabicExplanation: "التعويض يتحقق من الاتساق.", difficulty: "standard" }] },
};

const typedPracticeBySlug: Record<string, TypedPractice> = {
  functions: { question: "If f(x)=2x+1, type f(5).", arabicQuestion: "إذا كانت f(x)=2x+1، اكتب f(5).", answer: "11", acceptedAnswers: [], explanation: "Substitute x=5: 2(5)+1=11.", arabicExplanation: "نعوّض x=5: 2(5)+1=11.", difficulty: "guided", placeholder: "e.g. 11" },
  limits: { question: "Type lim(x→2) (x²-4)/(x-2).", arabicQuestion: "اكتب lim(x→2) (x²-4)/(x-2).", answer: "4", acceptedAnswers: ["4.0"], explanation: "Factor and cancel to x+2, then substitute 2.", arabicExplanation: "نحلل ونختصر إلى x+2 ثم نعوّض 2.", difficulty: "standard", placeholder: "e.g. 4" },
  derivatives: { question: "For f(x)=x³, type f'(2).", arabicQuestion: "للدالة f(x)=x³، اكتب f'(2).", answer: "12", acceptedAnswers: ["12.0"], explanation: "f'(x)=3x², so f'(2)=12.", arabicExplanation: "f'(x)=3x²، ولذلك f'(2)=12.", difficulty: "standard", placeholder: "e.g. 12" },
  integration: { question: "Type ∫2x dx without the constant C.", arabicQuestion: "اكتب ∫2x dx من دون الثابت C.", answer: "x^2", acceptedAnswers: ["x²"], explanation: "The antiderivative of 2x is x².", arabicExplanation: "الدالة الأصلية لـ2x هي x².", difficulty: "standard", placeholder: "e.g. x^2" },
  probability: { question: "A fair die is rolled. Type P(even) as a decimal.", arabicQuestion: "رُمي حجر نرد عادل. اكتب P(زوجي) كعدد عشري.", answer: "0.5", acceptedAnswers: ["1/2", ".5"], explanation: "Three even outcomes out of six gives 3/6=0.5.", arabicExplanation: "ثلاث نتائج زوجية من أصل ست تعطي 3/6=0.5.", difficulty: "guided", placeholder: "e.g. 0.5 or 1/2" },
  statistics: { question: "Type the mean of 5, 7, and 9.", arabicQuestion: "اكتب متوسط 5 و7 و9.", answer: "7", acceptedAnswers: ["7.0"], explanation: "(5+7+9)/3=7.", arabicExplanation: "(5+7+9)/3=7.", difficulty: "guided", placeholder: "e.g. 7" },
  "percentages-and-finance": { question: "Type 15% of 200.", arabicQuestion: "اكتب قيمة 15% من 200.", answer: "30", acceptedAnswers: ["30.0"], explanation: "0.15×200=30.", arabicExplanation: "0.15×200=30.", difficulty: "guided", placeholder: "e.g. 30" },
  "linear-models": { question: "A taxi costs 4+2d. Type the cost for d=8.", arabicQuestion: "كلفة سيارة الأجرة 4+2d. اكتب الكلفة عندما d=8.", answer: "20", acceptedAnswers: ["20.0"], explanation: "4+2(8)=20.", arabicExplanation: "4+2(8)=20.", difficulty: "guided", placeholder: "e.g. 20" },
  sequences: { question: "Type the next term: 4, 7, 10, …", arabicQuestion: "اكتب الحد التالي: 4، 7، 10، …", answer: "13", acceptedAnswers: [], explanation: "The common difference is 3, so 10+3=13.", arabicExplanation: "الفرق المشترك هو 3، لذلك 10+3=13.", difficulty: "guided", placeholder: "e.g. 13" },
  "complex-numbers": { question: "Type |3+4i|.", arabicQuestion: "اكتب |3+4i|.", answer: "5", acceptedAnswers: ["5.0"], explanation: "√(3²+4²)=5.", arabicExplanation: "√(3²+4²)=5.", difficulty: "standard", placeholder: "e.g. 5" },
  trigonometry: { question: "If sin θ=3/5 and hypotenuse=10, type the opposite side.", arabicQuestion: "إذا كان sin θ=3/5 والوتر=10، اكتب الضلع المقابل.", answer: "6", acceptedAnswers: ["6.0"], explanation: "Opposite=(3/5)×10=6.", arabicExplanation: "المقابل=(3/5)×10=6.", difficulty: "standard", placeholder: "e.g. 6" },
  "exponential-models": { question: "A value 100 doubles twice. Type the final value.", arabicQuestion: "قيمة 100 تتضاعف مرتين. اكتب القيمة النهائية.", answer: "400", acceptedAnswers: ["400.0"], explanation: "100×2²=400.", arabicExplanation: "100×2²=400.", difficulty: "guided", placeholder: "e.g. 400" },
  "random-variables": { question: "X is 2 or 4 with equal probabilities. Type E(X).", arabicQuestion: "يأخذ X القيمة 2 أو4 باحتمالين متساويين. اكتب E(X).", answer: "3", acceptedAnswers: ["3.0"], explanation: "E(X)=2(0.5)+4(0.5)=3.", arabicExplanation: "E(X)=2(0.5)+4(0.5)=3.", difficulty: "standard", placeholder: "e.g. 3" },
  correlation: { question: "Type the correlation direction for r=-0.7.", arabicQuestion: "اكتب اتجاه الارتباط عندما r=-0.7.", answer: "negative", acceptedAnswers: ["negative correlation", "سالب", "سلبي"], explanation: "The negative sign indicates a negative direction.", arabicExplanation: "الإشارة السالبة تدل على اتجاه سالب.", difficulty: "standard", placeholder: "e.g. negative" },
  "quadratic-models": { question: "Type the x-coordinate of the vertex of y=x²-6x+1.", arabicQuestion: "اكتب إحداثي x لرأس y=x²-6x+1.", answer: "3", acceptedAnswers: ["3.0"], explanation: "x=-b/(2a)=6/2=3.", arabicExplanation: "x=-b/(2a)=6/2=3.", difficulty: "standard", placeholder: "e.g. 3" },
  "certificate-revision": { question: "A rate is 4 and the initial value is 9. Type the model's value at x=2.", arabicQuestion: "المعدل 4 والقيمة الابتدائية 9. اكتب قيمة النموذج عند x=2.", answer: "17", acceptedAnswers: ["17.0"], explanation: "y=4x+9, so y=4(2)+9=17.", arabicExplanation: "y=4x+9، لذلك y=4(2)+9=17.", difficulty: "guided", placeholder: "e.g. 17" },
};

for (const item of interactiveLessons) {
  const expansion = expansionBySlug[item.slug] ?? expansionBySlug["certificate-revision"];
  const firstExample: InteractiveExample = { label: "Worked example", arabicLabel: "مثال محلول", question: item.example.question, arabicQuestion: item.example.arabicQuestion, solution: item.example.solution, arabicSolution: item.example.arabicSolution };
  const basePractice: InteractivePractice = { ...item.practice, difficulty: "standard" };
  item.examples = [firstExample, expansion.extraExample];
  item.practiceSet = [basePractice, ...expansion.extraPractice];
  item.typedPracticeSet = [typedPracticeBySlug[item.slug] ?? typedPracticeBySlug["certificate-revision"]];
}

const bySlug = new Map(interactiveLessons.map((item) => [item.slug, item]));
export function getInteractiveLesson(slug: string) { return bySlug.get(slug) ?? bySlug.get("certificate-revision")!; }
