export type LessonReviewLink = {
  slug: string;
  skill: string;
  arabicSkill: string;
  title: string;
  arabicTitle: string;
  summary: string;
  arabicSummary: string;
  focus: string;
  arabicFocus: string;
};

const entries: LessonReviewLink[] = [
  { slug: "functions", skill: "Functions", arabicSkill: "الدوال", title: "Functions review", arabicTitle: "مراجعة الدوال", summary: "Review domain, range, substitution, and how to read a function from its representation.", arabicSummary: "راجع المجال والمدى والتعويض وكيفية قراءة الدالة من تمثيلها.", focus: "Identify the input, output, and operation before calculating.", arabicFocus: "حدّد المدخل والمخرج والعملية قبل إجراء الحساب." },
  { slug: "limits", skill: "Limits", arabicSkill: "النهايات", title: "Limits review", arabicTitle: "مراجعة النهايات", summary: "Use direct substitution, factorization, and one-sided reasoning to evaluate limits.", arabicSummary: "استخدم التعويض المباشر والتحليل ودراسة الجهات لحساب النهايات.", focus: "Simplify the expression before substituting when an indeterminate form appears.", arabicFocus: "بسّط التعبير قبل التعويض عندما تظهر صيغة غير محددة." },
  { slug: "derivatives", skill: "Derivatives", arabicSkill: "المشتقات", title: "Derivatives review", arabicTitle: "مراجعة المشتقات", summary: "Connect derivative rules to rate of change, tangent slope, and optimization.", arabicSummary: "اربط قواعد الاشتقاق بمعدل التغير وميل المماس ومسائل التحسين.", focus: "Choose the rule, differentiate carefully, then interpret the result.", arabicFocus: "اختر القاعدة، اشتق بدقة، ثم فسّر النتيجة." },
  { slug: "integration", skill: "Integration", arabicSkill: "التكامل", title: "Integration review", arabicTitle: "مراجعة التكامل", summary: "Review antiderivatives, constants, and the meaning of definite integrals as accumulated change.", arabicSummary: "راجع الدوال الأصلية وثابت التكامل ومعنى التكامل المحدد كتغير متراكم.", focus: "Differentiate your antiderivative to check the result.", arabicFocus: "اشتق الدالة الأصلية للتحقق من النتيجة." },
  { slug: "probability", skill: "Probability", arabicSkill: "الاحتمالات", title: "Probability review", arabicTitle: "مراجعة الاحتمالات", summary: "Organize outcomes, use complementary events, and distinguish independent from conditional events.", arabicSummary: "نظّم النتائج، واستخدم الحدث المتمم، وميّز بين الأحداث المستقلة والمشروطة.", focus: "Define the sample space before selecting a probability rule.", arabicFocus: "حدّد فضاء العينة قبل اختيار قاعدة الاحتمال." },
  { slug: "statistics", skill: "Statistics", arabicSkill: "الإحصاء", title: "Statistics review", arabicTitle: "مراجعة الإحصاء", summary: "Interpret mean, variance, standard deviation, and data displays with attention to context.", arabicSummary: "فسّر المتوسط والتباين والانحراف المعياري وتمثيلات البيانات ضمن سياقها.", focus: "State what the number means for the data set, not only how it was computed.", arabicFocus: "اذكر معنى العدد لمجموعة البيانات، وليس طريقة حسابه فقط." },
  { slug: "percentages-and-finance", skill: "Percentages", arabicSkill: "النسب المئوية", title: "Percentages and finance review", arabicTitle: "مراجعة النسب والرياضيات المالية", summary: "Practice percentage change, discounts, markups, and interpreting financial quantities.", arabicSummary: "تدرّب على التغير النسبي والخصومات والزيادات وتفسير الكميات المالية.", focus: "Separate the base amount from the percentage rate.", arabicFocus: "افصل المبلغ الأساسي عن معدل النسبة المئوية." },
  { slug: "linear-models", skill: "Linear models", arabicSkill: "النماذج الخطية", title: "Linear models review", arabicTitle: "مراجعة النماذج الخطية", summary: "Build and interpret linear equations from rates, tables, graphs, and real-world constraints.", arabicSummary: "أنشئ وفسّر المعادلات الخطية من المعدلات والجداول والرسوم والقيود الواقعية.", focus: "Label the slope and intercept in the context of the problem.", arabicFocus: "سمِّ الميل والجزء المقطوع ضمن سياق المسألة." },
  { slug: "sequences", skill: "Sequences", arabicSkill: "المتتاليات", title: "Sequences review", arabicTitle: "مراجعة المتتاليات", summary: "Recognize arithmetic and geometric patterns, then select the correct term or sum formula.", arabicSummary: "تعرّف الأنماط الحسابية والهندسية ثم اختر صيغة الحد أو المجموع المناسبة.", focus: "Compare consecutive terms or ratios before choosing a formula.", arabicFocus: "قارن الحدود المتتالية أو النسب قبل اختيار الصيغة." },
  { slug: "complex-numbers", skill: "Complex numbers", arabicSkill: "الأعداد المركبة", title: "Complex numbers review", arabicTitle: "مراجعة الأعداد المركبة", summary: "Work with real and imaginary parts, conjugates, modulus, and products of complex numbers.", arabicSummary: "تدرّب على الجزأين الحقيقي والتخيلي والمرافق والمعيار وضرب الأعداد المركبة.", focus: "Use i² = −1 and keep real and imaginary parts organized.", arabicFocus: "استخدم i² = −1 ونظّم الجزأين الحقيقي والتخيلي." },
  { slug: "trigonometry", skill: "Trigonometry", arabicSkill: "المثلثات", title: "Trigonometry review", arabicTitle: "مراجعة المثلثات", summary: "Choose identities and right-triangle relationships carefully, with attention to angle units and signs.", arabicSummary: "اختر المتطابقات وعلاقات المثلث القائم بدقة مع الانتباه لوحدات الزوايا والإشارات.", focus: "Sketch the triangle or unit-circle position before calculating.", arabicFocus: "ارسم المثلث أو موضع دائرة الوحدة قبل الحساب." },
  { slug: "exponential-models", skill: "Exponential modeling", arabicSkill: "النمذجة الأسية", title: "Exponential models review", arabicTitle: "مراجعة النمذجة الأسية", summary: "Model growth and decay using an initial value, a multiplier, and elapsed time.", arabicSummary: "نمذج النمو والتناقص باستخدام القيمة الابتدائية والمضاعف والزمن المنقضي.", focus: "Decide whether the multiplier represents growth or decay.", arabicFocus: "حدّد ما إذا كان المضاعف يمثل نموًا أم تناقصًا." },
  { slug: "random-variables", skill: "Random variables", arabicSkill: "المتغيرات العشوائية", title: "Random variables review", arabicTitle: "مراجعة المتغيرات العشوائية", summary: "Read a discrete distribution, check probabilities, and calculate expected value.", arabicSummary: "اقرأ التوزيع المنفصل، وتحقق من الاحتمالات، واحسب القيمة المتوقعة.", focus: "Check that all probabilities are nonnegative and sum to one.", arabicFocus: "تحقق من أن كل الاحتمالات غير سالبة ومجموعها يساوي واحدًا." },
  { slug: "correlation", skill: "Correlation", arabicSkill: "الارتباط", title: "Correlation review", arabicTitle: "مراجعة الارتباط", summary: "Interpret direction and strength of association without confusing correlation with causation.", arabicSummary: "فسّر اتجاه وقوة العلاقة دون الخلط بين الارتباط والسببية.", focus: "Describe direction, strength, and context together.", arabicFocus: "صف الاتجاه والقوة والسياق معًا." },
  { slug: "quadratic-models", skill: "Quadratic models", arabicSkill: "النماذج التربيعية", title: "Quadratic models review", arabicTitle: "مراجعة النماذج التربيعية", summary: "Use roots, vertex form, and discriminant reasoning to analyze quadratic models.", arabicSummary: "استخدم الجذور وصيغة الرأس والمميز لتحليل النماذج التربيعية.", focus: "Choose the representation that matches the question being asked.", arabicFocus: "اختر التمثيل الذي يناسب السؤال المطلوب." },
];

const bySkill = new Map(entries.map((entry) => [entry.skill, entry]));

export function getLessonReviewLink(skill: string): LessonReviewLink {
  return bySkill.get(skill) ?? { slug: "certificate-revision", skill, arabicSkill: skill, title: `${skill} review`, arabicTitle: `مراجعة ${skill}`, summary: "Review the key definitions, methods, and worked examples for this skill.", arabicSummary: "راجع التعريفات والقواعد والأمثلة المحلولة الأساسية لهذه المهارة.", focus: "Write the known values first, then choose a method and check the result.", arabicFocus: "اكتب المعطيات أولًا، ثم اختر الطريقة وتحقق من النتيجة." };
}

export const lessonReviewEntries = entries;
