export type BankQuestion = {
  id: string;
  grade: "Grade 9" | "Grade 11" | "Grade 12";
  branch: "General Sciences" | "Life Sciences" | "Sociology and Economics" | "Sciences" | "Middle School";
  skill: string;
  prompt: string;
  arabicPrompt: string;
  options: readonly string[];
  correctIndex: number;
  explanation: string;
  arabicExplanation: string;
  patternSource: string;
};

export const uploadedExamQuestionBank: readonly BankQuestion[] = [
  { id: "bank-g9-proportion", grade: "Grade 9", branch: "Middle School", skill: "Proportions", prompt: "A recipe uses 3 cups of flour for 8 servings. How many cups are needed for 20 servings?", arabicPrompt: "تستعمل وصفة 3 أكواب من الطحين لثماني حصص. كم كوبًا نحتاج إلى 20 حصة؟", options: ["5 cups", "6 cups", "7.5 cups", "8 cups"], correctIndex: 2, explanation: "The scale factor is 20/8 = 2.5, so 3 × 2.5 = 7.5 cups.", arabicExplanation: "عامل التناسب هو 20/8 = 2.5، إذن 3 × 2.5 = 7.5 أكواب.", patternSource: "Test1Term3grade9.pdf · proportions" },
  { id: "bank-g9-coordinate", grade: "Grade 9", branch: "Middle School", skill: "Coordinate geometry", prompt: "What is the distance between P(1, 2) and Q(7, 10)?", arabicPrompt: "ما المسافة بين P(1, 2) وQ(7, 10)؟", options: ["8", "10", "12", "14"], correctIndex: 1, explanation: "Distance = √((7−1)² + (10−2)²) = √(36 + 64) = 10.", arabicExplanation: "المسافة = √((7−1)² + (10−2)²) = √(36 + 64) = 10.", patternSource: "Test1Term2grade9forabscent.pdf · coordinates and distance" },
  { id: "bank-g11-probability", grade: "Grade 11", branch: "Sciences", skill: "Conditional probability", prompt: "A box has 5 red and 3 blue tokens. After drawing one red token without replacement, what is the chance the next token is blue?", arabicPrompt: "صندوق فيه 5 كرات حمراء و3 زرقاء. بعد سحب كرة حمراء دون إرجاع، ما احتمال أن تكون التالية زرقاء؟", options: ["3/8", "3/7", "5/7", "1/2"], correctIndex: 1, explanation: "There are 7 tokens left and 3 are blue, so the conditional probability is 3/7.", arabicExplanation: "تبقى 7 كرات، منها 3 زرقاء، لذلك الاحتمال الشرطي هو 3/7.", patternSource: "test2term3forgrade11S.pdf · conditional probability" },
  { id: "bank-g11-derivative", grade: "Grade 11", branch: "Sciences", skill: "Derivatives", prompt: "For f(x) = x³ − 4x, find f′(2).", arabicPrompt: "إذا كانت f(x) = x³ − 4x، أوجد f′(2).", options: ["4", "8", "12", "16"], correctIndex: 2, explanation: "f′(x) = 3x² − 4, so f′(2) = 12 − 4 = 8.".replace("= 12 − 4 = 8", "= 3(2)² − 4 = 8"), arabicExplanation: "f′(x) = 3x² − 4، لذلك f′(2) = 3(2)² − 4 = 8.", patternSource: "test2term3forgrade11S.pdf · limits and derivatives" },
  { id: "bank-g12ls-log", grade: "Grade 12", branch: "Life Sciences", skill: "Logarithmic functions", prompt: "Solve ln(x) = 2 for x > 0.", arabicPrompt: "حلّ ln(x) = 2 حيث x > 0.", options: ["x = 2", "x = e²", "x = ln(2)", "x = 10²"], correctIndex: 1, explanation: "Apply the exponential function to both sides: x = e².", arabicExplanation: "نطبّق الدالة الأسية على الطرفين فنحصل على x = e².", patternSource: "test2forgrade12LS.pdf · logarithmic functions" },
  { id: "bank-g12ls-integral", grade: "Grade 12", branch: "Life Sciences", skill: "Integration", prompt: "Evaluate ∫₀² 3x² dx.", arabicPrompt: "احسب ∫₀² 3x² dx.", options: ["4", "6", "8", "12"], correctIndex: 2, explanation: "An antiderivative is x³. Evaluate x³ from 0 to 2: 8 − 0 = 8.", arabicExplanation: "دالة أصلية هي x³. نحسب من 0 إلى 2: 8 − 0 = 8.", patternSource: "test2forgrade12LS.pdf · integration" },
  { id: "bank-g12ls-probability", grade: "Grade 12", branch: "Life Sciences", skill: "Random variables", prompt: "A random variable X takes values 0 and 2 with probabilities 0.3 and 0.7. Find E(X).", arabicPrompt: "يأخذ المتغير العشوائي X القيمتين 0 و2 باحتمالين 0.3 و0.7. أوجد E(X).", options: ["0.7", "1.0", "1.4", "2.0"], correctIndex: 2, explanation: "E(X) = 0(0.3) + 2(0.7) = 1.4.", arabicExplanation: "E(X) = 0(0.3) + 2(0.7) = 1.4.", patternSource: "testforgrade12LSandGS-1.pdf · random variables" },
  { id: "bank-g12gs-complex", grade: "Grade 12", branch: "General Sciences", skill: "Complex numbers", prompt: "Find the modulus of z = 3 + 4i.", arabicPrompt: "أوجد معيار العدد المركب z = 3 + 4i.", options: ["3", "4", "5", "7"], correctIndex: 2, explanation: "|z| = √(3² + 4²) = √25 = 5.", arabicExplanation: "|z| = √(3² + 4²) = √25 = 5.", patternSource: "testterm2forgrade12GS.pdf · complex plane" },
  { id: "bank-g12gs-trig", grade: "Grade 12", branch: "General Sciences", skill: "Trigonometry", prompt: "If tan(θ) = 3/4 and θ is acute, find sin(θ).", arabicPrompt: "إذا كان tan(θ) = 3/4 وθ حادة، أوجد sin(θ).", options: ["3/5", "4/5", "3/4", "5/4"], correctIndex: 0, explanation: "Use a 3–4–5 right triangle: opposite = 3, adjacent = 4, hypotenuse = 5, so sin(θ) = 3/5.", arabicExplanation: "نستعمل مثلث 3–4–5: المقابل 3 والمجاور 4 والوتر 5، لذلك sin(θ) = 3/5.", patternSource: "testterm2forgrade12GS.pdf · trigonometry" },
  { id: "bank-g12se-profit", grade: "Grade 12", branch: "Sociology and Economics", skill: "Optimization", prompt: "A profit model is P(x) = −x² + 12x − 20. At which x is profit maximal?", arabicPrompt: "نموذج الربح هو P(x) = −x² + 12x − 20. عند أي قيمة x يكون الربح أعظميًا؟", options: ["x = 4", "x = 6", "x = 8", "x = 12"], correctIndex: 1, explanation: "For ax² + bx + c, the vertex is at x = −b/(2a) = −12/(−2) = 6.", arabicExplanation: "رأس القطع عند x = −b/(2a) = −12/(−2) = 6.", patternSource: "test1forgrade12SE.pdf · optimization and profit" },
  { id: "bank-g12se-regression", grade: "Grade 12", branch: "Sociology and Economics", skill: "Statistics", prompt: "A positive correlation means that, generally, as one variable increases, the other variable…", arabicPrompt: "الارتباط الموجب يعني أنه كلما زاد متغير، فإن المتغير الآخر…", options: ["decreases", "stays constant", "also tends to increase", "becomes zero"], correctIndex: 2, explanation: "Positive correlation describes variables that tend to move in the same direction.", arabicExplanation: "الارتباط الموجب يصف متغيرين يميلان إلى التحرك في الاتجاه نفسه.", patternSource: "test3term2forgrade12SE.pdf · regression" },
  { id: "bank-g12ls-exp-growth", grade: "Grade 12", branch: "Life Sciences", skill: "Exponential modeling", prompt: "A culture starts with 240 cells and triples every 4 hours. Which expression gives the number of cells after t hours?", arabicPrompt: "تبدأ مزرعة بـ240 خلية ويتضاعف عددها ثلاث مرات كل 4 ساعات. أي تعبير يعطي عدد الخلايا بعد t ساعة؟", options: ["240 + 3t", "240(3)^(t/4)", "3(240)^(t/4)", "240(t/3)^4"], correctIndex: 1, explanation: "Each 4-hour interval multiplies the population by 3, so the number of intervals is t/4 and N(t)=240·3^(t/4).", arabicExplanation: "كل فترة من 4 ساعات تضرب العدد في 3، وعدد الفترات هو t/4، لذلك N(t)=240·3^(t/4).", patternSource: "Successful attached LS patterns: exponentials and functions; original values and context" },
  { id: "bank-g12ls-area-integral-correct", grade: "Grade 12", branch: "Life Sciences", skill: "Area from an integral", prompt: "For x in [0, 3], a rate is r(x)=2x+1. What total quantity is accumulated over the interval?", arabicPrompt: "عندما يكون x ضمن [0, 3]، يكون المعدل r(x)=2x+1. ما الكمية الكلية المتراكمة خلال المجال؟", options: ["9", "10", "12", "15"], correctIndex: 2, explanation: "Integrate: ∫₀³(2x+1)dx = [x²+x]₀³ = 9+3 = 12.", arabicExplanation: "نحسب التكامل: ∫₀³(2x+1)dx = [x²+x]₀³ = 9+3 = 12.", patternSource: "Successful attached LS patterns: integrals and area calculation; original rate model" },
  { id: "bank-g12ls-limit-continuity", grade: "Grade 12", branch: "Life Sciences", skill: "Limits", prompt: "Let g(x)=(x²−9)/(x−3) for x≠3. Find lim(x→3) g(x).", arabicPrompt: "لتكن g(x)=(x²−9)/(x−3) عندما x≠3. أوجد النهاية عندما x تقترب من 3.", options: ["0", "3", "6", "9"], correctIndex: 2, explanation: "Factor x²−9=(x−3)(x+3), so g(x)=x+3 for x≠3 and the limit is 6.", arabicExplanation: "نحلل x²−9=(x−3)(x+3)، فتصبح g(x)=x+3 عندما x≠3، والنهاية تساوي 6.", patternSource: "Successful attached LS patterns: limits and functions; original coefficients" },
  { id: "bank-g12ls-derivative-extremum", grade: "Grade 12", branch: "Life Sciences", skill: "Derivative and extrema", prompt: "For h(x)=−x²+6x+2, at which x-value does h reach its maximum?", arabicPrompt: "للدالة h(x)=−x²+6x+2، عند أي قيمة x تبلغ الدالة قيمتها العظمى؟", options: ["x=−3", "x=2", "x=3", "x=6"], correctIndex: 2, explanation: "h′(x)=−2x+6. Setting h′(x)=0 gives x=3, and the negative leading coefficient confirms a maximum.", arabicExplanation: "h′(x)=−2x+6. بجعل المشتقة تساوي صفرًا نحصل على x=3، ومعامل الدرجة الثانية السالب يؤكد أنها قيمة عظمى.", patternSource: "Successful attached LS patterns: derivatives and optimization; original model" },
  { id: "bank-g12ls-probability-complement", grade: "Grade 12", branch: "Life Sciences", skill: "Probability complement", prompt: "The probability that a student completes a practice set is 0.72. What is the probability that the student does not complete it?", arabicPrompt: "احتمال أن يُكمل الطالب مجموعة التدريب هو 0.72. ما احتمال ألا يُكملها؟", options: ["0.18", "0.28", "0.72", "1.72"], correctIndex: 1, explanation: "The complement is 1−0.72=0.28.", arabicExplanation: "الاحتمال المتمم هو 1−0.72=0.28.", patternSource: "Successful attached LS patterns: probability and random variables; original educational context" },
];

export function filterBankQuestions(grade?: BankQuestion["grade"], branch?: BankQuestion["branch"]) {
  return uploadedExamQuestionBank.filter((question) => (!grade || question.grade === grade) && (!branch || question.branch === branch));
}
