"""Academy-original Brevet numbers / word-problems / coordinate banks.

Patterned on Lebanese Grade 9 contest wording (scientific notation, irreducible
fractions, two-offer tariffs, orthonormal plane). Original numbers. Not past papers.
"""

from __future__ import annotations

SOURCE = {
    "kind": "generated-in-official-style",
    "models": ["Grade 9 / Brevet official contests pack"],
    "note": "Academy-original. Patterned on Lebanese Brevet (الشهادة المتوسطة) wording. Not a photocopy of any past paper.",
}


def item(qid, slice_id, difficulty, stem, choices, answer_index, sketch, latex=None, tag=""):
    row = {
        "id": qid,
        "slice": slice_id,
        "difficulty": difficulty,
        "source": {**SOURCE, "tag": tag or slice_id},
        "stem": stem,
        "choices": choices,
        "answerIndex": answer_index,
        "answer": choices[answer_index],
        "solutionSketch": sketch,
    }
    if latex:
        row["latex"] = latex
    return row


NUM_SLICES = [
    {"id": "fraction", "title": "Irreducible fractions", "arabicTitle": "الكسور غير القابلة للاختزال"},
    {"id": "scientific", "title": "Scientific notation", "arabicTitle": "الكتابة العلمية"},
    {"id": "radical", "title": "Radicals", "arabicTitle": "الجذور"},
    {"id": "power", "title": "Powers", "arabicTitle": "القوى"},
]
NUM_RANK = {s["id"]: i for i, s in enumerate(NUM_SLICES)}

NUM = [
    item(
        "brevet-num-frac-01",
        "fraction",
        "easy",
        "Write 18/24 as an irreducible fraction. The result is:",
        ["\\(3/4\\)", "\\(9/12\\)", "\\(6/8\\)", "\\(2/3\\)"],
        0,
        ["Divide numerator and denominator by 6: 18/24 = 3/4.", "Trap: stopping at 9/12, which is not irreducible."],
        latex="18/24",
        tag="irreducible-basic",
    ),
    item(
        "brevet-num-frac-02",
        "fraction",
        "easy",
        "Calculate 2/7 + 3/7. The result is:",
        ["\\(5/14\\)", "\\(5/7\\)", "\\(6/7\\)", "\\(1\\)"],
        1,
        ["Same denominator: (2+3)/7 = 5/7.", "Trap: adding the denominators (5/14)."],
        latex="\\frac{2}{7}+\\frac{3}{7}",
        tag="add-same-denom",
    ),
    item(
        "brevet-num-frac-03",
        "fraction",
        "easy",
        "Calculate (3/5) × (10/9). Write the answer as an irreducible fraction:",
        ["\\(13/14\\)", "\\(30/45\\)", "\\(2/3\\)", "\\(1/3\\)"],
        2,
        ["Cancel 5 and 10, then 3 and 9: 3/5 × 10/9 = 2/3."],
        latex="\\frac{3}{5}\\times\\frac{10}{9}",
        tag="multiply-cancel",
    ),
    item(
        "brevet-num-sci-01",
        "scientific",
        "easy",
        "Write 7200 in the form a × 10^n with 1 ≤ |a| < 10. The result is:",
        ["\\(7.2\\times 10^3\\)", "\\(72\\times 10^2\\)", "\\(7.2\\times 10^2\\)", "\\(0.72\\times 10^4\\)"],
        0,
        ["7200 = 7.2 × 10^3. Trap: 72 × 10² is not in scientific notation because |a| ≥ 10."],
        latex="7200",
        tag="sci-integer",
    ),
    item(
        "brevet-num-sci-02",
        "scientific",
        "easy",
        "Write 0.0081 in the form a × 10^n with 1 ≤ |a| < 10. The result is:",
        ["\\(8.1\\times 10^{-2}\\)", "\\(8.1\\times 10^{-3}\\)", "\\(81\\times 10^{-4}\\)", "\\(0.81\\times 10^{-2}\\)"],
        1,
        ["Move the point three places: 0.0081 = 8.1 × 10^{−3}."],
        latex="0.0081",
        tag="sci-decimal",
    ),
    item(
        "brevet-num-rad-01",
        "radical",
        "easy",
        "√81 equals:",
        ["9", "8", "18", "3"],
        0,
        ["9² = 81, so √81 = 9. Trap: taking half of 81."],
        latex="\\sqrt{81}",
        tag="perfect-square",
    ),
    item(
        "brevet-num-rad-02",
        "radical",
        "easy",
        "Write √20 in the form a√b with a and b positive integers and b square-free. The result is:",
        ["\\(10\\sqrt{2}\\)", "\\(4\\sqrt{5}\\)", "\\(2\\sqrt{5}\\)", "\\(5\\sqrt{2}\\)"],
        2,
        ["√20 = √(4×5) = 2√5."],
        latex="\\sqrt{20}",
        tag="simplify-radical",
    ),
    item(
        "brevet-num-pow-01",
        "power",
        "easy",
        "2^6 equals:",
        ["12", "32", "64", "128"],
        2,
        ["2^6 = 64. Trap: 2^5 = 32 or 6×2 = 12."],
        latex="2^6",
        tag="power-eval",
    ),
    item(
        "brevet-num-pow-02",
        "power",
        "easy",
        "10^4 × 10^{−1} equals:",
        ["\\(10^5\\)", "\\(10^3\\)", "\\(10^{-4}\\)", "\\(1\\)"],
        1,
        ["Add the exponents: 10^{4+(−1)} = 10^3."],
        latex="10^4\\times 10^{-1}",
        tag="power-product",
    ),
    item(
        "brevet-num-frac-04",
        "fraction",
        "medium",
        "Calculate 5/6 − (1/4)×(2/3). The result as an irreducible fraction is:",
        ["\\(2/3\\)", "\\(7/18\\)", "\\(1/2\\)", "\\(5/8\\)"],
        0,
        [
            "Multiplication first: (1/4)×(2/3) = 1/6, then 5/6 − 1/6 = 2/3.",
            "Trap: computing (5/6 − 1/4)×(2/3) = 7/18.",
        ],
        latex="\\frac{5}{6}-\\frac{1}{4}\\times\\frac{2}{3}",
        tag="order-of-ops",
    ),
    item(
        "brevet-num-frac-05",
        "fraction",
        "medium",
        "Calculate 7/8 − 1/6. Write the answer as an irreducible fraction:",
        ["\\(3\\)", "\\(6/14\\)", "\\(17/24\\)", "\\(17/48\\)"],
        2,
        ["Common denominator 24: 21/24 − 4/24 = 17/24.", "Trap: subtracting numerators and denominators separately."],
        latex="\\frac{7}{8}-\\frac{1}{6}",
        tag="subtract-unlike",
    ),
    item(
        "brevet-num-frac-06",
        "fraction",
        "medium",
        "Calculate (8/15)×(25/12) ÷ (10/9) and write the result as an irreducible fraction:",
        ["\\(1\\)", "\\(2\\)", "\\(4/5\\)", "\\(9/10\\)"],
        0,
        [
            "Division: × 9/10. Then 8/15 × 25/12 × 9/10 = 1 after cancelling.",
            "8×25×9 = 1800 and 15×12×10 = 1800.",
        ],
        latex="\\frac{8}{15}\\times\\frac{25}{12}\\div\\frac{10}{9}",
        tag="fraction-chain",
    ),
    item(
        "brevet-num-sci-03",
        "scientific",
        "medium",
        "Write (4.8 × 10^6 × 2.5 × 10^{−2}) / (6 × 10^3) in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(2\\times 10^1\\)", "\\(2\\times 10^2\\)", "\\(1.2\\times 10^2\\)", "\\(2\\times 10^7\\)"],
        0,
        ["(4.8 × 2.5 / 6) × 10^{6−2−3} = 2 × 10^1.", "Trap: forgetting the factor 10^{−2} and writing 2 × 10²."],
        latex="\\frac{4.8\\times 10^6\\times 2.5\\times 10^{-2}}{6\\times 10^3}",
        tag="sci-quotient",
    ),
    item(
        "brevet-num-sci-04",
        "scientific",
        "medium",
        "Write (3.5 × 10^{−4}) × (4 × 10^6) in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(1.4\\times 10^2\\)", "\\(1.4\\times 10^3\\)", "\\(14\\times 10^2\\)", "\\(3.9\\times 10^2\\)"],
        1,
        ["3.5 × 4 = 14 and 10^{−4+6} = 10², so 14 × 10² = 1.4 × 10³.", "Trap: leaving 14 × 10² un-normalized."],
        latex="3.5\\times 10^{-4}\\times 4\\times 10^6",
        tag="sci-product",
    ),
    item(
        "brevet-num-sci-05",
        "scientific",
        "medium",
        "Write (5.6 × 10^{−3}) / (8 × 10^{−5}) in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(7\\times 10^1\\)", "\\(7\\times 10^{-8}\\)", "\\(0.7\\times 10^2\\)", "\\(7\\times 10^2\\)"],
        0,
        ["5.6/8 = 0.7 and 10^{−3−(−5)} = 10², so 0.7 × 10² = 7 × 10¹."],
        latex="\\frac{5.6\\times 10^{-3}}{8\\times 10^{-5}}",
        tag="sci-divide-neg",
    ),
    item(
        "brevet-num-rad-03",
        "radical",
        "medium",
        "Write √50 − √8 in the form a√2. The result is:",
        ["\\(7\\sqrt{2}\\)", "\\(3\\sqrt{2}\\)", "\\(\\sqrt{42}\\)", "\\(3\\sqrt{8}\\)"],
        1,
        ["√50 = 5√2 and √8 = 2√2, so 5√2 − 2√2 = 3√2.", "Trap: adding the coefficients (7√2)."],
        latex="\\sqrt{50}-\\sqrt{8}",
        tag="combine-radicals",
    ),
    item(
        "brevet-num-rad-04",
        "radical",
        "medium",
        "Write √27 + √12 in the form a√3. The result is:",
        ["\\(\\sqrt{39}\\)", "\\(5\\sqrt{6}\\)", "\\(5\\sqrt{3}\\)", "\\(3\\sqrt{3}\\)"],
        2,
        ["√27 = 3√3 and √12 = 2√3, so 3√3 + 2√3 = 5√3.", "Trap: √27 + √12 = √39."],
        latex="\\sqrt{27}+\\sqrt{12}",
        tag="add-radicals",
    ),
    item(
        "brevet-num-rad-05",
        "radical",
        "medium",
        "Rationalize 8/√2. The result is:",
        ["4", "\\(4\\sqrt{2}\\)", "\\(8\\sqrt{2}\\)", "\\(\\sqrt{2}\\)"],
        1,
        ["8/√2 × √2/√2 = 8√2 / 2 = 4√2."],
        latex="\\frac{8}{\\sqrt{2}}",
        tag="rationalize",
    ),
    item(
        "brevet-num-pow-03",
        "power",
        "medium",
        "5^7 / 5^4 equals:",
        ["\\(5^{11}\\)", "5", "25", "125"],
        3,
        ["Subtract exponents: 5^{7−4} = 5^3 = 125.", "Trap: adding the exponents (5^{11})."],
        latex="5^7/5^4",
        tag="power-quotient",
    ),
    item(
        "brevet-num-pow-04",
        "power",
        "medium",
        "3^{10} − 3^8 equals:",
        ["9", "\\(2\\times 3^8\\)", "\\(8\\times 3^8\\)", "\\(3^{10}\\)"],
        2,
        ["Factor 3^8: 3^{10} − 3^8 = 3^8(3² − 1) = 8 × 3^8.", "Trap: writing 3^{10−8} = 9."],
        latex="3^{10}-3^8",
        tag="factor-power-diff",
    ),
    item(
        "brevet-num-pow-05",
        "power",
        "medium",
        "2^{12} / 2^7 equals:",
        ["\\(2^{19}\\)", "32", "64", "14"],
        1,
        ["2^{12−7} = 2^5 = 32."],
        latex="2^{12}/2^7",
        tag="power-divide",
    ),
    item(
        "brevet-num-frac-07",
        "fraction",
        "hard",
        "Calculate 5/6 − (2/3)×(9/4). The result as an irreducible fraction is:",
        ["\\(-2/3\\)", "\\(3/8\\)", "\\(2/3\\)", "\\(1/4\\)"],
        0,
        [
            "(2/3)×(9/4) = 3/2, then 5/6 − 3/2 = 5/6 − 9/6 = −4/6 = −2/3.",
            "Trap: (5/6 − 2/3)×(9/4) = 3/8, or dropping the sign.",
        ],
        latex="\\frac{5}{6}-\\frac{2}{3}\\times\\frac{9}{4}",
        tag="negative-fraction",
    ),
    item(
        "brevet-num-frac-08",
        "fraction",
        "hard",
        "Write (12/35) ÷ (18/49) as an irreducible fraction. The result is:",
        ["\\(2/3\\)", "\\(15/14\\)", "\\(14/15\\)", "\\(2/5\\)"],
        2,
        ["12/35 × 49/18 = (12×7)/(5×18) = 84/90 = 14/15.", "Trap: inverting the first fraction instead of the second."],
        latex="\\frac{12}{35}\\div\\frac{18}{49}",
        tag="divide-fractions",
    ),
    item(
        "brevet-num-sci-06",
        "scientific",
        "hard",
        "Write (6.4 × 10^5 × 5 × 10^{−8}) / (8 × 10^{−2}) in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(4\\times 10^{-1}\\)", "\\(4\\times 10^{-3}\\)", "\\(4\\times 10^{1}\\)", "\\(0.4\\times 10^{-1}\\)"],
        0,
        ["(6.4 × 5 / 8) × 10^{5−8−(−2)} = 4 × 10^{−1}.", "Trap: 5 − 8 − 2 = −5 instead of subtracting a negative exponent."],
        latex="\\frac{6.4\\times 10^5\\times 5\\times 10^{-8}}{8\\times 10^{-2}}",
        tag="sci-nested",
    ),
    item(
        "brevet-num-sci-07",
        "scientific",
        "hard",
        "Given A = (4.8 × 10^4 × 10^{−6}) / (1.6 × 10^2). Write A in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(3\\times 10^{-2}\\)", "\\(3\\times 10^{-4}\\)", "\\(3\\times 10^{0}\\)", "\\(0.3\\times 10^{-3}\\)"],
        1,
        ["4.8/1.6 = 3 and 10^{4−6−2} = 10^{−4}, so A = 3 × 10^{−4}."],
        latex="A=\\frac{4.8\\times 10^4\\times 10^{-6}}{1.6\\times 10^2}",
        tag="sci-A",
    ),
    item(
        "brevet-num-sci-08",
        "scientific",
        "hard",
        "Write (9 × 10^{−2} × 5 × 10^6) / (1.5 × 10^3) in the form a × 10^n with 1 ≤ |a| < 10:",
        ["\\(3\\times 10^1\\)", "\\(30\\times 10^1\\)", "\\(3\\times 10^2\\)", "\\(3\\times 10^7\\)"],
        2,
        ["9 × 5 / 1.5 = 30 and 10^{−2+6−3} = 10^1, so 30 × 10^1 = 3 × 10²."],
        latex="\\frac{9\\times 10^{-2}\\times 5\\times 10^6}{1.5\\times 10^3}",
        tag="sci-normalize",
    ),
    item(
        "brevet-num-rad-06",
        "radical",
        "hard",
        "Write (2 + √5)² in the form a + b√5 where a and b are integers. The result is:",
        ["\\(4+\\sqrt{5}\\)", "\\(9+4\\sqrt{5}\\)", "\\(9+\\sqrt{5}\\)", "\\(4+4\\sqrt{5}\\)"],
        1,
        ["(2+√5)² = 4 + 4√5 + 5 = 9 + 4√5.", "Trap: forgetting 2×2×√5 or dropping 5."],
        latex="(2+\\sqrt{5})^2",
        tag="expand-binomial-radical",
    ),
    item(
        "brevet-num-rad-07",
        "radical",
        "hard",
        "Calculate (√7 − √3)(√7 + √3). The result is:",
        ["10", "\\(\\sqrt{21}\\)", "4", "\\(4\\sqrt{21}\\)"],
        2,
        ["Difference of squares: 7 − 3 = 4.", "Trap: adding 7+3 or writing √21."],
        latex="(\\sqrt{7}-\\sqrt{3})(\\sqrt{7}+\\sqrt{3})",
        tag="diff-squares-radicals",
    ),
    item(
        "brevet-num-rad-08",
        "radical",
        "hard",
        "Write √80 − 2√20 + √5 in the form a√5. The result is:",
        ["\\(9\\sqrt{5}\\)", "\\(5\\sqrt{5}\\)", "0", "\\(\\sqrt{5}\\)"],
        3,
        ["√80 = 4√5 and 2√20 = 4√5, so 4√5 − 4√5 + √5 = √5.", "Trap: adding all three as 9√5."],
        latex="\\sqrt{80}-2\\sqrt{20}+\\sqrt{5}",
        tag="collect-sqrt5",
    ),
    item(
        "brevet-num-pow-06",
        "power",
        "hard",
        "If (x + 1/x)² = 8, then x² + 1/x² equals:",
        ["8", "64", "6", "10"],
        2,
        [
            "(x + 1/x)² = x² + 2 + 1/x² = 8, so x² + 1/x² = 6.",
            "Trap: leaving 8, or adding 2 instead of subtracting (10), or squaring 8.",
        ],
        latex="\\left(x+\\frac{1}{x}\\right)^2=8",
        tag="identity-x-plus-1x",
    ),
    item(
        "brevet-num-pow-07",
        "power",
        "hard",
        "n is a natural number. (2/5)^{n+1} × (5/2)^n equals:",
        ["1", "\\(2/5\\)", "\\(5/2\\)", "\\((2/5)^{2n+1}\\)"],
        1,
        ["(2/5)^{n+1} × (5/2)^n = (2/5) × [(2/5)×(5/2)]^n = 2/5.", "Trap: cancelling everything to 1."],
        latex="\\left(\\frac{2}{5}\\right)^{n+1}\\left(\\frac{5}{2}\\right)^n",
        tag="reciprocal-powers",
    ),
    item(
        "brevet-num-pow-08",
        "power",
        "hard",
        "4^{12} − 4^{10} equals:",
        ["16", "\\(2\\times 4^{10}\\)", "\\(15\\times 4^{10}\\)", "\\(4^{12}\\)"],
        2,
        ["4^{12} − 4^{10} = 4^{10}(4² − 1) = 15 × 4^{10}.", "Trap: 4^{12−10} = 16."],
        latex="4^{12}-4^{10}",
        tag="factor-power-4",
    ),
]

WP_SLICES = [
    {"id": "percent", "title": "Percentages", "arabicTitle": "النسب المئوية"},
    {"id": "two_offers", "title": "Two offers", "arabicTitle": "عرضان"},
    {"id": "mixture", "title": "Bags and mixtures", "arabicTitle": "الأكياس والمزيج"},
    {"id": "system_ctx", "title": "Contextual systems", "arabicTitle": "جمل من مسائل"},
]
WP_RANK = {s["id"]: i for i, s in enumerate(WP_SLICES)}

WP = [
    item(
        "brevet-wp-pct-01",
        "percent",
        "easy",
        "An object costs 480 LL. Its price is increased by 5%. The new price is:",
        ["485 LL", "480.05 LL", "504 LL", "456 LL"],
        2,
        ["New price = 480 × 1.05 = 504 LL.", "Trap: adding 5 LL, or writing 480.05, or decreasing by 5%."],
        tag="price-increase",
    ),
    item(
        "brevet-wp-pct-02",
        "percent",
        "easy",
        "15% of 80 equals:",
        ["15", "8", "20", "12"],
        3,
        ["(15/100)×80 = 12."],
        tag="percent-of",
    ),
    item(
        "brevet-wp-off-01",
        "two_offers",
        "easy",
        "A company charges 30 000 LL plus 500 LL per km. For 20 km traveled, the amount paid is:",
        ["30 020 LL", "10 000 LL", "40 000 LL", "35 000 LL"],
        2,
        ["S = 30 000 + 500×20 = 40 000 LL.", "Trap: adding 20 to the deposit, or omitting the deposit."],
        tag="linear-cost",
    ),
    item(
        "brevet-wp-off-02",
        "two_offers",
        "easy",
        "Offer A is given by S(x) = 40 000 + 800x, where x is the number of km. For x = 10, S(x) equals:",
        ["40 080 LL", "8 000 LL", "40 800 LL", "48 000 LL"],
        3,
        ["40 000 + 800×10 = 48 000 LL."],
        latex="S(10)=40000+800\\times 10",
        tag="evaluate-S",
    ),
    item(
        "brevet-wp-mix-01",
        "mixture",
        "easy",
        "A bag contains 8 red balls and 12 blue balls. The percentage of red balls is:",
        ["8%", "40%", "60%", "66%"],
        1,
        ["8 out of 20 is 40%. Trap: 12/20 = 60% (that is the percentage of blue balls)."],
        tag="two-color-percent",
    ),
    item(
        "brevet-wp-mix-02",
        "mixture",
        "easy",
        "A bag contains 10 balls of which 3 are green. The percentage of green balls is:",
        ["3%", "13%", "30%", "70%"],
        2,
        ["3/10 × 100 = 30%."],
        tag="green-percent",
    ),
    item(
        "brevet-wp-sys-01",
        "system_ctx",
        "easy",
        "Two pens and one notebook cost 5 000 LL. One pen costs 1 500 LL. The notebook costs:",
        ["3 500 LL", "2 000 LL", "1 500 LL", "5 000 LL"],
        1,
        ["2 × 1 500 = 3 000, so the notebook costs 5 000 − 3 000 = 2 000 LL."],
        tag="two-items",
    ),
    item(
        "brevet-wp-sys-02",
        "system_ctx",
        "easy",
        "The sum of two numbers is 20 and their difference is 4. The larger number is:",
        ["16", "12", "8", "24"],
        1,
        ["Add: 2x = 24, so the larger is 12. Check: 12 + 8 = 20 and 12 − 8 = 4.", "Trap: 20 − 4 = 16."],
        tag="sum-diff",
    ),
    item(
        "brevet-wp-pct-03",
        "percent",
        "medium",
        "A bag contains 50 balls: 12 red, 18 blue, and the rest green. The percentage of green balls is:",
        ["36%", "24%", "40%", "20%"],
        2,
        ["Green = 50 − 12 − 18 = 20, so 20/50 × 100 = 40%.", "Trap: 18/50 = 36%."],
        tag="three-color",
    ),
    item(
        "brevet-wp-pct-04",
        "percent",
        "medium",
        "In a class of 200 students, 45 are absent. The percentage of students present is:",
        ["45%", "22.5%", "77.5%", "155%"],
        2,
        ["Present = 155. Then 155/200 × 100 = 77.5%.", "Trap: giving the absence percentage 22.5%."],
        tag="present-percent",
    ),
    item(
        "brevet-wp-pct-05",
        "percent",
        "medium",
        "A price of 800 LL is decreased by 15%. The new price is:",
        ["785 LL", "680 LL", "120 LL", "920 LL"],
        1,
        ["800 × 0.85 = 680 LL. Trap: subtracting 15 LL, or giving only the decrease 120 LL."],
        tag="price-decrease",
    ),
    item(
        "brevet-wp-off-03",
        "two_offers",
        "medium",
        "Offer A: 55 000 LL + 400 LL per km. Offer B: 35 000 LL + 600 LL per km. The two offers cost the same when the traveled distance is:",
        ["20 km", "50 km", "100 km", "200 km"],
        2,
        ["55 000 + 400x = 35 000 + 600x, so 20 000 = 200x, x = 100 km."],
        latex="55000+400x=35000+600x",
        tag="offers-equal",
    ),
    item(
        "brevet-wp-off-04",
        "two_offers",
        "medium",
        "With offer A: 55 000 + 400x and offer B: 35 000 + 600x (x in km), offer A is more advantageous than offer B:",
        [
            "for every distance less than 100 km",
            "only at 100 km",
            "for every distance greater than 100 km",
            "always",
        ],
        2,
        [
            "A < B iff 55 000 + 400x < 35 000 + 600x iff x > 100.",
            "Trap: reversing the inequality.",
        ],
        tag="offers-advantage",
    ),
    item(
        "brevet-wp-off-05",
        "two_offers",
        "medium",
        "A customer selects offer A given by S = 55 000 + 400x and pays 111 000 LL. The traveled distance is:",
        ["111 km", "56 km", "140 km", "400 km"],
        2,
        ["400x = 56 000, so x = 140 km.", "Trap: 56 000/1 000 = 56, or using 111 000 as the number of km."],
        tag="offers-solve-x",
    ),
    item(
        "brevet-wp-mix-03",
        "mixture",
        "medium",
        "A bag contains 80 balls, of which 25% are red. The number of red balls is:",
        ["25", "20", "55", "4"],
        1,
        ["(25/100)×80 = 20."],
        tag="percent-to-count",
    ),
    item(
        "brevet-wp-mix-04",
        "mixture",
        "medium",
        "A bag contains 80 balls: 10 red, 15 yellow, 25% black, and the rest white. The number of white balls is:",
        ["25", "20", "35", "40"],
        2,
        ["Black = 0.25×80 = 20. White = 80 − 10 − 15 − 20 = 35."],
        tag="rest-white",
    ),
    item(
        "brevet-wp-mix-05",
        "mixture",
        "medium",
        "A box contains 16 red and blue balls. If one red ball is removed and one blue ball is added, the number of red balls becomes equal to the number of blue balls. The original number of red balls is:",
        ["8", "7", "9", "10"],
        2,
        [
            "x + y = 16 and x − 1 = y + 1, so x − y = 2.",
            "Hence x = 9 and y = 7. After the change: 8 and 8.",
        ],
        latex="x+y=16,\\ x-y=2",
        tag="equal-after-swap",
    ),
    item(
        "brevet-wp-sys-03",
        "system_ctx",
        "medium",
        "A shop sold 10 cakes: apple cakes at 1 200 LL and lemon cakes at 1 800 LL. The total is 15 000 LL. The number of apple cakes is:",
        ["4", "5", "6", "8"],
        1,
        [
            "x + y = 10 and 1200x + 1800y = 15000, i.e. 2x + 3y = 25.",
            "Replace y = 10 − x: 2x + 30 − 3x = 25, so x = 5.",
        ],
        tag="cakes",
    ),
    item(
        "brevet-wp-sys-04",
        "system_ctx",
        "medium",
        "8 tickets were sold: child tickets at 4 000 LL and adult tickets at 7 000 LL. The total is 44 000 LL. The number of adult tickets is:",
        ["3", "4", "5", "6"],
        1,
        [
            "x + y = 8 and 4000x + 7000y = 44000, i.e. 4x + 7y = 44.",
            "x = 8 − y: 32 + 3y = 44, so y = 4.",
        ],
        tag="tickets",
    ),
    item(
        "brevet-wp-sys-05",
        "system_ctx",
        "medium",
        "The sum of two numbers is 6, and three times the first plus twice the second is 16. The first number is:",
        ["2", "3", "4", "6"],
        2,
        ["x + y = 6 and 3x + 2y = 16. Replace y = 6 − x: 3x + 12 − 2x = 16, so x = 4."],
        tag="two-numbers",
    ),
    item(
        "brevet-wp-pct-06",
        "percent",
        "hard",
        "A bag contains red, black and white balls. 20% are red, 35% are black, and there are 160 balls in all. The number of white balls is:",
        ["55", "72", "88", "45"],
        1,
        ["White = 100% − 20% − 35% = 45%, so 0.45 × 160 = 72.", "Trap: 20%+35%=55 balls, or 0.55×160=88."],
        tag="third-color-count",
    ),
    item(
        "brevet-wp-pct-07",
        "percent",
        "hard",
        "A price of 500 LL is increased by 20%, then decreased by 20% of the new price. The final price is:",
        ["500 LL", "480 LL", "400 LL", "520 LL"],
        1,
        [
            "500 × 1.2 = 600, then 600 × 0.8 = 480 LL.",
            "Trap: thinking +20% and −20% cancel (500), or taking 20% of the original twice.",
        ],
        tag="successive-percent",
    ),
    item(
        "brevet-wp-pct-08",
        "percent",
        "hard",
        "A shop increases a price of 240 LL by 25%, then offers 10% off the new price. The final price is:",
        ["204 LL", "216 LL", "264 LL", "270 LL"],
        3,
        ["240 × 1.25 = 300, then 300 × 0.9 = 270 LL.", "Trap: net 15% of 240 = 204 (applying both percents to the original)."],
        tag="increase-then-discount",
    ),
    item(
        "brevet-wp-off-06",
        "two_offers",
        "hard",
        "Offer A: S1(x) = 70 000 + 800x. Offer B: S2(x) = 40 000 + 1 400x, with x the number of cassettes. S1(x) ≤ S2(x) if and only if:",
        ["\\(x\\le 50\\)", "\\(x\\ge 50\\)", "\\(x\\ge 30\\)", "\\(x=50\\) only"],
        1,
        [
            "70 000 + 800x ≤ 40 000 + 1 400x, so 30 000 ≤ 600x, hence x ≥ 50.",
            "Trap: reversing the inequality when collecting x.",
        ],
        latex="70000+800x\\le 40000+1400x",
        tag="cassettes-inequality",
    ),
    item(
        "brevet-wp-off-07",
        "two_offers",
        "hard",
        "A customer selects offer A given by S1(x) = 70 000 + 800x and pays 118 000 LL. The number of cassettes is:",
        ["118", "48", "80", "60"],
        3,
        ["800x = 48 000, so x = 60.", "Trap: 118 000/1 000 or 48 000/1 000."],
        tag="cassettes-solve",
    ),
    item(
        "brevet-wp-off-08",
        "two_offers",
        "hard",
        "Plan P: 25 000 LL + 150 LL per minute. Plan Q: 10 000 LL + 250 LL per minute. Plan P is cheaper than plan Q when the number t of minutes satisfies:",
        ["\\(t>15\\)", "\\(t<150\\)", "\\(t>150\\)", "\\(t=100\\)"],
        2,
        ["25 000 + 150t < 10 000 + 250t iff 15 000 < 100t iff t > 150.", "Trap: 15 000/1 000 = 15."],
        tag="mobile-plans",
    ),
    item(
        "brevet-wp-mix-06",
        "mixture",
        "hard",
        "A box contains 18 red and black balls. If 2 red balls are removed and 2 black balls are added, the number of red balls becomes equal to the number of black balls. The original number of red balls is:",
        ["9", "7", "11", "13"],
        2,
        [
            "x + y = 18 and x − 2 = y + 2, so x − y = 4. Hence x = 11 and y = 7.",
            "Trap: answering 9 (the common number after the change).",
        ],
        latex="x+y=18,\\ x-y=4",
        tag="equal-after-two",
    ),
    item(
        "brevet-wp-mix-07",
        "mixture",
        "hard",
        "A box contains 8 red balls and 4 black balls. Four red balls and four black balls are added. The percentage of red balls in the box is then:",
        ["40%", "50%", "60%", "67%"],
        2,
        ["Red = 12, black = 8, total = 20, so 12/20 = 60%.", "Trap: 8/12 ≈ 67% using the original ratio, or 50% because equal numbers were added."],
        tag="add-then-percent",
    ),
    item(
        "brevet-wp-mix-08",
        "mixture",
        "hard",
        "A bag originally contains 12 red balls among 30 balls. Balls are added until there are 50 balls of which 40% are red. The number of red balls added is:",
        ["20", "12", "8", "10"],
        2,
        ["Final red = 0.40 × 50 = 20. Red added = 20 − 12 = 8.", "Trap: giving the final number of red balls (20)."],
        tag="red-added",
    ),
    item(
        "brevet-wp-sys-06",
        "system_ctx",
        "hard",
        "A farm has goats (4 legs) and chickens (2 legs): 30 heads and 80 legs in all. The number of chickens is:",
        ["10", "15", "20", "25"],
        2,
        [
            "g + c = 30 and 4g + 2c = 80, so 2g + c = 40.",
            "Subtract: g = 10, hence c = 20. Trap: answering the number of goats.",
        ],
        tag="heads-legs",
    ),
    item(
        "brevet-wp-sys-07",
        "system_ctx",
        "hard",
        "3 kg of type A and 2 kg of type B cost 14 000 LL. 1 kg of A and 4 kg of B cost 13 000 LL. The price of 1 kg of type A is:",
        ["2 500 LL", "4 000 LL", "2 000 LL", "3 000 LL"],
        3,
        [
            "3a + 2b = 14000 and a + 4b = 13000.",
            "3a + 12b = 39000, subtract: 10b = 25000, b = 2500, then a = 3000.",
        ],
        tag="two-types",
    ),
    item(
        "brevet-wp-sys-08",
        "system_ctx",
        "hard",
        "40 students go on a trip: some pay 15 000 LL and the others pay 9 000 LL. The total is 516 000 LL. The number of students who pay 9 000 LL is:",
        ["26", "12", "16", "14"],
        3,
        [
            "x + y = 40 and 15000x + 9000y = 516000, i.e. 5x + 3y = 172.",
            "y = 40 − x: 5x + 120 − 3x = 172, so 2x = 52, x = 26 (full price) and y = 14.",
            "Trap: answering the 26 who pay the full price.",
        ],
        tag="trip-discount",
    ),
]

COORD_SLICES = [
    {"id": "point_line", "title": "Point and line", "arabicTitle": "نقطة ومستقيم"},
    {"id": "slope_eq", "title": "Slope and equation", "arabicTitle": "الميل والمعادلة"},
    {"id": "parallel_perp", "title": "Parallel and perpendicular", "arabicTitle": "التوازي والتعامد"},
    {"id": "midpoint_pb", "title": "Midpoint and perpendicular bisector", "arabicTitle": "المنتصف والمنصف العمودي"},
]
COORD_RANK = {s["id"]: i for i, s in enumerate(COORD_SLICES)}

COORD = [
    item(
        "brevet-co-pt-01",
        "point_line",
        "easy",
        "In an orthonormal system, the point A(2 ; 3) and the line (d): y = x + 1. Then:",
        [
            "A belongs to (d)",
            "A does not belong to (d)",
            "(d) is vertical",
            "A is the origin",
        ],
        0,
        ["The coordinates of A verify the equation: 3 = 2 + 1, so A belongs to (d)."],
        latex="y=x+1",
        tag="point-on-line",
    ),
    item(
        "brevet-co-pt-02",
        "point_line",
        "easy",
        "The y-intercept of the line y = 3x − 5 is the point:",
        ["(0 ; 3)", "(−5 ; 0)", "(3 ; −5)", "(0 ; −5)"],
        3,
        ["Set x = 0: y = −5, so the y-intercept is (0 ; −5).", "Trap: ( −5 ; 0 ), the x-intercept."],
        latex="y=3x-5",
        tag="y-intercept",
    ),
    item(
        "brevet-co-pt-03",
        "point_line",
        "easy",
        "Which of the following points belongs to the line y = −2x + 4?",
        ["(0 ; 4)", "(0 ; −2)", "(4 ; 0)", "(2 ; 4)"],
        0,
        ["For (0 ; 4): y = 4. For (4 ; 0): 0 = −8 + 4 is false. Trap: mixing intercepts."],
        tag="which-point",
    ),
    item(
        "brevet-co-sl-01",
        "slope_eq",
        "easy",
        "The slope of the line passing through A(1 ; 2) and B(3 ; 6) is:",
        ["\\(1/2\\)", "2", "4", "3"],
        1,
        ["a(AB) = (6 − 2)/(3 − 1) = 4/2 = 2.", "Trap: inverting the ratio (1/2)."],
        latex="a=\\frac{y_B-y_A}{x_B-x_A}",
        tag="slope-two-points",
    ),
    item(
        "brevet-co-sl-02",
        "slope_eq",
        "easy",
        "The line y = −3x + 1 has slope:",
        ["1", "3", "\\(-1/3\\)", "−3"],
        3,
        ["In y = ax + b the slope is a = −3.", "Trap: taking the opposite of the reciprocal as if asking for a perpendicular."],
        latex="y=-3x+1",
        tag="read-slope",
    ),
    item(
        "brevet-co-pp-01",
        "parallel_perp",
        "easy",
        "In an orthonormal system, the lines (D1): y = 2x + 1 and (D2): y = 2x − 5 are:",
        ["perpendicular", "parallel", "intersecting at the origin", "coincident"],
        1,
        ["Same slope 2, different intercepts: the lines are parallel and distinct."],
        tag="parallel-same-slope",
    ),
    item(
        "brevet-co-pp-02",
        "parallel_perp",
        "easy",
        "In an orthonormal system, two non-vertical perpendicular lines have slopes a and a′ satisfying:",
        ["\\(a\\times a'=1\\)", "\\(a\\times a'=-1\\)", "\\(a=a'\\)", "\\(a+a'=0\\)"],
        1,
        ["The product of the slopes of two perpendicular lines is −1."],
        latex="a\\times a'",
        tag="perp-product",
    ),
    item(
        "brevet-co-md-01",
        "midpoint_pb",
        "easy",
        "I is the midpoint of [AB] with A(2 ; 4) and B(6 ; 8). Then I is:",
        ["(8 ; 12)", "(4 ; 6)", "(2 ; 4)", "(4 ; 4)"],
        1,
        ["I = ((2+6)/2 ; (4+8)/2) = (4 ; 6).", "Trap: adding the coordinates without dividing by 2."],
        latex="I=\\left(\\frac{x_A+x_B}{2};\\frac{y_A+y_B}{2}\\right)",
        tag="midpoint",
    ),
    item(
        "brevet-co-md-02",
        "midpoint_pb",
        "easy",
        "The midpoint of [AB] with A(0 ; 0) and B(6 ; −2) is:",
        ["(6 ; −2)", "(3 ; −2)", "(−3 ; 1)", "(3 ; −1)"],
        3,
        ["I = (3 ; −1)."],
        tag="midpoint-origin",
    ),
    item(
        "brevet-co-pt-04",
        "point_line",
        "medium",
        "The point A(1 ; −1) and the line (d): y = 2x − 3. Then:",
        ["A belongs to (d)", "A is the y-intercept of (d)", "(d) is vertical", "A is the origin"],
        0,
        ["2(1) − 3 = −1, so the coordinates of A verify the equation of (d)."],
        latex="y=2x-3",
        tag="verify-A",
    ),
    item(
        "brevet-co-pt-05",
        "point_line",
        "medium",
        "Which of the following points belongs to (d): y = −x + 5?",
        ["(2 ; 7)", "(2 ; 3)", "(5 ; 5)", "(0 ; 0)"],
        1,
        ["For (2 ; 3): −2 + 5 = 3. For (2 ; 7): −2 + 5 ≠ 7 (that would be y = x + 5)."],
        tag="which-on-d",
    ),
    item(
        "brevet-co-pt-06",
        "point_line",
        "medium",
        "The line (d) has equation 2x + 3y − 12 = 0. The point C(3 ; 2):",
        ["does not belong to (d)", "belongs to (d)", "is the origin", "makes (d) vertical"],
        1,
        ["2×3 + 3×2 − 12 = 0, so C belongs to (d)."],
        latex="2x+3y-12=0",
        tag="implicit-verify",
    ),
    item(
        "brevet-co-sl-03",
        "slope_eq",
        "medium",
        "A(0 ; 2) and B(8 ; 6). An equation of the line (AB) is:",
        ["\\(y=2x+2\\)", "\\(y=\\frac{1}{2}x\\)", "\\(y=4x+2\\)", "\\(y=\\frac{1}{2}x+2\\)"],
        3,
        ["a(AB) = (6−2)/(8−0) = 1/2. Through (0 ; 2): y = (1/2)x + 2."],
        latex="A(0;2),\\ B(8;6)",
        tag="equation-AB",
    ),
    item(
        "brevet-co-sl-04",
        "slope_eq",
        "medium",
        "The slope of the line through C(2 ; −1) and D(6 ; 7) is:",
        ["\\(1/2\\)", "8", "−2", "2"],
        3,
        ["a(CD) = (7 − (−1))/(6 − 2) = 8/4 = 2."],
        tag="slope-CD",
    ),
    item(
        "brevet-co-sl-05",
        "slope_eq",
        "medium",
        "The line passing through A(1 ; 4) with slope −1 has equation:",
        ["\\(y=-x+4\\)", "\\(y=x+5\\)", "\\(y=-x+5\\)", "\\(y=-x+3\\)"],
        2,
        ["y − 4 = −1(x − 1), so y = −x + 5."],
        latex="y-4=-(x-1)",
        tag="point-slope",
    ),
    item(
        "brevet-co-pp-03",
        "parallel_perp",
        "medium",
        "In an orthonormal system, (D1): y = 3x − 4 and (D2): y = −(1/3)x + 2 are:",
        ["parallel", "coincident", "perpendicular", "vertical"],
        2,
        ["3 × (−1/3) = −1, so the lines are perpendicular."],
        tag="perp-slopes",
    ),
    item(
        "brevet-co-pp-04",
        "parallel_perp",
        "medium",
        "In an orthonormal system, (D1): y = 4x − 1 and (D2): y = −x/4 + 3 are:",
        ["parallel", "perpendicular", "coincident", "horizontal"],
        1,
        ["4 × (−1/4) = −1, so (D1) ⊥ (D2)."],
        tag="perp-4",
    ),
    item(
        "brevet-co-pp-05",
        "parallel_perp",
        "medium",
        "In an orthonormal system, (d): y = −3x + 4 and (AE): y = (1/3)x − 1. Then:",
        ["(d) // (AE)", "(d) ⊥ (AE)", "(d) and (AE) coincide", "(d) is vertical"],
        1,
        ["−3 × (1/3) = −1, so (d) ⊥ (AE)."],
        tag="d-perp-AE",
    ),
    item(
        "brevet-co-md-03",
        "midpoint_pb",
        "medium",
        "A(1 ; 3) and B(5 ; 7). An equation of the perpendicular bisector of [AB] is:",
        ["\\(y=x+2\\)", "\\(y=-x+5\\)", "\\(y=-x+8\\)", "\\(y=-x+3\\)"],
        2,
        [
            "Midpoint I(3 ; 5). Slope of AB is 1, so the perpendicular slope is −1.",
            "Through I: y − 5 = −(x − 3), hence y = −x + 8.",
            "Trap: the line (AB) itself, y = x + 2.",
        ],
        latex="A(1;3),\\ B(5;7)",
        tag="perp-bisector-eq",
    ),
    item(
        "brevet-co-md-04",
        "midpoint_pb",
        "medium",
        "A(0 ; 2) and B(4 ; 2). The perpendicular bisector of [AB] has equation:",
        ["\\(y=2\\)", "\\(x=4\\)", "\\(y=x\\)", "\\(x=2\\)"],
        3,
        ["[AB] is horizontal; its midpoint is (2 ; 2); the perpendicular bisector is the vertical line x = 2."],
        tag="vertical-pb",
    ),
    item(
        "brevet-co-md-05",
        "midpoint_pb",
        "medium",
        "I is the midpoint of [AB] with A(−1 ; 4) and B(5 ; −2). Then I is:",
        ["(4 ; 2)", "(2 ; 3)", "(3 ; 1)", "(2 ; 1)"],
        3,
        ["I = ((−1+5)/2 ; (4+(−2))/2) = (2 ; 1)."],
        tag="midpoint-signed",
    ),
    item(
        "brevet-co-md-06",
        "midpoint_pb",
        "medium",
        "In an orthonormal system, A(1 ; −2) and B(4 ; 2). The length AB equals:",
        ["5", "7", "\\(\\sqrt{7}\\)", "25"],
        0,
        ["AB² = (4−1)² + (2−(−2))² = 9 + 16 = 25, so AB = 5.", "Trap: adding 3+4 or leaving 25."],
        latex="AB=\\sqrt{3^2+4^2}",
        tag="distance",
    ),
    item(
        "brevet-co-pt-07",
        "point_line",
        "hard",
        "The line (D): y = (1/2)x − 2. Then the point E(6 ; 1):",
        ["belongs to (D)", "does not belong to (D)", "is the origin", "makes (D) vertical"],
        0,
        ["(1/2)×6 − 2 = 1, so E belongs to (D). Two points determine a line: A(0 ; −2) also belongs to (D)."],
        latex="y=\\frac{1}{2}x-2",
        tag="E-on-D",
    ),
    item(
        "brevet-co-pt-08",
        "point_line",
        "hard",
        "The line (d): 3x − y + 1 = 0. The point P(1 ; 4):",
        ["belongs to (d)", "does not belong to (d)", "is the x-intercept of (d)", "makes (d) horizontal"],
        0,
        ["3(1) − 4 + 1 = 0, so P belongs to (d)."],
        latex="3x-y+1=0",
        tag="P-on-d",
    ),
    item(
        "brevet-co-sl-06",
        "slope_eq",
        "hard",
        "A(−2 ; 1) and B(4 ; −2). An equation of the line (AB) is:",
        ["\\(y=-\\frac{1}{2}x+1\\)", "\\(y=-2x\\)", "\\(y=\\frac{1}{2}x\\)", "\\(y=-\\frac{1}{2}x\\)"],
        3,
        [
            "a(AB) = (−2 − 1)/(4 − (−2)) = −3/6 = −1/2.",
            "y − 1 = −(1/2)(x + 2) = −x/2 − 1, so y = −(1/2)x.",
        ],
        latex="A(-2;1),\\ B(4;-2)",
        tag="equation-through-origin",
    ),
    item(
        "brevet-co-sl-07",
        "slope_eq",
        "hard",
        "Write 2x − 4y + 8 = 0 in the form y = ax + b. The result is:",
        ["\\(y=2x+8\\)", "\\(y=\\frac{1}{2}x-2\\)", "\\(y=-2x+2\\)", "\\(y=\\frac{1}{2}x+2\\)"],
        3,
        ["−4y = −2x − 8, so y = (1/2)x + 2."],
        latex="2x-4y+8=0",
        tag="to-slope-intercept",
    ),
    item(
        "brevet-co-sl-08",
        "slope_eq",
        "hard",
        "In an orthonormal system, the line y = 2x + 1 makes with the positive x-axis an angle α. Rounded to the nearest degree, α is nearest to:",
        ["\\(27^\\circ\\)", "\\(45^\\circ\\)", "\\(63^\\circ\\)", "\\(117^\\circ\\)"],
        2,
        ["tan α = 2, and tan 63° ≈ 1.96, tan 45° = 1. So α ≈ 63°.", "Trap: 27° (that is tan^{−1}(1/2))."],
        latex="\\tan\\alpha=2",
        tag="angle-slope",
    ),
    item(
        "brevet-co-pp-06",
        "parallel_perp",
        "hard",
        "A slope of a line perpendicular to y = (2/5)x + 1 is:",
        ["\\(5/2\\)", "\\(-2/5\\)", "\\(2/5\\)", "\\(-5/2\\)"],
        3,
        ["The perpendicular slope is the opposite of the reciprocal: −5/2.", "Trap: +5/2 or −2/5."],
        tag="perp-slope-only",
    ),
    item(
        "brevet-co-pp-07",
        "parallel_perp",
        "hard",
        "The line through A(1 ; 2) perpendicular to y = (1/3)x has equation:",
        ["\\(y=3x-1\\)", "\\(y=-3x-1\\)", "\\(y=\\frac{1}{3}x+2\\)", "\\(y=-3x+5\\)"],
        3,
        ["Perpendicular slope −3. Then y − 2 = −3(x − 1), so y = −3x + 5."],
        latex="A(1;2),\\ y=\\frac{1}{3}x",
        tag="perp-through-A",
    ),
    item(
        "brevet-co-pp-08",
        "parallel_perp",
        "hard",
        "In an orthonormal system, (D1): y = (1 − √5)x − 2 and (D2): y = (1 + √5)x + 2 are:",
        ["parallel", "perpendicular", "intersecting, neither parallel nor perpendicular", "coincident"],
        2,
        [
            "The slopes 1−√5 and 1+√5 are different, so the lines are not parallel.",
            "Product: (1−√5)(1+√5) = 1 − 5 = −4 ≠ −1, so they are not perpendicular.",
        ],
        tag="neither-par-perp",
    ),
    item(
        "brevet-co-md-07",
        "midpoint_pb",
        "hard",
        "A(0 ; 1) and B(4 ; 3). An equation of the perpendicular bisector of [AB] is:",
        ["\\(y=\\frac{1}{2}x+1\\)", "\\(y=-2x+2\\)", "\\(y=-2x+4\\)", "\\(y=-2x+6\\)"],
        3,
        [
            "I(2 ; 2). Slope of AB is 1/2, so the perpendicular slope is −2.",
            "y − 2 = −2(x − 2), hence y = −2x + 6.",
        ],
        latex="A(0;1),\\ B(4;3)",
        tag="pb-hard",
    ),
    item(
        "brevet-co-md-08",
        "midpoint_pb",
        "hard",
        "ABCD is a parallelogram with A(1 ; 0), B(5 ; 1) and C(4 ; 4). Then D equals:",
        ["(8 ; 5)", "(4 ; 3)", "(5 ; 4)", "(0 ; 3)"],
        3,
        [
            "Vector AD = vector BC, so D = A + (C − B) = (1+4−5 ; 0+4−1) = (0 ; 3).",
            "Trap: (8 ; 5) = B + C − A, the fourth vertex of a different parallelogram on the same three points.",
        ],
        tag="parallelogram-vertex",
    ),
    item(
        "brevet-co-md-09",
        "midpoint_pb",
        "hard",
        "In an orthonormal system, the lines y = 2x − 1 and y = −x + 5 intersect at:",
        ["(0 ; −1)", "(5 ; 0)", "(2 ; 1)", "(2 ; 3)"],
        3,
        ["2x − 1 = −x + 5, so 3x = 6, x = 2 and y = 3. Intersection (2 ; 3)."],
        latex="2x-1=-x+5",
        tag="intersection",
    ),
]


def _assert_bank(name, questions, slices, min_n=30):
    ids = [q["id"] for q in questions]
    assert len(ids) == len(set(ids)), name
    assert len(questions) >= min_n, (name, len(questions))
    bands = {"easy": 0, "medium": 0, "hard": 0}
    slice_ids = {s["id"] for s in slices}
    for q in questions:
        assert q["slice"] in slice_ids, q["id"]
        assert 0 <= q["answerIndex"] < len(q["choices"]), q["id"]
        assert q["choices"][q["answerIndex"]] == q["answer"], q["id"]
        bands[q["difficulty"]] += 1
    assert bands["easy"] >= 5 and bands["medium"] >= 7 and bands["hard"] >= 4, (name, bands)
    return bands


if __name__ == "__main__":
    for label, qs, sl in (("numbers", NUM, NUM_SLICES), ("word_problems", WP, WP_SLICES), ("coordinate", COORD, COORD_SLICES)):
        print(label, len(qs), _assert_bank(label, qs, sl))
