#!/usr/bin/env python3
"""
Build the embedded PDF fonts for the branded WhatsApp PDFs (src/lib/pdf/fonts/*.ts).

- Noto Naskh Arabic (SIL OFL 1.1): instanced to a static weight, subset to the Arabic block +
  Arabic Presentation Forms A/B (the runtime shaper maps letters to presentation forms).
- DejaVu Sans (Bitstream Vera / DejaVu licence): Latin, Greek, superscripts, arrows and maths.

Layout tables and hinting are dropped (the runtime does its own shaping); the result is stored
as base64 so the font ships inside the server bundle (no runtime file access).

Usage: python3 scripts/build-pdf-fonts.py  (needs fontTools; source fonts from the system font dir)
"""
import base64
import io
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

NASKH = os.environ.get("NASKH_TTF", "/usr/share/fonts/truetype/sand-box/google/Noto Naskh Arabic/NotoNaskhArabic-VariableFont_wght.ttf")
DEJAVU = os.environ.get("DEJAVU_TTF", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
DEJAVU_BOLD = os.environ.get("DEJAVU_BOLD_TTF", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "pdf", "fonts")

ARABIC = list(range(0x0600, 0x0700)) + list(range(0xFB50, 0xFE00)) + list(range(0xFE70, 0xFF00)) + [0x20, 0xA0, 0xAB, 0xBB, 0x2E, 0x3A, 0x28, 0x29]
LATIN = (
    list(range(0x20, 0x7F)) + list(range(0xA0, 0x180)) + list(range(0x370, 0x400)) + list(range(0x2000, 0x2070))
    + list(range(0x2070, 0x20A0)) + list(range(0x2100, 0x2150)) + list(range(0x2190, 0x2200)) + list(range(0x2200, 0x2300))
    + list(range(0x25A0, 0x2600)) + [0x2713, 0x2714, 0x2717, 0x2718, 0x221A]
)


def subset_font(font: TTFont, unicodes: list[int]) -> bytes:
    options = subset.Options()
    options.layout_features = []
    options.hinting = False
    options.drop_tables += ["GSUB", "GPOS", "GDEF", "kern", "MATH", "FFTM", "STAT", "HVAR", "gvar", "fvar", "avar"]
    options.name_IDs = [1, 2, 4, 6]
    options.notdef_outline = True
    sub = subset.Subsetter(options)
    sub.populate(unicodes=unicodes)
    sub.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def write_module(name: str, export: str, data: bytes, source: str, licence: str) -> None:
    b64 = base64.b64encode(data).decode("ascii")
    chunks = [b64[i : i + 120] for i in range(0, len(b64), 120)]
    body = "\n".join(f'  "{c}",' for c in chunks)
    path = os.path.join(OUT, f"{name}.ts")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(
            "/* eslint-disable */\n"
            f"/** Generated by scripts/build-pdf-fonts.py — do not edit. {source}. Licence: {licence}. */\n"
            f"export const {export}: string = [\n{body}\n].join(\"\");\n"
        )
    print(f"{path}: {len(data)} bytes font, {len(b64)} chars base64")


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    for weight, suffix in ((400, "Regular"), (700, "Bold")):
        var = TTFont(NASKH)
        static = instancer.instantiateVariableFont(var, {"wght": weight})
        data = subset_font(static, ARABIC)
        write_module(f"notoNaskhArabic{suffix}", f"NOTO_NASKH_ARABIC_{suffix.upper()}_BASE64", data, f"Noto Naskh Arabic {suffix} (subset)", "SIL Open Font License 1.1")
    for path, suffix in ((DEJAVU, "Regular"), (DEJAVU_BOLD, "Bold")):
        data = subset_font(TTFont(path), LATIN)
        write_module(f"dejaVuSans{suffix}", f"DEJAVU_SANS_{suffix.upper()}_BASE64", data, f"DejaVu Sans {suffix} (subset)", "Bitstream Vera / DejaVu Fonts licence (free redistribution)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
