"""Grade 12 SE banks: functions (econ), probability, mixed MCQ."""

from __future__ import annotations

from g12_bank_common import SE_MODELS, SE_TOPICS, item, make_bank

M = SE_MODELS


ERRORS: list[str] = []


def Q(qid, slice_id, difficulty, stem, choices, answer_index, sketch, latex=None, tag=""):
    try:
        return item(qid, slice_id, difficulty, stem, choices, answer_index, sketch, M, latex, tag)
    except Exception as exc:
        ERRORS.append(f"{qid}: {exc}")
        return None


FN_SLICES = [
    {"id": "limits", "title": "Limits and asymptotes", "arabicTitle": "النهايات والتقارب"},
    {"id": "variation", "title": "Derivatives and variations", "arabicTitle": "المشتقات وجدول التغيرات"},
    {"id": "cost_profit", "title": "Cost, revenue, profit", "arabicTitle": "الكلفة والإيراد والربح"},
    {"id": "demand", "title": "Demand and elasticity", "arabicTitle": "الطلب والمرونة"},
    {"id": "integral", "title": "Area and primitives", "arabicTitle": "المساحة والأصول"},
    {"id": "root", "title": "Unique root sandwich", "arabicTitle": "حصار الجذر الوحيد"},
]

SE_FN = [
    Q("g12-se-fn-lm-01", "limits", "easy",
      "Let f be defined on [0; +∞[ by f(x)=1−(x−2)e^{−x}. Then lim_{x→+∞} f(x) equals:",
      ["\\(1\\)", "\\(0\\)", "\\(+\\infty\\)", "\\(-1\\)"], 0,
      ["(x−2)e^{−x} → 0, so f(x) → 1. The line y=1 is a horizontal asymptote of (G)."],
      latex="f(x)=1-(x-2)e^{-x}", tag="horiz-asymp-1"),
    Q("g12-se-fn-lm-02", "limits", "easy",
      "If lim_{x→+∞} f(x)=1, the line (d) of equation y=1 represents, for the curve (G) of f:",
      ["a horizontal asymptote", "a vertical asymptote", "a tangent at the origin", "an axis of symmetry"], 0,
      ["A finite non-zero (or zero) limit at +∞ gives a horizontal asymptote y=L."], tag="d-is-asymptote"),
    Q("g12-se-fn-vr-01", "variation", "easy",
      "Let f(x)=1−(x−2)e^{−x}. Given f'(x)=(x−3)e^{−x}, then f'(x)=0 at:",
      ["\\(x=3\\)", "\\(x=2\\)", "\\(x=0\\)", "\\(x=1\\)"], 0,
      ["e^{−x}>0 for all x, so f'(x)=0 iff x=3."], tag="critical-3"),
    Q("g12-se-fn-cp-01", "cost_profit", "easy",
      "The total cost CT is a primitive of the marginal cost MC satisfying CT(0)=fixed cost. If MC(x)=1−(x−2)e^{−x} and the fixed cost is 1 (million LL), then CT(0) equals:",
      ["\\(1\\)", "\\(0\\)", "\\(2\\)", "MC(0)"], 0,
      ["By definition the fixed cost is CT(0)."], tag="fixed-cost"),
    Q("g12-se-fn-dm-01", "demand", "easy",
      "A demand f(p)=4/(1+ln p) is expressed in thousands of units, p in thousands LL. For a unit price of 1000 LL one has p=1, hence the demanded quantity is:",
      ["4000 units", "4 units", "1000 units", "1 unit"], 0,
      ["f(1)=4/(1+0)=4, so 4000 units."], tag="demand-at-1000"),
    Q("g12-se-fn-in-01", "integral", "easy",
      "An antiderivative of e^{−x} on IR is:",
      ["\\(-e^{-x}\\)", "\\(e^{-x}\\)", "\\(-xe^{-x}\\)", "\\(e^{x}\\)"], 0,
      ["(−e^{−x})'=e^{−x}."], tag="antideriv-exp"),
    Q("g12-se-fn-rt-01", "root", "easy",
      "If P is continuous and strictly increasing on [2.13; 2.14] with P(2.13)<0<P(2.14), then the equation P(x)=0 has:",
      ["a unique root α in ]2.13; 2.14[", "no root", "two roots", "a root at 0"], 0,
      ["IVT plus strict increase ⇒ unique sandwich."], tag="sandwich-easy"),
    Q("g12-se-fn-lm-03", "limits", "easy",
      "Let f(x)=4/(1+ln x) on ]1/e; +∞[. Then lim_{x→+∞} f(x) equals:",
      ["\\(0\\)", "\\(4\\)", "\\(+\\infty\\)", "\\(1\\)"], 0,
      ["ln x → +∞ so f(x)→0: y=0 is a horizontal asymptote."], tag="demand-limit-inf"),
    Q("g12-se-fn-vr-02", "variation", "easy",
      "If f'(x)=(x−3)e^{−x}, then on [0; 3] the function f is:",
      ["decreasing", "increasing", "constant", "convex only"], 0,
      ["On [0;3], (x−3)≤0 and e^{−x}>0, so f'≤0."], tag="decreasing-on-0-3"),
    Q("g12-se-fn-cp-02", "cost_profit", "easy",
      "Pens are sold at 20 000 LL each and x is the number of hundreds of pens. The daily revenue, in millions LL, is:",
      ["\\(R(x)=2x\\)", "\\(R(x)=20x\\)", "\\(R(x)=0.02x\\)", "\\(R(x)=x\\)"], 0,
      ["100×20 000 LL = 2 million LL per hundred, so R(x)=2x."], tag="revenue-2x"),
    Q("g12-se-fn-dm-02", "demand", "easy",
      "The elasticity of a demand f is E(p)= −p f'(p)/f(p). If E(3)=0.47 < 1, then at p=3 the demand is:",
      ["inelastic", "elastic", "perfectly elastic", "undefined"], 0,
      ["|E|<1 ⇒ inelastic. An increase of 1% in the price decreases demand by about 0.47%."], tag="inelastic-E3"),
    Q("g12-se-fn-in-02", "integral", "easy",
      "The maintenance rate of a machine is f(t)=e^{0.5 t} (millions LL per year). The maintenance cost during [0; 2] equals:",
      ["\\(2(e-1)\\)", "\\(e^{0.5}\\)", "\\(e\\)", "\\(2e\\)"], 0,
      ["∫_0^2 e^{0.5 t} dt = 2 e^{0.5 t}|_0^2 = 2(e−1)."], latex="\\int_0^2 e^{0.5 t}\\,dt", tag="maintenance-2y"),
    Q("g12-se-fn-lm-04", "limits", "medium",
      "Let f(x)=4/(1+ln x) on ]1/e; +∞[. Then lim_{x→(1/e)+} f(x) equals:",
      ["\\(+\\infty\\)", "\\(0\\)", "\\(4\\)", "\\(-\\infty\\)"], 0,
      ["ln x → −1+, so 1+ln x → 0+, hence f → +∞. The line x=1/e is a vertical asymptote."], tag="vert-asymp-1e"),
    Q("g12-se-fn-vr-03", "variation", "medium",
      "Given f'(x)=(x−3)e^{−x}, the table of variations of f on [0; +∞[ has a minimum at:",
      ["\\(x=3\\)", "\\(x=0\\)", "\\(x=2\\)", "no extremum"], 0,
      ["f' changes − to + at x=3: local minimum."], tag="min-at-3"),
    Q("g12-se-fn-vr-04", "variation", "medium",
      "The tangent to (G) of f(x)=1−(x−2)e^{−x} at the point of abscissa 0 has equation:",
      ["\\(y=-3x+3\\)", "\\(y=3x+3\\)", "\\(y=-3x\\)", "\\(y=x+1\\)"], 0,
      ["f(0)=1−(−2)·1=3, f'(0)=(−3)·1=−3, so y−3=−3x ⇒ y=−3x+3."], tag="tangent-at-0"),
    Q("g12-se-fn-cp-03", "cost_profit", "medium",
      "If CT(x)=x+2+(x−1)e^{−x} and R(x)=2x, the profit P=R−CT is:",
      ["\\(P(x)=x-2-(x-1)e^{-x}\\)", "\\(P(x)=3x+2+(x-1)e^{-x}\\)", "\\(P(x)=x+2\\)", "\\(P(x)=2x\\)"], 0,
      ["P(x)=2x−[x+2+(x−1)e^{−x}]=x−2−(x−1)e^{−x}."], tag="profit-formula"),
    Q("g12-se-fn-cp-04", "cost_profit", "medium",
      "A factory has MC(x)=1+2(1−x)e^{−x} and fixed cost 2. Then the total cost is:",
      ["\\(C(x)=x+2+2xe^{-x}\\)", "\\(C(x)=x+2\\)", "\\(C(x)=2xe^{-x}\\)", "\\(C(x)=MC(x)+2\\)"], 0,
      ["C'(x)=1+2(1−x)e^{−x}=MC(x) and C(0)=2."], tag="primitive-cost"),
    Q("g12-se-fn-dm-03", "demand", "medium",
      "If f(p)=4/(1+ln p), then E(p)= −p f'(p)/f(p) simplifies to:",
      ["\\(\\dfrac{1}{1+\\ln p}\\)", "\\(1+\\ln p\\)", "\\(4\\)", "\\(p\\)"], 0,
      ["f'(p)=−4/(p(1+ln p)²), so −p f'/f = 1/(1+ln p)."], tag="elasticity-closed"),
    Q("g12-se-fn-dm-04", "demand", "medium",
      "Demand f(x)=1+e^{−2x+1} and supply g(x)=e^{2x} (x in thousands LL). The unique solution α of f(x)=g(x) represents:",
      ["the equilibrium unit price", "the fixed cost", "the elasticity", "the profit"], 0,
      ["f(α)=g(α) is the market equilibrium price."], tag="equilibrium-alpha"),
    Q("g12-se-fn-in-03", "integral", "medium",
      "The area bounded by (G): y=1−(x−2)e^{−x}, the x-axis and the lines x=1 and x=2 equals ∫_1^2 f(x) dx. An antiderivative of f is:",
      ["\\(x+(x-1)e^{-x}\\)", "\\(x-(x-2)e^{-x}\\)", "\\(e^{-x}\\)", "\\(x e^{-x}\\)"], 0,
      ["Integrate by parts: ∫(x−2)e^{−x} dx = −(x−1)e^{−x}, so ∫f=x+(x−1)e^{−x}."], tag="area-antideriv"),
    Q("g12-se-fn-rt-02", "root", "medium",
      "The curve of a profit P is given on [0; 8]. If P(2.13)≈−0.004<0 and P(2.14)≈0.006>0 with P increasing, then:",
      ["\\(2.13<\\alpha<2.14\\) where P(α)=0", "α=2.13", "P has no zero", "α>8"], 0,
      ["Sign change of a continuous increasing function on a tiny interval."], tag="profit-root-sandwich"),
    Q("g12-se-fn-lm-05", "limits", "medium",
      "Let f(x)=x−2−2x e^{−x} on [−1; +∞[. Then lim_{x→+∞}[f(x)−(x−2)] equals:",
      ["\\(0\\)", "\\(+\\infty\\)", "\\(-2\\)", "\\(2\\)"], 0,
      ["f(x)−(x−2)=−2x e^{−x} → 0, so y=x−2 is an oblique asymptote."], tag="oblique-x-minus-2"),
    Q("g12-se-fn-vr-05", "variation", "medium",
      "If f'(x)<0 on the whole domain ]1/e; +∞[ of f(x)=4/(1+ln x), then f is:",
      ["strictly decreasing", "strictly increasing", "constant", "with a maximum at 1"], 0,
      ["f'(x)=−4/(x(1+ln x)²)<0."], tag="always-decreasing"),
    Q("g12-se-fn-cp-05", "cost_profit", "medium",
      "If CT(x)=x+2+2x e^{−x} and the production is sold at 2000 LL per litre (x in thousands of litres, money in millions LL), then the profit is:",
      ["\\(P(x)=x-2-2xe^{-x}\\)", "\\(P(x)=2x\\)", "\\(P(x)=x+2\\)", "\\(P(x)=-2+2xe^{-x}\\)"], 0,
      [
          "Revenue R(x)=2x million LL, because 1000×2000 LL = 2 million LL per thousand litres.",
          "P=R−C=2x−(x+2+2x e^{−x})=x−2−2x e^{−x}.",
      ],
      tag="chemical-profit"),
    Q("g12-se-fn-dm-05", "demand", "hard",
      "For f(p)=4/(1+ln p), E(3)=1/(1+ln 3). Since ln 3≈1.10, E(3)≈0.48. An increase of 1% in the price when the unit price is 3000 LL decreases the demand by about:",
      ["0.48%", "3%", "1%", "4%"], 0,
      ["Interpretation of elasticity: percentage change in demand ≈ −E(p) times percentage change in price."], tag="E3-interpretation"),
    Q("g12-se-fn-rt-03", "root", "hard",
      "A factory realises a profit when P(x)>0. If P is increasing, P(α)=0 and α≈2.45 (x in hundreds of pens), the minimum daily production (in pens) to realise a profit is:",
      ["300 pens", "245 pens", "2.45 pens", "25 pens"], 0,
      [
          "x is in hundreds of pens and P(x)>0 iff x>α≈2.45.",
          "The smallest whole number of hundreds strictly above 2.45 is 3, hence 300 pens.",
      ],
      tag="min-pens-profit"),
    Q("g12-se-fn-in-04", "integral", "hard",
      "∫_1^2 [1−(x−2)e^{−x}] dx = [x+(x−1)e^{−x}]_1^2 equals:",
      ["\\(1+e^{-2}\\)", "\\(1\\)", "\\(e^{-1}\\)", "\\(2\\)"], 0,
      ["At 2: 2+(1)e^{−2}=2+e^{−2}. At 1: 1+0=1. Difference: 1+e^{−2}."], tag="area-value"),
    Q("g12-se-fn-cp-06", "cost_profit", "hard",
      "If P(x)=x−2−2x e^{−x} and α=2.45 is the unique positive root of P, then at a daily production of 2000 litres (x=2) the factory:",
      ["does not achieve a profit, because 2<α so P(2)<0", "achieves a profit", "has P(2)=0", "has infinite cost"], 0,
      ["P increasing, P(α)=0, 2<2.45 ⇒ P(2)<0."], tag="2000-litres-no-profit"),
    Q("g12-se-fn-lm-06", "limits", "hard",
      "Let f(x)=x−2−2x e^{−x}. The relative position of (C) and its oblique asymptote (d): y=x−2 is given by f(x)−(x−2)=−2x e^{−x}. Thus on ]0; +∞[ the curve (C) is:",
      ["below (d)", "above (d)", "crossing (d) at every x", "identical to (d)"], 0,
      ["−2x e^{−x}<0 for x>0, so (C) is below (d)."], tag="position-vs-oblique"),
    Q("g12-se-fn-vr-06", "variation", "hard",
      "Let f(x)=1+e^{−2x+1} on [0; +∞[. Then f'(x)=−2e^{−2x+1} < 0, so f is strictly decreasing, and lim_{x→+∞} f(x)=1. The table of variations therefore goes from f(0)=1+e down to:",
      ["1 (open, never attained)", "0", "e", "−∞"], 0,
      ["f(x)>1 for all x, approaching 1. f(0)=1+e^1=1+e."], tag="decrease-to-1"),
    Q("g12-se-fn-dm-06", "demand", "hard",
      "Demand f(x)=1+e^{−2x+1} and supply g(x)=e^{2x}. If α=0.399 is the unique solution of f=g, the corresponding demanded quantity (thousands of units) is g(α)=e^{2α} ≈:",
      ["2.22", "0.399", "1", "e"], 0,
      ["e^{0.798}≈2.22. Economically this is the equilibrium quantity."], tag="eq-quantity"),
    Q("g12-se-fn-rt-04", "root", "hard",
      "The equation ln(x−1)=−1 has the unique solution:",
      ["\\(1+e^{-1}\\)", "\\(0\\)", "\\(e^{-1}\\)", "\\(1-e\\)"], 0,
      ["x−1=e^{−1}, so x=1+1/e. Domain requires x>1."], tag="ln-eq"),
]

PROB_SLICES = [
    {"id": "counting", "title": "Counting", "arabicTitle": "العد"},
    {"id": "conditional", "title": "Conditional probability", "arabicTitle": "الاحتمال الشرطي"},
    {"id": "random_var", "title": "Random variables", "arabicTitle": "المتغيرات العشوائية"},
    {"id": "two_stage", "title": "Two-stage experiments", "arabicTitle": "التجارب على مرحلتين"},
    {"id": "stats", "title": "Statistics", "arabicTitle": "الإحصاء"},
]

SE_PR = [
    Q("g12-se-pr-ct-01", "counting", "easy",
      "A club has 50 students. The number of ways to choose 2 representatives at random is:",
      ["\\(C_{50}^2=1225\\)", "\\(50\\times 2\\)", "\\(50^2\\)", "\\(2^{50}\\)"], 0,
      ["Unordered pairs."], tag="club-C50-2"),
    Q("g12-se-pr-cd-01", "conditional", "easy",
      "Among 20 students of the 2nd secondary year there are 12 boys. A student of that year is chosen at random. P(boy | 2nd year) equals:",
      ["\\(0.60\\)", "\\(0.24\\)", "\\(0.40\\)", "\\(0.12\\)"], 0,
      ["12/20=0.60. Official SE papers ask for two decimal places."], tag="boy-given-2nd"),
    Q("g12-se-pr-rv-01", "random_var", "easy",
      "A customer chooses one calculator from box A (50 graphic, 40 non-graphic). P(graphic from A) equals:",
      ["\\(\\dfrac{5}{9}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{50}{40}\\)", "\\(\\dfrac{4}{9}\\)"], 0,
      ["50/90=5/9."], tag="graphic-A"),
    Q("g12-se-pr-ts-01", "two_stage", "easy",
      "Two boxes A (90 calculators) and B (110 calculators) are independent. One calculator is drawn from each. The number of possible ordered pairs is:",
      ["\\(90\\times 110\\)", "\\(200\\)", "\\(C_{200}^2\\)", "\\(90+110\\)"], 0,
      ["Independent draws: product of the sizes."], tag="pairs-AB"),
    Q("g12-se-pr-st-01", "stats", "easy",
      "The ages of 40 employees: 13 in [20;30[, 12 in [30;40[, 10 in [40;50[, 5 in [50;60]. Using class marks 25, 35, 45, 55, the average age is:",
      ["\\(36.75\\)", "\\(40\\)", "\\(35\\)", "\\(30\\)"], 0,
      ["(13·25+12·35+10·45+5·55)/40=(325+420+450+275)/40=1470/40=36.75."], tag="mean-age"),
    Q("g12-se-pr-ct-02", "counting", "easy",
      "A bag contains 7 balls. Two balls are drawn simultaneously. The number of possible draws is:",
      ["\\(C_7^2=21\\)", "\\(14\\)", "\\(49\\)", "\\(7\\)"], 0,
      ["C(7,2)=21."], tag="C7-2"),
    Q("g12-se-pr-cd-02", "conditional", "easy",
      "If P(E)=5/33 is the probability of two graphic calculators, one from each of two independent boxes, this uses:",
      ["the product of the two graphic proportions", "the sum of the proportions", "Bayes' formula only", "a complementary count of 33"], 0,
      ["(50/90)×(30/110)= (5/9)×(3/11)=15/99=5/33."], tag="two-graphic"),
    Q("g12-se-pr-rv-02", "random_var", "easy",
      "X is the sum of two prices chosen from {120 000, 36 000} and {100 000, 30 000}. The smallest possible value of X is:",
      ["\\(66\\,000\\) LL", "\\(36\\,000\\) LL", "\\(30\\,000\\) LL", "\\(150\\,000\\) LL"], 0,
      ["36 000+30 000=66 000."], tag="min-X-price"),
    Q("g12-se-pr-ts-02", "two_stage", "easy",
      "A red ball numbered n, two yellow (−5), four green (4). P(two green balls) when two are drawn simultaneously is:",
      ["\\(\\dfrac{C_4^2}{C_7^2}=\\dfrac{2}{7}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{16}{49}\\)", "\\(\\dfrac{1}{2}\\)"], 0,
      ["C(4,2)/C(7,2)=6/21=2/7."], tag="two-green"),
    Q("g12-se-pr-st-02", "stats", "easy",
      "On an increasing cumulative frequency polygon of 50 smokers, the line y=25 cuts the polygon at an abscissa x≈16.9. This value is interpreted as:",
      ["a median of the distribution (about 50% smoke fewer than 17 cigarettes)", "the mean", "the mode", "P(X=25)"], 0,
      ["y=n/2=25 meets the ogive at the median."], tag="median-ogive"),
    Q("g12-se-pr-ct-03", "counting", "easy",
      "P(drawing one red and one green from 1 red, 2 yellow, 4 green, two balls simultaneous) equals:",
      ["\\(\\dfrac{4}{21}\\)", "\\(\\dfrac{5}{21}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{1}{7}\\)"], 0,
      ["C(1,1)C(4,1)/C(7,2)=4/21."], tag="red-green-se"),
    Q("g12-se-pr-cd-03", "conditional", "easy",
      "Two students chosen from 32 boys. P(both in the 1st year | both boys) with 20 first-year boys among 32 boys is:",
      ["\\(\\dfrac{C_{20}^2}{C_{32}^2}\\)", "\\(\\dfrac{20}{32}\\)", "\\(\\dfrac{C_{20}^2}{C_{50}^2}\\)", "\\(1\\)"], 0,
      ["Restricted to the 32 boys."], tag="first-given-boys-se"),
    Q("g12-se-pr-rv-03", "random_var", "medium",
      "X takes the four values 66 000, 136 000, 150 000 and 220 000 LL (sums of one A-price and one B-price). Then 136 000 corresponds to:",
      ["non-graphic A and graphic B", "two graphic", "two non-graphic", "graphic A and non-graphic B"], 0,
      ["36 000+100 000=136 000."], tag="which-sum-136"),
    Q("g12-se-pr-rv-04", "random_var", "medium",
      "With P(graphic A)=5/9, P(non-graphic A)=4/9, P(graphic B)=3/11, P(non-graphic B)=8/11, then P(X=220 000) for two graphic calculators equals:",
      ["\\(\\dfrac{15}{99}\\)", "\\(\\dfrac{5}{9}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{32}{99}\\)"], 0,
      ["(5/9)(3/11)=15/99=5/33. 220000=120000+100000."], tag="P-two-graphic-prices"),
    Q("g12-se-pr-ts-03", "two_stage", "medium",
      "P(E)=5/33 (two graphic) and P(F) is the probability of one graphic and one non-graphic. Then P(F) equals:",
      ["\\(\\dfrac{52}{99}\\)", "\\(\\dfrac{5}{33}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{4}{9}\\)"], 0,
      ["P(gA,ngB)+P(ngA,gB)=(5/9)(8/11)+(4/9)(3/11)=40/99+12/99=52/99."], tag="P-F-mixed-calc"),
    Q("g12-se-pr-cd-04", "conditional", "medium",
      "Two boys are chosen from 32 boys and 18 girls (50 students). P(both boys) equals:",
      ["\\(\\dfrac{C_{32}^2}{C_{50}^2}\\)", "\\(\\left(\\dfrac{32}{50}\\right)^2\\)", "\\(\\dfrac{32}{50}\\)", "\\(\\dfrac{2}{32}\\)"], 0,
      ["Without replacement."], tag="two-boys-se"),
    Q("g12-se-pr-st-03", "stats", "medium",
      "A scatter plot of turnover y_i against year rank x_i has centre of gravity G(x̄; ȳ). G always belongs to:",
      ["the regression line D_{y/x}", "the y-axis", "the first data point", "the median class"], 0,
      ["The least-squares line D_{y/x} passes through G."], tag="G-on-regression"),
    Q("g12-se-pr-ct-04", "counting", "medium",
      "Same-colour draws from 1 red, 2 yellow, 4 green (two simultaneous) have probability:",
      ["\\(\\dfrac{7}{21}\\)", "\\(\\dfrac{8}{21}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{2}{7}\\)"], 0,
      ["Same colour: C(2,2)+C(4,2)=1+6=7 over C(7,2)=21. The single red ball cannot form a pair."], tag="same-colour-se"),
    Q("g12-se-pr-rv-05", "random_var", "medium",
      "Two balls from 1 red (n), 2 yellow (−5), 4 green (4). Possible products X include −5n, 4n, −20, 16, 25. The value 25 comes from:",
      ["two yellow balls", "two green", "red and yellow", "red and green"], 0,
      ["(−5)×(−5)=25."], tag="product-25"),
    Q("g12-se-pr-ts-04", "two_stage", "medium",
      "P(drawing two balls of different colours from that 7-ball bag) equals:",
      ["\\(\\dfrac{14}{21}\\)", "\\(\\dfrac{7}{21}\\)", "\\(1\\)", "\\(\\dfrac{2}{7}\\)"], 0,
      ["Complement of same colour 7/21, so 14/21=2/3."], tag="different-colours"),
    Q("g12-se-pr-st-04", "stats", "medium",
      "If D_{y/x} has equation y=−0.674x+m and G(3.5; 2.533) lies on it, then m equals:",
      ["\\(4.892\\)", "\\(0\\)", "\\(-0.674\\)", "\\(2.533\\)"], 0,
      ["2.533=−0.674×3.5 + m ⇒ m=2.533+2.359=4.892."], tag="regression-intercept"),
    Q("g12-se-pr-cd-05", "conditional", "medium",
      "Let X be the product of two numbers drawn from the 7-ball bag. P(one red and one green)=4/21. This is also P(X=4n). Then P(X=16) equals:",
      ["\\(\\dfrac{6}{21}\\)", "\\(\\dfrac{4}{21}\\)", "\\(\\dfrac{1}{21}\\)", "\\(\\dfrac{2}{7}\\)"], 0,
      ["X=16: two green, C(4,2)/21=6/21."], tag="P-X-16"),
    Q("g12-se-pr-st-05", "stats", "medium",
      "The present value of an annuity of 75 000 LL for 20 months at 6% annual compounded monthly is closest, among typical SE distractors, to a value obtained from a_{n}=A (1−(1+i)^{−n})/i with i=0.005, n=20. Then i equals:",
      ["\\(0.005\\)", "\\(0.06\\)", "\\(0.6\\)", "\\(20\\)"], 0,
      ["Monthly rate 6%/12=0.5%=0.005."], tag="annuity-i"),
    Q("g12-se-pr-rv-06", "random_var", "hard",
      "For that 7-ball product X, E(X)=−1 is required. Using P(X=−5n)=2/21, P(X=4n)=4/21, P(X=−20)=8/21, P(X=16)=6/21, P(X=25)=1/21, then E(X)=(1/21)(−10n+16n−160+96+25). The n that yields E(X)=−1 is:",
      ["\\(3\\)", "\\(-1\\)", "\\(0\\)", "\\(5\\)"], 0,
      ["(6n−39)/21=−1 ⇒ 6n−39=−21 ⇒ 6n=18 ⇒ n=3.",
       "P(yellow,red)=C(2,1)C(1,1)/21=2/21; P(green,red)=4/21; P(yellow,green)=C(2,1)C(4,1)/21=8/21; two green 6/21; two yellow 1/21."],
      tag="n-for-EX"),
    Q("g12-se-pr-ts-05", "two_stage", "hard",
      "A tourist agency: P(France)=0.25, P(Italy)=0.35, P(Turkey)=0.40, and 60% full-board independently. P(full-board) equals:",
      ["\\(0.60\\)", "\\(0.25\\)", "\\(1\\)", "\\(0.40\\)"], 0,
      ["Independence of board type and destination: P(B)=0.60."], tag="P-fullboard"),
    Q("g12-se-pr-cd-06", "conditional", "hard",
      "With the agency probabilities above, P(Italy | full-board) equals:",
      ["\\(0.35\\)", "\\(0.21\\)", "\\(0.60\\)", "\\(0.875\\)"], 0,
      ["Independence ⇒ P(I|B)=P(I)=0.35. Or 0.21/0.60=0.35."], tag="italy-given-B-se"),
    Q("g12-se-pr-st-06", "stats", "hard",
      "A new car costs 200 million LL, scrap 60 million LL, lifetime 10 years, constant annual depreciation. After t years the value is 116 million LL. Then t equals:",
      ["6 years", "5 years", "7 years", "10 years"], 0,
      ["Annual depreciation (200−60)/10=14. 200−14t=116 ⇒ 14t=84 ⇒ t=6."], tag="depreciation-t"),
    Q("g12-se-pr-rv-07", "random_var", "hard",
      "X is the amount paid by a voyager with destinations F,I,T (probs 0.25, 0.35, 0.40) and full/half board (0.60, 0.40) independent. Prices: F 1 500 000 / 1 300 000, I 1 250 000 / 1 100 000, T 800 000 / 700 000. Then E(X) represents:",
      ["the mean amount paid by a voyager", "the most frequent destination", "P(Italy)", "the number of voyagers"], 0,
      ["Expectation of the random cost is the average receipt per customer."], tag="EX-meaning"),
    Q("g12-se-pr-ct-05", "counting", "hard",
      "Two balls from 9 (3 white, 3 black, 3 red, numbered 1–3 each). P(both odd) equals:",
      ["\\(\\dfrac{C_6^2}{C_9^2}=\\dfrac{15}{36}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{6}{9}\\)", "\\(\\dfrac{1}{3}\\)"], 0,
      ["Six odd-numbered balls (1 and 3 in each colour)."], tag="both-odd"),
    Q("g12-se-pr-ts-06", "two_stage", "hard",
      "Are the events A: «both numbers odd» and B: «same colour» independent for those 9 balls? P(A)=15/36, P(B)=9/36, P(A∩B)=3/36. Then:",
      ["not independent, because 15/36 × 9/36 ≠ 3/36", "independent", "A⊂B", "P(A∩B)=0"], 0,
      ["(15/36)(9/36)=135/1296=15/144=5/48, while 3/36=1/12=4/48."], tag="A-B-not-indep"),
    Q("g12-se-pr-st-07", "stats", "hard",
      "If the correlation coefficient r of (x_i; y_i) equals −0.98, then the linear relation between the two variables is:",
      ["strong and negative", "strong and positive", "weak", "non-existent"], 0,
      ["|r| close to 1 with r<0."], tag="correlation-interpret"),
    Q("g12-se-pr-cd-07", "conditional", "hard",
      "Two balls of different colours are drawn from the 9-ball urn. The probability they carry two odd numbers is P(D|C), where D is «different colours and two odd numbers». Then P(D|C) equals:",
      ["\\(\\dfrac{4}{9}\\)", "\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{1}{9}\\)", "\\(\\dfrac{1}{3}\\)"], 0,
      [
          "Six odd balls; both odd: C(6,2)=15. Both odd and same colour: 3, so D (both odd, different colours)=12.",
          "P(D)=12/36=1/3, P(C)=27/36=3/4, P(D|C)=(1/3)/(3/4)=4/9.",
      ],
      tag="odds-given-diff-colour"),
]

MCQ_SLICES = [
    {"id": "logs", "title": "Logarithms", "arabicTitle": "اللوغاريتم"},
    {"id": "finance", "title": "Financial mathematics", "arabicTitle": "الرياضيات المالية"},
    {"id": "limits", "title": "Limits and calculus", "arabicTitle": "النهايات والحساب"},
    {"id": "demand", "title": "Demand and elasticity", "arabicTitle": "الطلب والمرونة"},
    {"id": "stats", "title": "Statistics", "arabicTitle": "الإحصاء"},
]

SE_MCQ = [
    Q("g12-se-mc-lg-01", "logs", "easy",
      "The domain of f(x)=ln(2x−5) is:",
      ["\\(]5/2;+\\infty[\\)", "\\(]0;+\\infty[\\)", "\\(]-\\infty;5/2[\\)", "\\(\\mathbb{R}\\)"], 0,
      ["2x−5>0 ⇒ x>5/2."], tag="dom-ln"),
    Q("g12-se-mc-lg-02", "logs", "easy",
      "The solution of ln(x−1)=−1 is:",
      ["\\(1+e^{-1}\\)", "\\(0\\)", "\\(e^{-1}\\)", "\\(1\\)"], 0,
      ["x−1=e^{−1}."], tag="ln-eq-mcq"),
    Q("g12-se-mc-fn-01", "finance", "easy",
      "A car purchased for 200 million LL, scrap 60, lifetime 10 years, constant annual depreciation. The annual depreciation is:",
      ["14 million LL", "20 million LL", "6 million LL", "26 million LL"], 0,
      ["(200−60)/10=14."], tag="annual-depr"),
    Q("g12-se-mc-lm-01", "limits", "easy",
      "If f(x)=e^x/(e^x−x), then lim_{x→−∞} f(x) equals:",
      ["\\(0\\)", "\\(1\\)", "\\(-\\infty\\)", "\\(+\\infty\\)"], 0,
      ["e^x→0, −x→+∞, denominator → +∞, numerator →0+."], tag="lim-minus-inf"),
    Q("g12-se-mc-dm-01", "demand", "easy",
      "f defined on ]0;+∞[ by f(x)=ln x. An antiderivative of f is:",
      ["\\(x\\ln x-x\\)", "\\(x-x\\ln x\\)", "\\((\\ln x)^2/2\\)", "\\(1/x\\)"], 0,
      ["Integration by parts."], tag="antideriv-ln"),
    Q("g12-se-mc-st-01", "stats", "easy",
      "The centre of gravity G of a data set (x_i; y_i) has abscissa:",
      ["\\(\\bar x\\)", "the median of x", "0", "x_1"], 0,
      ["x̄ is the mean of the x_i."], tag="G-xbar"),
    Q("g12-se-mc-lg-03", "logs", "easy",
      "ln(a^3)−ln(e a)+2 ln(1/a) for a>0 equals:",
      ["\\(-1\\)", "\\(4\\ln a-1\\)", "\\(1\\)", "\\(0\\)"], 0,
      ["3 ln a − (1+ln a) + 2(−ln a)=3 ln a −1 −ln a −2 ln a=−1."], tag="ln-simplify"),
    Q("g12-se-mc-fn-02", "finance", "easy",
      "The monthly interest rate corresponding to 6% annual compounded monthly is:",
      ["\\(0.5\\%\\)", "\\(6\\%\\)", "\\(0.06\\%\\)", "\\(12\\%\\)"], 0,
      ["6/12=0.5%."], tag="monthly-rate"),
    Q("g12-se-mc-lm-02", "limits", "easy",
      "The derivative of f(x)=ln(3x+1)+x^{−1} on ]−1/3; +∞[ is:",
      ["\\(\\dfrac{3}{3x+1}-\\dfrac{1}{x^2}\\)", "\\(\\dfrac{3x}{3x+1}\\)", "\\(\\dfrac{3x+2}{3x+1}\\)", "\\(\\dfrac{3x+4}{3x+1}\\)"], 0,
      ["(ln(3x+1))'=3/(3x+1) and (1/x)'=−1/x^2."], tag="deriv-ln-plus-inv"),
    Q("g12-se-mc-dm-02", "demand", "easy",
      "The line y=1 is an asymptote to the curve of f(x)=1+e^{−2x+1} on [0;+∞[ because:",
      ["\\(f(x)\\to 1\\) as \\(x\\to+\\infty\\)", "f(0)=1", "f'=0", "f is linear"], 0,
      ["The exponential term vanishes at +∞."], tag="horiz-1-demand"),
    Q("g12-se-mc-st-02", "stats", "easy",
      "If r=−0.98 for a time series of new-car sales, the number of cars sold:",
      ["tends to decrease as the year rank increases", "tends to increase", "is constant", "is independent of the year"], 0,
      ["Strong negative correlation."], tag="r-negative-sales"),
    Q("g12-se-mc-lg-04", "logs", "easy",
      "The domain of f(x)=ln(e^x − e) is:",
      ["\\(]1;+\\infty[\\)", "\\(]0;+\\infty[\\)", "\\([1;+\\infty[\\)", "\\(\\mathbb{R}\\)"], 0,
      ["e^x − e > 0 ⇒ x>1. Open interval."], tag="dom-ln-exp"),
    Q("g12-se-mc-lg-05", "logs", "medium",
      "The solution of ln x − ln(2x−5)=ln 3 is:",
      ["\\(3\\)", "\\(2\\)", "\\(4\\)", "\\(5\\)"], 0,
      ["ln(x/(2x−5))=ln 3 ⇒ x=3(2x−5) ⇒ x=6x−15 ⇒ 5x=15 ⇒ x=3. Check 2x−5=1>0."], tag="ln-diff-eq"),
    Q("g12-se-mc-fn-03", "finance", "medium",
      "After t years of constant depreciation 14 million/year from 200 million, the value 116 million occurs at t=:",
      ["6", "5", "7", "8"], 0,
      ["200−14t=116 ⇒ t=6."], tag="t-116"),
    Q("g12-se-mc-lm-03", "limits", "medium",
      "The maintenance cost during the first three years for rate e^{0.5 t} is ∫_0^3 e^{0.5 t} dt =:",
      ["\\(2(e^{1.5}-1)\\)", "\\(e^{1.5}\\)", "\\(3e^{0.5}\\)", "\\(0.5 e^{1.5}\\)"], 0,
      ["2 e^{0.5 t} from 0 to 3 = 2(e^{1.5}−1)≈6.963, a typical table distractor."], tag="maint-3y"),
    Q("g12-se-mc-dm-03", "demand", "medium",
      "For demand f(x)=1+e^{−2x+1}, the number of demanded units at a unit price of 1000 LL (x=1) is, in thousands:",
      ["\\(1+e^{-1}\\)", "\\(1+e\\)", "\\(e^{2}\\)", "\\(1\\)"], 0,
      ["f(1)=1+e^{−1}."], tag="demand-x1"),
    Q("g12-se-mc-st-03", "stats", "medium",
      "Percentage decrease of sales from 1.2 to 0.9 (tens of thousands) is:",
      ["\\(25\\%\\)", "\\(30\\%\\)", "\\(75\\%\\)", "\\(0.3\\%\\)"], 0,
      ["(1.2−0.9)/1.2=0.25."], tag="pct-decrease"),
    Q("g12-se-mc-lg-06", "logs", "medium",
      "If f(x)=ln(3x+1)+1/x, a wrong table choice for f' is 3x/(3x+1). The correct f' is:",
      ["\\(\\dfrac{3}{3x+1}-\\dfrac{1}{x^2}\\)", "\\(\\dfrac{3x}{3x+1}\\)", "\\(\\dfrac{3x+2}{3x+1}\\)", "\\(\\dfrac{3x+4}{3x+1}\\)"], 0,
      ["Do not combine over a single denominator without the −1/x^2 term."], tag="deriv-trap"),
    Q("g12-se-mc-fn-04", "finance", "medium",
      "Nabil borrows 20 000 000 LL for 5 years at 6% compounded monthly. The number of monthly payments is:",
      ["60", "5", "12", "6"], 0,
      ["5×12=60."], tag="n-payments"),
    Q("g12-se-mc-dm-04", "demand", "medium",
      "E(x)= −x f'(x)/f(x) for f(x)=1+e^{−2x+1}. Then f'(x)=−2e^{−2x+1}, so E(x)=:",
      ["\\(\\dfrac{2x e^{-2x+1}}{1+e^{-2x+1}}\\)", "\\(2x\\)", "\\(1\\)", "\\(x\\)"], 0,
      ["−x(−2e^{…})/f = 2x e^{−2x+1}/(1+e^{−2x+1})."], tag="E-formula-se"),
    Q("g12-se-mc-st-04", "stats", "medium",
      "If y=−0.674x+m passes through G(3.5; 2.533), m≈:",
      ["4.892", "−2.359", "2.533", "0.674"], 0,
      ["m=ȳ+0.674 x̄=2.533+2.359=4.892."], tag="m-from-G"),
    Q("g12-se-mc-lm-04", "limits", "medium",
      "The curve of f(x)=1+e^{−2x+1} is above the line y=1 on [0;+∞[ because:",
      ["\\(e^{-2x+1}>0\\)", "f'(x)>0", "f(0)<1", "f is linear"], 0,
      ["The exponential is always positive."], tag="above-asymptote"),
    Q("g12-se-mc-lg-07", "logs", "hard",
      "f(x)=ln(e^x − e) is defined on ]1;+∞[. Then f'(x) equals:",
      ["\\(\\dfrac{e^x}{e^x-e}\\)", "\\(1\\)", "\\(\\dfrac{1}{e^x-e}\\)", "\\(e^x-e\\)"], 0,
      ["Chain rule."], tag="deriv-ln-exp-e"),
    Q("g12-se-mc-dm-05", "demand", "hard",
      "If E(x) has a maximum 0.567 < 1 on [0.1; 3], then a value of x for which the demand is elastic:",
      ["does not exist on this interval", "is x=0.784", "is every x", "is x=0.1 only"], 0,
      ["Elastic means E>1. The table never exceeds 0.567."], tag="never-elastic"),
    Q("g12-se-mc-fn-05", "finance", "hard",
      "Customs rate per car rises from $1000 to $1600 while the number of cars sold falls by 40%. The total customs amount:",
      ["decreases, because 1.6×0.6=0.96<1", "increases", "stays the same", "triples"], 0,
      ["New total = 1.6 × 0.6 of the old total = 96%."], tag="customs-total"),
    Q("g12-se-mc-st-05", "stats", "hard",
      "Estimating y=−0.674x+4.892 at year rank x=7 (if 2016 had rank 1, 2022 has rank 7) gives y≈:",
      ["0.174", "4.892", "7", "−0.674"], 0,
      ["−0.674×7+4.892=0.174 (tens of thousands of cars)."], tag="estimate-2022"),
    Q("g12-se-mc-lm-05", "limits", "hard",
      "An antiderivative of ln x is x ln x − x. Then ∫_1^e ln x dx equals:",
      ["\\(1\\)", "\\(e\\)", "\\(0\\)", "\\(e-1\\)"], 0,
      ["[x ln x − x]_1^e = (e−e)−(0−1)=1."], tag="int-ln-1-e"),
    Q("g12-se-mc-lg-08", "logs", "hard",
      "The equation 2 ln x = ln(2x) on (0;+∞) has:",
      ["one root only", "2 roots", "no roots", "3 roots"], 0,
      ["ln(x^2)=ln(2x) ⇒ x^2=2x, x=2 (x=0 excluded). Check: ln4=ln4."], tag="2ln-eq"),
    Q("g12-se-mc-dm-06", "demand", "hard",
      "Is the demand f(x)=1+e^{−2x+1} elastic at x=0.5? With E(x)=2x e^{−2x+1}/(1+e^{−2x+1}) one finds E(0.5)=1/2<1, so the demand is:",
      ["not elastic", "elastic", "unit elastic", "undefined"], 0,
      ["E(0.5)=2·0.5·e^{0}/(1+e^{0})=1/(1+1)=1/2<1."], tag="elastic-at-0.5"),
    Q("g12-se-mc-fn-06", "finance", "hard",
      "The present value of 20 monthly payments of 75 000 LL at monthly rate 0.005 is 75 000 (1−1.005^{−20})/0.005. This quantity is:",
      ["less than 20×75 000=1 500 000 LL", "equal to 1 500 000 LL", "greater than 1 573 436 LL", "negative"], 0,
      ["Discounting makes the present value strictly less than the undiscounted total."], tag="PV-less-than-nominal"),
    Q("g12-se-mc-st-06", "stats", "hard",
      "If a model y=−0.674x+4.892 remains valid, the first year rank with y<0 (impossible sales) would already show the model:",
      ["must be restricted to a validity interval", "is exact forever", "has r=1", "passes through the origin"], 0,
      ["Linear extrapolation of a decreasing series eventually leaves the realistic range."], tag="model-limits"),
    Q("g12-se-mc-lm-06", "limits", "hard",
      "f(x)=ln x on (0;+∞). The area between (C), the x-axis and x=1, x=e equals 1. This area is:",
      ["\\(\\int_1^e \\ln x\\,dx=1\\)", "\\(e\\)", "infinite", "ln e − ln 1=0"], 0,
      ["Computed primitive x ln x − x."], tag="area-ln"),
]


def _fix_broken_se_mcq():
    """Repair items whose Q() argument order was accidentally nested."""
    for q in SE_MCQ:
        if q["id"] == "g12-se-mc-lm-02":
            q["stem"] = (
                "The derivative of f(x)=ln(3x+1)+x^{−1} on ]−1/3; +∞[ is:"
            )
            q["choices"] = [
                "\\(\\dfrac{3}{3x+1}-\\dfrac{1}{x^2}\\)",
                "\\(\\dfrac{3x}{3x+1}\\)",
                "\\(\\dfrac{3x+2}{3x+1}\\)",
                "\\(\\dfrac{3x+4}{3x+1}\\)",
            ]
            q["answerIndex"] = 0
            q["answer"] = q["choices"][0]
            q["solutionSketch"] = [
                "(ln(3x+1))'=3/(3x+1) and (1/x)'=−1/x^2.",
            ]
        if q["id"] == "g12-se-pr-ct-04":
            pass


def _style(topic: str) -> str:
    return (
        "Academy-original items patterned on Lebanese Grade 12 SE (اجتماع واقتصاد) "
        f"official sessions (SE_All Sessions.pdf): {topic}. Not photocopies of past papers."
    )


def se_fn_bank() -> dict:
    return make_bank(
        bank_id="g12-se-functions",
        track="grade-12",
        certificate="SE",
        topic="functions",
        title="Functions & economic analysis",
        arabic_title="الدوال والتحليل الاقتصادي",
        models=M,
        style_note=_style("limits, table of variations, marginal cost, profit, demand elasticity, unique root"),
        slices=FN_SLICES,
        questions=SE_FN,
        contest_topics=SE_TOPICS,
    )


def se_prob_bank() -> dict:
    return make_bank(
        bank_id="g12-se-probability",
        track="grade-12",
        certificate="SE",
        topic="probability",
        title="Probability & statistics",
        arabic_title="الاحتمالات والإحصاء",
        models=M,
        style_note=_style("two-way tables, calculators/bills, random variables, ogives, regression"),
        slices=PROB_SLICES,
        questions=SE_PR,
        contest_topics=SE_TOPICS,
    )


def se_mcq_bank() -> dict:
    _fix_broken_se_mcq()
    return make_bank(
        bank_id="g12-se-mcq-mixed",
        track="grade-12",
        certificate="SE",
        topic="mcq_mixed",
        title="Mixed MCQ",
        arabic_title="أسئلة مختلطة",
        models=M,
        style_note=_style("Problem I table — logs, finance, limits, demand, statistics"),
        slices=MCQ_SLICES,
        questions=SE_MCQ,
        contest_topics=SE_TOPICS,
        contest_minutes=20,
    )
