"""Grade 12 GS banks: functions, space geometry, probability, complex, mixed MCQ."""

from __future__ import annotations

from g12_bank_common import GS_MODELS, GS_TOPICS, item, make_bank

M = GS_MODELS


ERRORS: list[str] = []


def Q(qid, slice_id, difficulty, stem, choices, answer_index, sketch, latex=None, tag=""):
    try:
        return item(qid, slice_id, difficulty, stem, choices, answer_index, sketch, M, latex, tag)
    except Exception as exc:
        ERRORS.append(f"{qid}: {exc}")
        return None


FN_SLICES = [
    {"id": "limits", "title": "Limits and asymptotes", "arabicTitle": "النهايات والتقارب"},
    {"id": "variation", "title": "Derivatives and variations", "arabicTitle": "المشتقات وجدول التغيرات"},
    {"id": "de", "title": "Differential equations", "arabicTitle": "المعادلات التفاضلية"},
    {"id": "integral", "title": "Integration and area", "arabicTitle": "التكامل والمساحة"},
    {"id": "inverse", "title": "Inverse and logarithm", "arabicTitle": "العكسية واللوغاريتم"},
    {"id": "inflection", "title": "Inflection and position", "arabicTitle": "الانعطاف والموقع"},
]

GS_FN = [
    Q("g12-gs-fn-lm-01", "limits", "easy",
      "Let f(x)=e^{−2x}−2e^{−x}+1 on IR. Then lim_{x→+∞} f(x) equals:",
      ["\\(1\\)", "\\(0\\)", "\\(+\\infty\\)", "\\(-1\\)"], 0,
      ["Both exponentials vanish, so f(x)→1. The line y=1 is a horizontal asymptote."],
      latex="f(x)=e^{-2x}-2e^{-x}+1", tag="lim-plus-inf"),
    Q("g12-gs-fn-lm-02", "limits", "easy",
      "With the same f, lim_{x→−∞} f(x) equals:",
      ["\\(+\\infty\\)", "\\(1\\)", "\\(0\\)", "\\(-\\infty\\)"], 0,
      ["e^{−2x}=(e^{−x})² dominates and →+∞ as x→−∞."], tag="lim-minus-inf"),
    Q("g12-gs-fn-vr-01", "variation", "easy",
      "If f'(x)=−2e^{−2x}+2e^{−x}=2e^{−2x}(e^{x}−1), then f'(x)=0 at:",
      ["\\(x=0\\)", "\\(x=1\\)", "\\(x=-1\\)", "no real root"], 0,
      ["e^{−2x}>0, so f'=0 iff e^x=1 iff x=0."], tag="crit-0"),
    Q("g12-gs-fn-de-01", "de", "easy",
      "The characteristic equation of z''+3z'+2z=0 is r²+3r+2=0, whose roots are:",
      ["\\(-1\\) and \\(-2\\)", "\\(1\\) and \\(2\\)", "\\(-3\\) and \\(1\\)", "\\(0\\) and \\(-3\\)"], 0,
      ["(r+1)(r+2)=0."], tag="char-eq"),
    Q("g12-gs-fn-in-01", "integral", "easy",
      "An antiderivative of e^{−x} is −e^{−x}. Then ∫_0^{+∞} e^{−x} dx equals:",
      ["\\(1\\)", "\\(0\\)", "\\(+\\infty\\)", "\\(-1\\)"], 0,
      ["lim_{A→+∞}[−e^{−x}]_0^A=1."], tag="exp-improper"),
    Q("g12-gs-fn-iv-01", "inverse", "easy",
      "If f is continuous and strictly decreasing on [0;+∞[ with f([0;+∞[)=]1; 1+e], then f admits an inverse defined on:",
      ["\\(]1;1+e]\\)", "IR", "\\([0;+\\infty[\\)", "\\(]0;1[\\)"], 0,
      ["The inverse is defined on the range of f."], tag="inverse-domain"),
    Q("g12-gs-fn-if-01", "inflection", "easy",
      "A point of inflection of (C) is a point where f'' changes sign. If f''(x)=4e^{−2x}−2e^{−x}=2e^{−2x}(2−e^{x}), then f''(x)=0 at:",
      ["\\(x=\\ln 2\\)", "\\(x=0\\)", "\\(x=2\\)", "\\(x=e\\)"], 0,
      ["2−e^x=0 ⇒ x=ln 2."], tag="inflection-ln2"),
    Q("g12-gs-fn-lm-03", "limits", "easy",
      "The line y=1 is an asymptote of (C): y=e^{−2x}−2e^{−x}+1 at +∞. Then lim_{x→+∞}(f(x)−1) equals:",
      ["\\(0\\)", "\\(1\\)", "\\(+\\infty\\)", "\\(-2\\)"], 0,
      ["f(x)−1=e^{−2x}−2e^{−x}→0."], tag="f-minus-1"),
    Q("g12-gs-fn-vr-02", "variation", "easy",
      "On ]−∞; 0], f'(x)=2e^{−2x}(e^x−1) is:",
      ["negative or zero", "positive", "undefined", "always −1"], 0,
      ["e^x−1≤0 on ]−∞;0]."], tag="fprime-sign-left"),
    Q("g12-gs-fn-de-02", "de", "easy",
      "A particular solution of y''+3y'+2y=2 is a constant k. Then 2k=2 so k=:",
      ["\\(1\\)", "\\(2\\)", "\\(0\\)", "\\(-1\\)"], 0,
      ["For a constant, y''=y'=0, hence 2k=2."], tag="const-particular"),
    Q("g12-gs-fn-in-02", "integral", "easy",
      "∫ cos x dx = sin x + c. Then ∫_0^{π/2} cos x dx equals:",
      ["\\(1\\)", "\\(0\\)", "\\(\\pi/2\\)", "\\(-1\\)"], 0,
      ["sin(π/2)−sin 0=1."], tag="int-cos"),
    Q("g12-gs-fn-iv-02", "inverse", "easy",
      "If g=ln∘f with f(x)>0, then g'(x)=f'(x)/f(x). In particular at a point where f=1 and f'=2, g' equals:",
      ["\\(2\\)", "\\(1\\)", "\\(0\\)", "\\(1/2\\)"], 0,
      ["2/1=2."], tag="log-deriv"),
    Q("g12-gs-fn-lm-04", "limits", "medium",
      "Let f(x)=e^{−2x}−2e^{−x}+1. Then lim_{x→−∞} f(x)/x equals:",
      ["\\(-\\infty\\)", "\\(0\\)", "\\(1\\)", "\\(+\\infty\\)"], 0,
      ["f(x)∼e^{−2x}→+∞ while x→−∞, so f/x → −∞."], tag="f-over-x"),
    Q("g12-gs-fn-vr-03", "variation", "medium",
      "f'(x)=2e^{−2x}(e^x−1) changes from − to + at 0, so f has a minimum f(0) equal to:",
      ["\\(0\\)", "\\(1\\)", "\\(-1\\)", "\\(2\\)"], 0,
      ["f(0)=1−2+1=0."], tag="min-at-0"),
    Q("g12-gs-fn-de-03", "de", "medium",
      "The general solution of z''+3z'+2z=0 is z=C1 e^{−x}+C2 e^{−2x}. For (E): y''+3y'+2y=2 one sets y=z+1, hence:",
      ["\\(y=C_1 e^{-x}+C_2 e^{-2x}+1\\)", "\\(y=C_1 e^{x}+C_2 e^{2x}\\)", "\\(y=1\\) only", "\\(y=C_1+C_2 x\\)"], 0,
      ["Shift by the particular solution 1."], tag="general-sol-E"),
    Q("g12-gs-fn-de-04", "de", "medium",
      "The particular solution of (E) whose curve is tangent at O to (Ox) satisfies y(0)=0 and y'(0)=0. Then:",
      ["\\(y=e^{-2x}-2e^{-x}+1\\)", "\\(y=1\\)", "\\(y=e^{-x}\\)", "\\(y=0\\)"], 0,
      ["y=C1 e^{−x}+C2 e^{−2x}+1, y(0)=C1+C2+1=0, y'=−C1 e^{−x}−2C2 e^{−2x}, y'(0)=−C1−2C2=0 ⇒ C1=−2, C2=1."],
      tag="tangent-at-O"),
    Q("g12-gs-fn-in-03", "integral", "medium",
      "The area between (C): y=e^{−2x}−2e^{−x}+1, its asymptote y=1 and the axis of ordinates for x≥0 is ∫_0^{+∞}(1−f(x)) dx. Since 1−f(x)=2e^{−x}−e^{−2x}, this integral equals:",
      ["\\(\\dfrac{3}{2}\\)", "\\(1\\)", "\\(2\\)", "\\(+\\infty\\)"], 0,
      ["∫(2e^{−x}−e^{−2x})dx=−2e^{−x}+(1/2)e^{−2x}. From 0 to +∞: 0−(−2+1/2)=3/2."], tag="area-to-asymptote"),
    Q("g12-gs-fn-iv-03", "inverse", "medium",
      "Let g(x)=ln(f(x)) with f(x)=e^{−2x}−2e^{−x}+1=(1−e^{−x})². Then f(x)=0 iff x=0, so g is defined on:",
      ["\\(\\mathbb{R}\\setminus\\{0\\}\\)", "IR", "\\([0;+\\infty[\\)", "\\(]-\\infty;0]\\)"], 0,
      ["f(x)=(1−e^{−x})² ≥0 and vanishes only at 0, so ln∘f is defined for x≠0."], tag="dom-g"),
    Q("g12-gs-fn-if-02", "inflection", "medium",
      "The curve (C) of f(x)=e^{−2x}−2e^{−x}+1 meets its asymptote y=1 when e^{−x}(e^{−x}−2)=0, hence at:",
      ["\\(x=-\\ln 2\\)", "no finite point", "\\(x=0\\)", "\\(x=1\\)"], 0,
      ["e^{−x}=2 ⇒ x=−ln 2."], tag="meet-asymptote"),
    Q("g12-gs-fn-vr-04", "variation", "medium",
      "On [−3;3], f(x)=(2/3)√(9−x²) is the upper semi-ellipse of x²/9 + y²/4 =1. Then f(0) equals:",
      ["\\(2\\)", "\\(3\\)", "\\(0\\)", "\\(2/3\\)"], 0,
      ["(2/3)·3=2, the semi-minor axis."], tag="ellipse-top"),
    Q("g12-gs-fn-lm-05", "limits", "medium",
      "Prove that y=−2x is an asymptote of g(x)=ln(f(x)) as x→−∞ by studying g(x)+2x. Since f(x)∼e^{−2x}, ln f(x)∼−2x, so g(x)+2x →:",
      ["\\(0\\)", "\\(+\\infty\\)", "\\(-\\infty\\)", "\\(2\\)"], 0,
      ["f(x)=e^{−2x}(1−2e^{x}+e^{2x})=e^{−2x}(1−e^{x})², ln f=−2x+2 ln|1−e^{x}|, and as x→−∞, ln|1−e^{x}|→ln1=0."],
      tag="g-plus-2x"),
    Q("g12-gs-fn-in-04", "integral", "medium",
      "The ellipse of equation x²/9 + y²/4 = 1 has area:",
      ["\\(6\\pi\\)", "\\(3\\pi\\)", "\\(9\\pi\\)", "\\(2\\pi\\)"], 0,
      ["Ellipse x²/9+y²/4=1 has area π·3·2=6π."], tag="ellipse-area"),
    Q("g12-gs-fn-de-05", "de", "hard",
      "The particular solution of y'−(1/2)y=0 with y(−2)=1 is y=A e^{x/2}. Then A e^{−1}=1 so A=e and y=:",
      ["\\(e^{x/2+1}\\)", "\\(-2e^{x/2}\\)", "\\(e^{x/2}\\)", "\\(2\\cos x-\\sin x\\)"], 0,
      ["y=e · e^{x/2}=e^{x/2+1}. Check y(−2)=e^{0}=1. Wait e^{−2/2+1}=e^{0}=1. Yes."],
      tag="linear-DE-particular"),
    Q("g12-gs-fn-if-03", "inflection", "hard",
      "For f(x)=e^{−2x}−2e^{−x}+1, the inflection point I is at x=ln 2. Then f(ln 2)=:",
      ["\\(\\dfrac{1}{4}\\)", "\\(0\\)", "\\(1\\)", "\\(\\ln 2\\)"], 0,
      ["e^{−2 ln 2}=1/4, e^{−ln 2}=1/2, f=1/4−2·(1/2)+1=1/4−1+1=1/4."], tag="I-ordinates"),
    Q("g12-gs-fn-iv-04", "inverse", "hard",
      "g(x)=ln(f(x))=2 ln|1−e^{−x}|. The equation g(x)=0 on IR\\{0} has the unique solution:",
      ["\\(x=-\\ln 2\\)", "\\(x=\\ln 2\\)", "every x", "\\(x=0\\)"], 0,
      ["|1−e^{−x}|=1 ⇒ e^{−x}=2 (the case e^{−x}=0 is impossible), so x=−ln 2."], tag="g-eq-0"),
    Q("g12-gs-fn-in-05", "integral", "hard",
      "The area between (C), y=1 and x=0 for x≥0 equals ∫_0^∞ (2e^{−x}−e^{−2x}) dx =:",
      ["\\(\\dfrac{3}{2}\\)", "\\(1\\)", "\\(2\\)", "\\(1/2\\)"], 0,
      ["[−2e^{−x}+(1/2)e^{−2x}]_0^∞ = 0 − (−2+1/2)=3/2."], tag="area-3-2"),
    Q("g12-gs-fn-vr-05", "variation", "hard",
      "The period of f(x)=2 sin(π x + 2) is T such that π T = 2π, hence T=:",
      ["\\(2\\)", "\\(\\pi\\)", "\\(2\\pi\\)", "\\(\\pi/2\\)"], 0,
      ["Standard period of sin(ωx+φ) is 2π/|ω|=2π/π=2."], tag="period-sin"),
    Q("g12-gs-fn-lm-06", "limits", "hard",
      "If f(x)=(2/3)√(9−x²) on [−3;3], then f'(x)=0 at:",
      ["\\(x=0\\)", "\\(x=\\pm 3\\)", "\\(x=3\\) only", "no point"], 0,
      ["f'(x)=(2/3)·(1/2)(9−x²)^{−1/2}·(−2x)=−(2x)/(3√(9−x²)), zero at x=0."], tag="ellipse-fprime"),
    Q("g12-gs-fn-de-06", "de", "hard",
      "The equation 2 ln x = ln(2x) has:",
      ["one root only", "2 roots", "no roots", "3 roots"], 0,
      ["x²=2x, x=2 (x=0 excluded)."], tag="2lnx-ln2x"),
    Q("g12-gs-fn-if-04", "inflection", "hard",
      "Let g(x)=ln(f(x)) with f(x)=e^{−2x}(1−e^{x})² and (D): y=−2x. Then g(x)+2x=2 ln|1−e^{x}|, so g(x)=−2x at:",
      ["\\(x=\\ln 2\\)", "\\(x=0\\)", "every x", "no real x"], 0,
      ["|1−e^{x}|=1 ⇒ e^{x}=2 ⇒ x=ln 2. Then g(ln 2)=−2 ln 2, so the curve of g meets (D) at that abscissa."],
      tag="g-eq-minus-2x"),
    Q("g12-gs-fn-iv-05", "inverse", "hard",
      "If f(x)=ln x − 3x, then f'(x) equals:",
      ["\\(\\dfrac{1}{x}-3\\)", "\\(\\dfrac{3}{x}\\)", "\\(-\\dfrac{3}{x}\\)", "\\(\\dfrac{1}{x}\\)"], 0,
      ["Standard."], tag="ln-minus-3x"),
    Q("g12-gs-fn-vr-06", "variation", "medium",
      "On [−3;3], f(x)=(2/3)√(9−x²) attains its maximum at x=0 with f(0)=2 and vanishes at x=±3. The table of variations therefore starts and ends at:",
      ["\\(0\\)", "\\(2\\)", "\\(3\\)", "\\(-3\\)"], 0,
      ["f(±3)=0 at the ends of the domain."], tag="ellipse-ends"),
]

SPACE_SLICES = [
    {"id": "planes", "title": "Planes", "arabicTitle": "المستويات"},
    {"id": "lines", "title": "Lines", "arabicTitle": "المستقيمات"},
    {"id": "orthogonality", "title": "Orthogonality", "arabicTitle": "التعامد"},
    {"id": "distances", "title": "Distances", "arabicTitle": "المسافات"},
    {"id": "figures", "title": "Space figures", "arabicTitle": "الأشكال الفضائية"},
]

GS_SPACE = [
    Q("g12-gs-sg-pl-01", "planes", "easy",
      "In the space referred to a direct orthonormal system (O; i, j, k), a normal to x − y − 2z − 5 = 0 is:",
      ["\\((1;-1;-2)\\)", "\\((1;1;2)\\)", "\\((5;0;0)\\)", "\\((1;-1;2)\\)"], 0,
      ["Coefficients of x, y, z."], tag="normal-P"),
    Q("g12-gs-sg-ln-01", "lines", "easy",
      "A direction of (d): x=t+1, y=−t+2, z=2t is:",
      ["\\((1;-1;2)\\)", "\\((1;2;0)\\)", "\\((1;-1;-2)\\)", "\\((t;t;t)\\)"], 0,
      ["Coefficients of t."], tag="dir-d"),
    Q("g12-gs-sg-or-01", "orthogonality", "easy",
      "(d) of direction (1;−1;2) and the plane x−y−2z−5=0 have V·N equal to:",
      ["\\(-2\\)", "\\(0\\)", "\\(1\\)", "\\(6\\)"], 0,
      ["1·1 + (−1)·(−1) + 2·(−2)=1+1−4=−2. The line is not perpendicular to the plane."], tag="V-dot-N"),
    Q("g12-gs-sg-ds-01", "distances", "easy",
      "The distance from O to the plane x=3 is:",
      ["\\(3\\)", "\\(0\\)", "\\(1\\)", "\\(\\sqrt{3}\\)"], 0,
      ["|0−3|=3."], tag="dist-O-x3"),
    Q("g12-gs-sg-fg-01", "figures", "easy",
      "The midpoint of A(1;−2;1) and B(2;−1;3) is:",
      ["\\((1.5;-1.5;2)\\)", "\\((3;-3;4)\\)", "\\((1;0;2)\\)", "\\((0;0;0)\\)"], 0,
      ["Average of coordinates."], tag="mid-AB"),
    Q("g12-gs-sg-pl-02", "planes", "easy",
      "The plane through A(1;−2;1), B(2;−1;3), C(1;1;4) has a normal AB∧AC. AB=(1;1;2), AC=(0;3;3). Then AB∧AC equals:",
      ["\\((-3;-3;3)\\)", "\\((1;1;2)\\)", "\\((0;0;1)\\)", "\\((3;3;3)\\)"], 0,
      ["i(3−6)−j(3−0)+k(3−0)=(−3;−3;3)."], tag="cross-ABC"),
    Q("g12-gs-sg-ln-02", "lines", "easy",
      "The line x=t, y=t, z=−t+2 passes through H(0;0;2) when t=0. This statement is:",
      ["true", "false because z would be 0", "true only in a non-orthonormal system", "false because x≠y"], 0,
      ["Substitute t=0."], tag="H-on-d"),
    Q("g12-gs-sg-or-02", "orthogonality", "easy",
      "Two lines of directions (2;−2;1) and (1;2;2) are perpendicular because the product of directions is:",
      ["\\(2-4+2=0\\)", "\\(1\\)", "\\(5\\)", "\\(-1\\)"], 0,
      ["2·1 + (−2)·2 + 1·2=2−4+2=0."], tag="lines-perp"),
    Q("g12-gs-sg-ds-02", "distances", "easy",
      "d(A,(P)) for A(1;−2;1) and (P): x+2y−2z−1=0. First |1−4−2−1|=6, √(1+4+4)=3, so the distance is:",
      ["\\(2\\)", "\\(6\\)", "\\(3\\)", "\\(1\\)"], 0,
      ["Wait 1+2(−2)−2(1)−1=1−4−2−1=−6, |−6|/3=2. Need the correct plane. Use x+2y−2z+1? A given as (1,−2,1): 1−4−2−1=-6, /3=2. The plane I wrote is x+2y−2z−1: 1-4-2-1=-6. Yes d=2."],
      tag="d-A-P"),
    Q("g12-gs-sg-fg-02", "figures", "easy",
      "If H is equidistant from A, B and C then HA=HB=HC, so H is the centre of the sphere through A, B, C (and a fourth point if needed). In a GS paper H often is:",
      ["the circumcentre of triangle ABC in its plane, when also on the altitude", "the origin always", "the midpoint of [BC] only", "a point at infinity"], 0,
      ["Equidistance from three non-collinear points: axis of the circumcircle."], tag="equidistant-H"),
    Q("g12-gs-sg-pl-03", "planes", "easy",
      "An equation of the plane through H(0;0;2) perpendicular to (1;1;−1) is:",
      ["\\(x+y-z+2=0\\)", "\\(x+y-z=0\\)", "\\(z=2\\)", "\\(x+y=0\\)"], 0,
      ["1(x−0)+1(y−0)−1(z−2)=0 ⇒ x+y−z+2=0."], tag="plane-at-H"),
    Q("g12-gs-sg-ln-03", "lines", "easy",
      "Parametric equations of the line through E(1;2;0) of direction (1;−1;2) are:",
      ["\\(x=1+t,\\ y=2-t,\\ z=2t\\)", "\\(x=t,\\ y=-t,\\ z=2t\\)", "\\(x=1,\\ y=2,\\ z=0\\)", "\\(x=1-t,\\ y=2+t,\\ z=t\\)"], 0,
      ["Point plus t times direction."], tag="param-E"),
    Q("g12-gs-sg-pl-04", "planes", "medium",
      "An equation of the plane determined by A(1;−2;1), B(2;−1;3) and C(1;1;4) is:",
      ["\\(x+y-z+2=0\\)", "\\(x-y+z=0\\)", "\\(x+y+z=4\\)", "\\(x-y-2z=5\\)"], 0,
      ["Normal (1;1;−1) through A."], tag="plane-ABC-gs"),
    Q("g12-gs-sg-ln-04", "lines", "medium",
      "The line (d): x=t+1, y=−t+2, z=2t meets the plane x−y−2z−5=0 at the point E:",
      ["\\((-2;5;-6)\\)", "\\((1;2;0)\\)", "\\((0;0;0)\\)", "\\((4;-1;6)\\)"], 0,
      ["t=−3: x=−2, y=5, z=−6. Check: −2−5+12−5=0 yes."], tag="E-intersection"),
    Q("g12-gs-sg-or-03", "orthogonality", "medium",
      "The plane (Q) perpendicular to (d) of direction (1;−1;2) at E(−2;5;−6) has equation:",
      ["\\(x-y+2z+19=0\\)", "\\(x-y-2z=5\\)", "\\(x+y+z=0\\)", "\\(z=0\\)"], 0,
      ["Normal = direction of (d): (x+2)−(y−5)+2(z+6)=0 ⇒ x−y+2z+19=0."], tag="Q-perp-d"),
    Q("g12-gs-sg-or-04", "orthogonality", "medium",
      "(d) and (d') given by x=2t+1, y=−2t−1, z=t+2 and x=m, y=2m−3, z=2m intersect at A(1;−1;2) because for t=0 and m=1: (1;−1;2) and (1;−1;2). Their directions (2;−2;1) and (1;2;2) are perpendicular. An equation of the plane they determine is N=(2;−2;1)∧(1;2;2)=:",
      ["\\((-6;-3;6)\\) collinear to \\((2;1;-2)\\)", "\\((1;0;0)\\)", "\\((2;-2;1)\\)", "\\((0;0;1)\\)"], 0,
      ["i(−4−2)−j(4−1)+k(4+2)=(−6;−3;6). Through A: 2(x−1)+1(y+1)−2(z−2)=0 ⇒ 2x+y−2z+1=0? 2x−2 + y+1 −2z+4=0 ⇒ 2x+y−2z+3=0.",
       "The question asks the cross product, answer (−6;−3;6)."], tag="plane-two-lines"),
    Q("g12-gs-sg-ds-03", "distances", "medium",
      "If (d) is perpendicular to (P) at H, then for any M in (P), HM is orthogonal to the direction of (d). Equivalently d(A,(P))=AH when A lies on (d). If A(1;−2;1) and H(0;0;2), AH=:",
      ["\\(\\sqrt{1+4+1}=\\sqrt{6}\\)", "\\(1\\)", "\\(3\\)", "\\(0\\)"], 0,
      ["AH=(−1;2;1), |AH|=√6."], tag="AH-length"),
    Q("g12-gs-sg-ds-04", "distances", "medium",
      "The distance from B(5;2;0) to (P): x+2y−2z+3=0 is |5+4+3|/3=4. To (P'): 2x+y+2z=0 it is |10+2|/3=4. If (P)⟂(P'), d(B, intersection) equals:",
      ["\\(4\\sqrt{2}\\)", "\\(4\\)", "\\(8\\)", "\\(0\\)"], 0,
      ["d²=d1²+d2²=16+16=32, d=4√2."], tag="dist-to-intersection-gs"),
    Q("g12-gs-sg-fg-03", "figures", "medium",
      "E(−1;−1;0) on a bisector (D) in plane (P), circle centred at E tangent to (d) and (d') at T and S. If (d)⟂(d'), quadrilateral ATES with A the intersection of (d),(d') is a:",
      ["square (when ET=ES=AT=AS)", "rhombus that is never a square", "rectangle only", "parallelogram that is never a rhombus"], 0,
      ["Tangents from a point to a circle are equal; with perpendicular lines one gets a square."], tag="ATES-square"),
    Q("g12-gs-sg-ln-05", "lines", "medium",
      "A line (D): x=3λ−1, y=−1, z=3λ in the plane of (d),(d') is a bisector of (d),(d') if a direction of (D) is proportional to u/|u| + v/|v| (unit directions). Here u=(2;−2;1), |u|=3, v=(1;2;2), |v|=3, so u+v=(3;0;3) collinear to (1;0;1), and (D) has direction (3;0;3). This matches. Then E(−1;−1;0) corresponds to λ=0. The statement is:",
      ["true", "false because |u|≠|v|", "false because y is not 0", "true only if λ=1"], 0,
      ["|u|=|v|=3, u+v=(3;0;3)."], tag="bisector-D"),
    Q("g12-gs-sg-pl-05", "planes", "medium",
      "The mediator plane of [AE] with A(1;−1;2) and E(−1;−1;0) has midpoint (0;−1;1) and normal (2;0;2). An equation is:",
      ["\\(x+z-1=0\\)", "\\(x=0\\)", "\\(z=1\\)", "\\(y=-1\\)"], 0,
      ["2(x−0)+2(z−1)=0 ⇒ x+z=1."], tag="mediator-AE"),
    Q("g12-gs-sg-fg-04", "figures", "medium",
      "If (CH) is perpendicular to plane (HAB) and CA=CB, then the interior bisector of angle ACB contains the projection T of H on (ABC) by:",
      ["the property of the altitude and bisector in the isosceles triangle, and the orthogonal projection", "Thales only", "a random coincidence", "Pythagoras alone"], 0,
      ["Classic GS configuration: T ∈ bisector (δ)."], tag="T-on-bisector"),
    Q("g12-gs-sg-ds-05", "distances", "hard",
      "If AB · (AG ∧ GF) ≠ 0, with G,F on a line (d) not through A, then (AB) and (d) are:",
      ["skew (not coplanar)", "parallel", "intersecting", "perpendicular and coplanar"], 0,
      ["A non-zero mixed product of AB with two directions spanning a plane through (d) means AB is not parallel to that plane, hence not coplanar with (d)."],
      tag="skew-mixed-product"),
    Q("g12-gs-sg-or-05", "orthogonality", "hard",
      "The line (D) in (P) perpendicular to (d) at E is the intersection of (P) and the plane through E perpendicular to (d). A direction of (D) is N_P ∧ V_d. For N=(1;−1;−2) and V=(1;−1;2), N∧V=:",
      ["\\((-4;-4;0)\\) collinear to \\((1;1;0)\\)", "\\((1;-1;-2)\\)", "\\((0;0;1)\\)", "\\((1;0;0)\\)"], 0,
      ["i(2−2)−j(2−(−2))+k(−1−(−1))=(0;−4;0)? i[(−1)(2)−(−2)(−1)]=i(−2−2)=−4i. j component: minus |(1,−2);(1,2)|=−(2−(−2))=−4, so −j(−4)? Standard: i(ny vz − nz vy)−j(nx vz−nz vx)+k(nx vy−ny vx).",
       "i((−1)(2)−(−2)(−1))+ … = i(−2−2)=−4i.",
       "−j(1·2−(−2)·1)=−j(2+2)=−4j.",
       "k(1·(−1)−(−1)·1)=k(−1+1)=0.",
       "So (−4;−4;0). Yes."], tag="D-direction"),
    Q("g12-gs-sg-ln-06", "lines", "hard",
      "I(2;1;2) is on (d): x=t+1, y=−t+2, z=2t (t=1). J is the symmetric of I with respect to (D). Then the midpoint of [IJ] lies on (D) and (IJ) ⟂ (D). If (D) has direction (1;1;0) and passes through E(−2;5;−6), this is the classical GS construction of:",
      ["the reflection of I across the line (D)", "the projection of I on (P)", "the inversion of I", "a translation of I"], 0,
      ["Symmetric with respect to a line in space."], tag="symmetric-wrt-D"),
    Q("g12-gs-sg-fg-05", "figures", "hard",
      "Circle in plane (P) with centre E tangent to (d) at T: ET ⟂ (d) and |ET|=distance from E to (d). If |u|=3 and E to (d) is 2, then AT with A on (d) and right angle at T in square ATES equals:",
      ["the radius 2, hence AT=2", "3", "1", "√2"], 0,
      ["In a square the side equals the radius of the circle centred at E tangent at T,S."], tag="AT-radius"),
    Q("g12-gs-sg-pl-06", "planes", "hard",
      "(P): x+2y−2z+3=0 and (P'): 2x+y+2z=0 are perpendicular (N·N'=2+2−4=0). The line (d) of intersection has direction N∧N':",
      ["\\((6;-6;-3)\\) collinear to \\((2;-2;-1)\\)", "\\((1;2;-2)\\)", "\\((2;1;2)\\)", "\\((1;0;0)\\)"], 0,
      ["i(4−(−2))−j(0−(−4))+k(1−4)=(6;−4? wait) i(4+2)=6i. −j(2·0−(−2)·2)=−j(0+4)=−4j. k(1−4)=−3k. So (6;−4;−3)? N=(1,2,−2), N'=(2,1,2).",
       "i(2·2−(−2)·1)=i(4+2)=6.",
       "−j(1·2−(−2)·2)=−j(2+4)=−6j.",
       "k(1·1−2·2)=k(1−4)=−3k.",
       "(6;−6;−3)=3(2;−2;−1). Fix the −4 I first wrote. Good, choice is (6;-6;-3)."], tag="intersect-dir-PP"),
    Q("g12-gs-sg-or-06", "orthogonality", "hard",
      "A(1;1;1) and B(5;2;0) lie on the same side of (P): x+2y−2z+3=0 if the product of the two values of the cartesian form is positive. f(A)=1+2−2+3=4>0, f(B)=5+4+3=12>0, so:",
      ["A and B are on the same side of (P)", "they are on opposite sides", "B∈(P)", "A∈(P)"], 0,
      ["Same sign of the affine form."], tag="same-side"),
    Q("g12-gs-sg-ds-06", "distances", "hard",
      "Let d1=d(B,(P))=4 and d2=d(B,(P'))=4 with (P)⟂(P'). Then d(B,(d))²=d1²+d2²=32, so d(B,(d))=",
      ["\\(4\\sqrt{2}\\)", "\\(4\\)", "\\(\\sqrt{8}\\)", "\\(32\\)"], 0,
      ["Pythagoras in space for two perpendicular planes."], tag="dB-d"),
    Q("g12-gs-sg-pl-07", "planes", "hard",
      "The line of intersection of (P): x+2y−2z+3=0 and (P'): 2x+y+2z=0 passes through the solution of the system with z=0: x+2y=−3, 2x+y=0. Then y=−2, x=1, so a point of the intersection is:",
      ["\\((1;-2;0)\\)", "\\((0;0;0)\\)", "\\((3;0;0)\\)", "\\((0;1;0)\\)"], 0,
      ["z=0 reduces to x+2y=−3 and 2x+y=0 ⇒ x=1, y=−2."], tag="point-on-intersection"),
    Q("g12-gs-sg-ln-07", "lines", "medium",
      "A direction of (d): x=2t+1, y=−2t−1, z=t+2 is (2;−2;1). A direction of (d'): x=m, y=2m−3, z=2m is (1;2;2). These lines are perpendicular because:",
      ["\\(2-4+2=0\\)", "they meet at O", "their constants coincide", "\\(|u|=|v|\\)"], 0,
      ["Dot product of directions: 2·1+(−2)·2+1·2=0."], tag="d-dprime-perp"),
    Q("g12-gs-sg-fg-06", "figures", "hard",
      "The point H(0; 0; 2) belongs to the plane x+y−z+2=0. Then |OH| equals:",
      ["\\(2\\)", "\\(\\sqrt{3}\\)", "\\(1\\)", "\\(0\\)"], 0,
      ["H is on (Oz) and OH=2. (It is not in general the orthogonal projection of O on the plane.)"], tag="OH-length"),
]

PROB_SLICES = [
    {"id": "counting", "title": "Counting", "arabicTitle": "العد"},
    {"id": "conditional", "title": "Conditional probability", "arabicTitle": "الاحتمال الشرطي"},
    {"id": "random_var", "title": "Random variables", "arabicTitle": "المتغيرات العشوائية"},
    {"id": "independence", "title": "Independence", "arabicTitle": "الاستقلال"},
    {"id": "two_stage", "title": "Two-stage experiments", "arabicTitle": "التجارب على مرحلتين"},
]

GS_PROB = [
    Q("g12-gs-pr-ct-01", "counting", "easy",
      "An urn contains 9 balls. Two balls are drawn simultaneously. The number of possible draws is:",
      ["\\(C_9^2=36\\)", "\\(18\\)", "\\(81\\)", "\\(9\\)"], 0,
      ["C(9,2)=36."], tag="C9-2"),
    Q("g12-gs-pr-cd-01", "conditional", "easy",
      "P(A/B)=P(A∩B)/P(B) provided P(B)>0. If P(A∩B)=1/12 and P(B)=1/4, then P(A/B)=:",
      ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{1}{4}\\)", "\\(3\\)"], 0,
      ["(1/12)/(1/4)=1/3."], tag="cond-div"),
    Q("g12-gs-pr-rv-01", "random_var", "easy",
      "A fair coin is tossed 3 times. Let X be the number of heads. Then X follows a binomial law B(3; 1/2) and P(X=0)=:",
      ["\\(\\dfrac{1}{8}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(0\\)"], 0,
      ["(1/2)^3=1/8."], tag="binomial-0"),
    Q("g12-gs-pr-in-01", "independence", "easy",
      "Events A,B are independent iff P(A∩B)=P(A)P(B). If this fails they are:",
      ["not independent", "certain", "impossible", "complementary"], 0,
      ["Definition."], tag="indep-def"),
    Q("g12-gs-pr-ts-01", "two_stage", "easy",
      "Three white, three black, three red balls numbered 1,2,3 each. P(same colour) for two simultaneous draws is:",
      ["\\(\\dfrac{9}{36}=\\dfrac{1}{4}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{3}{9}\\)"], 0,
      ["3×C(3,2)=9, over 36."], tag="same-colour-9"),
    Q("g12-gs-pr-ct-02", "counting", "easy",
      "P(both odd numbers) with 6 odd balls among 9 is:",
      ["\\(\\dfrac{15}{36}\\)", "\\(\\dfrac{6}{9}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{2}{9}\\)"], 0,
      ["C(6,2)/C(9,2)=15/36."], tag="both-odd-gs"),
    Q("g12-gs-pr-cd-02", "conditional", "easy",
      "If P(A)=15/36 and P(B)=9/36 then P(A)P(B)=135/1296. Compared with P(A∩B)=3/36=108/1296, one concludes A and B are:",
      ["not independent", "independent", "equal", "disjoint"], 0,
      ["135≠108."], tag="not-indep-easy"),
    Q("g12-gs-pr-rv-02", "random_var", "easy",
      "E(X)=∑ x_i p_i. If X=0 or 1 with P(X=1)=p, then E(X)=:",
      ["\\(p\\)", "\\(1\\)", "\\(0\\)", "\\(p^2\\)"], 0,
      ["Bernoulli expectation."], tag="bernoulli-E"),
    Q("g12-gs-pr-in-02", "independence", "easy",
      "If A and B are independent, then P(A/B)=:",
      ["\\(P(A)\\)", "\\(P(B)\\)", "\\(1\\)", "\\(0\\)"], 0,
      ["The definition rewritten."], tag="P-A-given-B-indep"),
    Q("g12-gs-pr-ts-02", "two_stage", "easy",
      "A tourist chooses France with probability 0.25 and full-board with probability 0.60 independently. P(France and full-board)=:",
      ["\\(0.15\\)", "\\(0.85\\)", "\\(0.60\\)", "\\(0.25\\)"], 0,
      ["0.25×0.60=0.15."], tag="F-and-B"),
    Q("g12-gs-pr-ct-03", "counting", "easy",
      "C(9,2) equals:",
      ["36", "18", "72", "9"], 0,
      ["9×8/2=36."], tag="C92-num"),
    Q("g12-gs-pr-rv-03", "random_var", "easy",
      "If X takes 1,2,3,4,5 each with probability 2/25 and 0 with probability 3/5, then ∑p_i equals:",
      ["\\(1\\)", "\\(3/5\\)", "\\(2/5\\)", "\\(7/5\\)"], 0,
      ["15/25+10/25=1."], tag="sum-pi"),
    Q("g12-gs-pr-cd-03", "conditional", "medium",
      "P(A∩B)=3/36, P(B)=9/36, so P(A/B)=:",
      ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{4}\\)", "\\(\\dfrac{3}{36}\\)", "\\(1\\)"], 0,
      ["3/9=1/3."], tag="A-given-B"),
    Q("g12-gs-pr-in-03", "independence", "medium",
      "P(C)=P(different colours)=27/36=3/4. P(D)=P(different colours and two odds)=12/36=1/3. Then P(D/C)=:",
      ["\\(\\dfrac{4}{9}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{1}{12}\\)"], 0,
      ["(1/3)/(3/4)=4/9."], tag="D-given-C"),
    Q("g12-gs-pr-rv-04", "random_var", "medium",
      "X∼B(3;1/2). Then P(X=2)=C(3,2)(1/2)^3=:",
      ["\\(\\dfrac{3}{8}\\)", "\\(\\dfrac{1}{8}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{3}{4}\\)"], 0,
      ["3/8."], tag="B3-X2"),
    Q("g12-gs-pr-ts-03", "two_stage", "medium",
      "X is the amount paid with six possible (destination, board) pairs. E(X) is the average receipt per voyager. If the agency serves 200 voyagers, an estimate of the total sum is:",
      ["\\(200\\,E(X)\\)", "\\(E(X)/200\\)", "\\(E(X)\\)", "\\(200\\)"], 0,
      ["Linearity / law of large numbers estimate."], tag="200-EX"),
    Q("g12-gs-pr-ct-04", "counting", "medium",
      "Favourable outcomes for two odd balls of different colours: 12. Total 36. P=:",
      ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{12}{9}\\)"], 0,
      ["12/36=1/3."], tag="P-D"),
    Q("g12-gs-pr-cd-04", "conditional", "medium",
      "P(A∩B)=P(both odd and same colour)=3/36=1/12. P(A)=15/36. Then P(B/A)=:",
      ["\\(\\dfrac{1}{5}\\)", "\\(\\dfrac{1}{4}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{12}\\)"], 0,
      ["(1/12)/(15/36)=(1/12)×(36/15)=3/15=1/5."], tag="B-given-A"),
    Q("g12-gs-pr-rv-05", "random_var", "medium",
      "A die is rolled. X=1 if multiple of 3, else 0. Var(X)=E(X²)−[E(X)]²=p−p² with p=1/3, so Var(X)=:",
      ["\\(\\dfrac{2}{9}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{9}\\)", "\\(1\\)"], 0,
      ["(1/3)(2/3)=2/9."], tag="var-indicator"),
    Q("g12-gs-pr-in-04", "independence", "medium",
      "If A⊂B and P(A)>0, P(B)<1, then P(A∩B)=P(A)≠P(A)P(B), so A and B are:",
      ["not independent", "independent", "disjoint", "equiprobable"], 0,
      ["Unless P(B)=1."], tag="subset-not-indep"),
    Q("g12-gs-pr-ts-04", "two_stage", "medium",
      "Two bills, one from each pocket, independent. P(sum=70 000)=P(20k from right)×P(50k from left)=(3/4)(3/5)=:",
      ["\\(\\dfrac{9}{20}\\)", "\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{3}{5}\\)"], 0,
      ["Product of independent draws."], tag="sum70-gs"),
    Q("g12-gs-pr-ct-05", "counting", "medium",
      "P(two green from 4 green among 7)=C(4,2)/C(7,2)=:",
      ["\\(\\dfrac{2}{7}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{6}{7}\\)", "\\(\\dfrac{1}{2}\\)"], 0,
      ["6/21=2/7."], tag="two-green-gs"),
    Q("g12-gs-pr-rv-06", "random_var", "hard",
      "X∼B(n;p). If n=3, p=1/2, then E(X)=np=:",
      ["\\(\\dfrac{3}{2}\\)", "\\(3\\)", "\\(\\dfrac{1}{2}\\)", "\\(1\\)"], 0,
      ["3/2."], tag="binomial-mean"),
    Q("g12-gs-pr-cd-05", "conditional", "hard",
      "A customer chose full-board (P(B)=0.6). Destinations independent. P(Italy|B)=P(I)=0.35. This uses:",
      ["independence of B and I", "Bayes with unknown P(I|B)≠P(I)", "the fact that Italy is the mode", "P(B|I)=1"], 0,
      ["Independence is the key."], tag="indep-bayes-collapse"),
    Q("g12-gs-pr-in-05", "independence", "hard",
      "P(A)=15/36, P(B)=9/36, P(A)P(B)=135/1296 and P(A∩B)=108/1296. The absolute difference is 27/1296=1/48. Therefore:",
      ["A and B are dependent", "rounding error only", "P(A∩B) was miscomputed as 3/36", "they must be redefined"], 0,
      ["A genuine gap: 3 colours × 1 pair of odd balls =3, not 15×9/36."], tag="dependent-gap"),
    Q("g12-gs-pr-ts-05", "two_stage", "hard",
      "Let X be the voyage price. P(X=1 500 000)=P(F∩ full-board)=0.15. This is one atom of the law of X. The number of distinct values of X is:",
      ["6", "3", "2", "200"], 0,
      ["3 destinations × 2 board types, all prices distinct in the table."], tag="six-values-X"),
    Q("g12-gs-pr-rv-07", "random_var", "hard",
      "Var(X) for X∼B(3;1/2) equals np(1−p)=:",
      ["\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{3}{2}\\)", "\\(\\dfrac{1}{4}\\)", "\\(3\\)"], 0,
      ["3·(1/2)·(1/2)=3/4."], tag="binomial-var"),
    Q("g12-gs-pr-ct-06", "counting", "hard",
      "The number of ways to draw two balls of different colours from 3 white + 3 black + 3 red is C(9,2)−3 C(3,2), which equals:",
      ["\\(27\\)", "\\(36\\)", "\\(9\\)", "\\(6\\)"], 0,
      ["Three unordered colour pairs {W,B},{W,R},{B,R}, each 3×3=9, total 27."], tag="count-diff-colour"),
    Q("g12-gs-pr-cd-06", "conditional", "hard",
      "Two balls drawn have different colours. P(they carry two odd numbers)=4/9 as above. Equivalently this is C(2,1)^3 / 27? Odd per colour: 2. Different colours and both odd: 3 colour-pairs × 2×2=12, over 27: 12/27=4/9. The 12 favourable pairs are:",
      ["the mixed-colour odd-odd pairs", "all 36 pairs", "the 3 same-colour odd pairs", "the even-even pairs"], 0,
      ["12/27=4/9."], tag="interpret-12"),
    Q("g12-gs-pr-ts-06", "two_stage", "hard",
      "A man chooses a pocket with P(R)=2/3 then draws two bills from 4 right-pocket bills (1×100k, 3×20k). P(S∩R) if S is «sum < 90 000» and P(S/R)=C(3,2)/C(4,2)=1/2, equals:",
      ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{2}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{6}\\)"], 0,
      ["(2/3)(1/2)=1/3. Two 20k bills sum to 40k<90k; any draw including the 100k is ≥120k."], tag="S-cap-R"),
]

CX_SLICES = [
    {"id": "algebraic", "title": "Algebraic and exponential form", "arabicTitle": "الشكل الجبري والأسّي"},
    {"id": "geometry", "title": "Geometric interpretation", "arabicTitle": "التفسير الهندسي"},
    {"id": "transform", "title": "Transformations z ↦ z'", "arabicTitle": "التحويلات"},
    {"id": "triangles", "title": "Triangles and similitudes", "arabicTitle": "المثلثات والتشابهات"},
    {"id": "equations", "title": "Equations in C", "arabicTitle": "المعادلات في C"},
]

GS_CX = [
    Q("g12-gs-cx-al-01", "algebraic", "easy",
      "The modulus of z=1+i is:",
      ["\\(\\sqrt{2}\\)", "\\(1\\)", "\\(2\\)", "\\(i\\)"], 0,
      ["√(1+1)=√2."], tag="mod-1i"),
    Q("g12-gs-cx-al-02", "algebraic", "easy",
      "A measure of arg(i) is:",
      ["\\(\\pi/2\\)", "\\(0\\)", "\\(\\pi\\)", "\\(\\pi/4\\)"], 0,
      ["i=e^{iπ/2}."], tag="arg-i-gs"),
    Q("g12-gs-cx-ge-01", "geometry", "easy",
      "If |z−z_E|=5, the point M of affix z describes:",
      ["the circle of centre E and radius 5", "a line", "a point", "the empty set"], 0,
      ["Definition of a circle."], tag="circle-centre-E"),
    Q("g12-gs-cx-tr-01", "transform", "easy",
      "|z'|=|z−a|/|z−b| is the ratio of distances from M to A and to B. If |z'|=1 then M describes:",
      ["the mediator of [AB], deprived of B", "the circle of diameter [AB]", "the line (AB)", "a point"], 0,
      ["|z−a|=|z−b|."], tag="mediator-ratio-1"),
    Q("g12-gs-cx-tr-02", "triangles", "easy",
      "If triangle ABC is right-angled at B, then the complex number (c−b)/(a−b) is:",
      ["pure imaginary", "real", "of modulus 2", "equal to 1"], 0,
      ["arg((c−b)/(a−b))=±π/2."], tag="right-at-B"),
    Q("g12-gs-cx-eq-01", "equations", "easy",
      "The square roots of 1 are:",
      ["\\(1\\) and \\(-1\\)", "\\(i\\) and \\(-i\\)", "\\(1\\) only", "\\(0\\)"], 0,
      ["z²=1."], tag="sqrt-1"),
    Q("g12-gs-cx-al-03", "algebraic", "easy",
      "e^{iπ} equals:",
      ["\\(-1\\)", "\\(1\\)", "\\(i\\)", "\\(0\\)"], 0,
      ["Euler."], tag="e-i-pi"),
    Q("g12-gs-cx-ge-02", "geometry", "easy",
      "The points of affixes 2e^{iθ} for θ real describe:",
      ["the circle of centre O and radius 2", "the line Re z=2", "a spiral", "the origin"], 0,
      ["Modulus constant 2."], tag="circle-r2"),
    Q("g12-gs-cx-tr-03", "transform", "easy",
      "If z'= \\bar z, the map M↦M' is:",
      ["the reflection across (Ox)", "a rotation", "a translation", "a dilation of ratio −1"], 0,
      ["Conjugation."], tag="conjugate-reflect"),
    Q("g12-gs-cx-tr-04", "triangles", "easy",
      "Three points of equal modulus 2 lie on the circle of centre O and radius 2. If also arg((c−a)/(b−a))=π/3 and |b−a|=|c−a|, the triangle is:",
      ["equilateral", "right-angled only", "impossible", "degenerate"], 0,
      ["Equal sides from A and angle π/3."], tag="equilateral-arg"),
    Q("g12-gs-cx-eq-02", "equations", "easy",
      "z^4−z=0 ⇔ z(z³−1)=0. The real solutions are:",
      ["\\(0\\) and \\(1\\)", "\\(0\\) only", "\\(1\\) only", "\\(-1\\) and \\(1\\)"], 0,
      ["z=0 or z³=1 (real cube root 1)."], tag="z4-minus-z"),
    Q("g12-gs-cx-al-04", "algebraic", "easy",
      "If z=2 e^{iπ/3} then Re(z) equals:",
      ["\\(1\\)", "\\(\\sqrt{3}\\)", "\\(2\\)", "\\(0\\)"], 0,
      ["2 cos(π/3)=2·1/2=1."], tag="re-exp"),
    Q("g12-gs-cx-al-05", "algebraic", "medium",
      "z_B−z_A with z_A=1, z_B=3/2 + i √3/2. Then z_B−z_A=1/2 + i √3/2 = e^{iπ/3}. A measure of (u; AB) is:",
      ["\\(\\pi/3\\)", "\\(\\pi/6\\)", "\\(\\pi/2\\)", "\\(0\\)"], 0,
      ["Argument of z_B−z_A."], tag="angle-u-AB"),
    Q("g12-gs-cx-ge-03", "geometry", "medium",
      "B belongs to the circle of centre A and radius 1 because |z_B−z_A|=1. With the previous values |e^{iπ/3}|=1, so:",
      ["B ∈ (C)", "B=A", "B=O", "AB=2"], 0,
      ["Radius 1."], tag="B-on-C"),
    Q("g12-gs-cx-tr-05", "transform", "medium",
      "Let z'=(z−5)/(z−1) with z≠1. If |z'|=1, the point M of affix z describes:",
      ["the mediator of [AB] deprived of A, where A(1) and B(5)", "the circle |z|=1", "the point 5", "the real axis"], 0,
      ["|z−5|=|z−1| ⇒ Re(z)=3, and z≠1."], tag="set-unit-zprime"),
    Q("g12-gs-cx-tr-06", "triangles", "medium",
      "z'=(z_G−z_E)/(z_F−z_E)=e^{iπ/3} and |z_F−z_E|=|z_G−z_E| together prove that triangle EFG is:",
      ["equilateral", "right-angled at E", "isosceles but not equilateral", "of angle π/6 at E"], 0,
      ["Ratio of equal moduli and argument π/3 ⇒ equilateral."], tag="EFG-equilateral"),
    Q("g12-gs-cx-eq-03", "equations", "medium",
      "Square roots of −5+12i: seek (x+iy)²=−5+12i.  x²−y²=−5, 2xy=12 so xy=6. Then (x,y)=(2,3) or (−2,−3), because 4−9=−5. So the square roots are:",
      ["\\(2+3i\\) and \\(-2-3i\\)", "\\(3+2i\\) and \\(-3-2i\\)", "\\(1+i\\)", "\\(12i\\)"], 0,
      ["Verify (2+3i)²=4+12i−9=−5+12i."], tag="sqrt-minus5-12i"),
    Q("g12-gs-cx-al-06", "algebraic", "medium",
      "z= −sin θ + i cos θ = e^{i(π/2+θ)}. This identity holds because i e^{iθ}=:",
      ["\\(-\\sin\\theta+i\\cos\\theta\\)", "\\(\\cos\\theta+i\\sin\\theta\\)", "\\(\\sin\\theta-i\\cos\\theta\\)", "\\(1\\)"], 0,
      ["i(cos θ + i sin θ)= i cos θ − sin θ."], tag="i-exp"),
    Q("g12-gs-cx-ge-04", "geometry", "medium",
      "If |z|=4 and z'=(z−4)/(z+4) with y≠0, then z' is:",
      ["pure imaginary", "real", "of modulus 4", "equal to z"], 0,
      ["M on the circle of diameter? |z|=4 deprived of ±4: the image is the imaginary axis deprived of 0."],
      tag="pure-imag-zprime"),
    Q("g12-gs-cx-eq-04", "equations", "medium",
      "f(z)=z²−(4+5i)z+(7i−1). The roots are the square-root companions after discriminant. If the square roots of −5+12i are ±(2+3i), one can finish the quadratic. The sum of the roots is:",
      ["\\(4+5i\\)", "\\(7i-1\\)", "\\(0\\)", "\\(2+3i\\)"], 0,
      ["Vieta: sum = 4+5i."], tag="vieta-sum"),
    Q("g12-gs-cx-tr-07", "transform", "medium",
      "When M varies on y=x, z=x+ix, then z'=f(z) of a quadratic maps (d) to a parabola (typical GS). The image of a line by z↦z² is generally:",
      ["a parabola (or a degenerate conic)", "always a circle", "always a line", "a single point"], 0,
      ["Classical: z² maps lines not through 0 to parabolas in suitable coordinates."], tag="line-to-parabola"),
    Q("g12-gs-cx-al-07", "algebraic", "hard",
      "If z=x+iy and z'=(z−4)/(z+4) (z≠−4), then Re(z')=0 iff x²+y²=16. So M describes:",
      ["the circle of centre O and radius 4, deprived of A(−4;0)", "the line x=4", "the imaginary axis", "the empty set"], 0,
      ["|z|=4, z≠−4."], tag="set-re-zprime-0"),
    Q("g12-gs-cx-ge-05", "geometry", "hard",
      "Let z=4 e^{iθ} and z_1=4 e^{i 3θ}. Then |z| and |z_1| satisfy:",
      ["\\(|z_1|=|z|=4\\)", "\\(z_1=0\\)", "\\(z=1\\)", "\\(\\theta=0\\)"], 0,
      ["Both moduli equal 4, so N and L lie on the same circle of centre O and radius 4."], tag="same-circle-NL"),
    Q("g12-gs-cx-tr-08", "triangles", "hard",
      "A direct similitude S maps A to B and B to C in a direct equilateral triangle ABC. An angle and the ratio of S are:",
      ["ratio 1 and angle \\(2\\pi/3\\)", "ratio 2 and angle \\(\\pi/2\\)", "ratio 1 and angle 0", "ratio 1/2 and angle \\(\\pi\\)"], 0,
      ["|B−A|=|C−B| so k=1; arg((c−b)/(b−a))=2π/3 for a direct equilateral (exterior). For equilateral direct ABC, arg((b−a)/(c−a))? S(A)=B, S(B)=C so (S(B)−S(A))/(B−A)=(C−B)/(B−A) has argument the angle of S.",
       "In equilateral, (C−B)/(B−A)=e^{i 2π/3} or e^{−i 2π/3} according to orientation. Direct: e^{i 2π/3}."],
      tag="similitude-equilateral"),
    Q("g12-gs-cx-eq-05", "equations", "hard",
      "When M' varies on the y-axis, z' is pure imaginary, and for f(z)=z²−(4+5i)z+7i−1 this constraint on (x,y) is a hyperbola. A hyperbola is the set of points where:",
      ["||MF|-|MF'|| is constant (or a quadratic with xy or x²−y² terms)", "x²+y² is constant", "y=x²", "x=constant"], 0,
      ["GS papers ask nature, asymptotes and vertices after expanding x'=0."], tag="hyperbola-nature"),
    Q("g12-gs-cx-ge-06", "geometry", "hard",
      "If (1−i√3)^n is the conjugate of (1+i√3)^n, then Z=(1+i√3)^n − (1−i√3)^n is:",
      ["pure imaginary (twice i times the imaginary part)", "real", "of modulus 1", "zero"], 0,
      ["z − \\bar z = 2i Im(z)."], tag="z-minus-conj"),
    Q("g12-gs-cx-al-08", "algebraic", "hard",
      "The exponential form of z=−√3 + e^{iπ/6} is e^{i 5π/6}, because z=−√3/2 + i/2. Then |z| equals:",
      ["\\(1\\)", "\\(\\sqrt{3}\\)", "\\(2\\)", "\\(1/2\\)"], 0,
      ["√(3/4+1/4)=1."], tag="mod-after-sum"),
    Q("g12-gs-cx-tr-09", "transform", "hard",
      "If S is a direct similitude of angle π/2, then S∘S is a dilation of:",
      ["negative ratio (homothety of ratio −k²) about the centre of S", "ratio 1 and angle 0", "translation", "identity always"], 0,
      ["h=S∘S has angle π, hence is a homothety of negative ratio."], tag="S-circ-S"),
    Q("g12-gs-cx-eq-06", "equations", "hard",
      "The inverse similitude S^{−1} has complex form obtained by solving z'=az+b for z. If S(z)=ω z with |ω|=1, ω≠1, then S^{−1}(z)=:",
      ["\\(\\bar\\omega z\\)", "\\(\\omega z\\)", "\\(-z\\)", "\\(z+1\\)"], 0,
      ["ω · S^{−1}=Id ⇒ S^{−1}(z)=ω^{−1} z= \\bar ω z on the unit circle."], tag="inverse-similitude"),
    Q("g12-gs-cx-ge-07", "geometry", "medium",
      "The points A, B, C of affixes 2, 2e^{i 2π/3} and 2e^{i 4π/3} are the vertices of:",
      ["an equilateral triangle inscribed in the circle of centre O and radius 2", "a right triangle", "a line", "a square"], 0,
      ["Three cube roots of 8, equally spaced on |z|=2."], tag="cube-roots-triangle"),
    Q("g12-gs-cx-al-09", "algebraic", "hard",
      "If z = 2(cos(π/5) + i sin(π/5)), then z^5 equals:",
      ["\\(-32\\)", "\\(32\\)", "\\(2\\)", "\\(1\\)"], 0,
      ["De Moivre: 2^5 (cos π + i sin π)=32(−1)=−32."], tag="demoivre-z5"),
    Q("g12-gs-cx-tr-10", "transform", "easy",
      "If z' = 2z, the map M↦M' is the dilation of centre O and ratio:",
      ["\\(2\\)", "\\(1/2\\)", "\\(-2\\)", "\\(0\\)"], 0,
      ["Homothety of ratio 2 at the origin."], tag="dilation-2"),
]

MCQ_SLICES = [
    {"id": "complex", "title": "Complex numbers", "arabicTitle": "الأعداد المركبة"},
    {"id": "de", "title": "Differential equations", "arabicTitle": "المعادلات التفاضلية"},
    {"id": "functions", "title": "Functions and logs", "arabicTitle": "الدوال واللوغاريتم"},
    {"id": "space", "title": "Space geometry", "arabicTitle": "هندسة الفضاء"},
    {"id": "probability", "title": "Probability", "arabicTitle": "الاحتمالات"},
]

GS_MCQ = [
    Q("g12-gs-mc-cx-01", "complex", "easy",
      "The exponential form of i is:",
      ["\\(e^{i\\pi/2}\\)", "\\(e^{i\\pi}\\)", "\\(e^{0}\\)", "\\(e^{i\\pi/4}\\)"], 0,
      ["Standard."], tag="i-exp-form"),
    Q("g12-gs-mc-de-01", "de", "easy",
      "The particular solution of y'−y/2=0 with y(−2)=1 is:",
      ["\\(y=e^{x/2+1}\\)", "\\(y=-2e^{x/2}\\)", "\\(y=2\\cos x-\\sin x\\)", "\\(y=x^2-3\\)"], 0,
      ["y=A e^{x/2}, A e^{−1}=1, A=e."], tag="mcq-DE"),
    Q("g12-gs-mc-fn-01", "functions", "easy",
      "The period of f(x)=2 sin(π x + 2) is:",
      ["\\(2\\)", "\\(\\pi\\)", "\\(2\\pi\\)", "\\(\\pi/2\\)"], 0,
      ["2π/π=2."], tag="period-mcq"),
    Q("g12-gs-mc-sp-01", "space", "easy",
      "A normal to x+2y−2z+3=0 is:",
      ["\\((1;2;-2)\\)", "\\((1;2;2)\\)", "\\((3;0;0)\\)", "\\((1;-2;2)\\)"], 0,
      ["Read coefficients."], tag="mcq-normal-gs"),
    Q("g12-gs-mc-pr-01", "probability", "easy",
      "C(9,2) equals:",
      ["36", "18", "72", "9"], 0,
      ["36."], tag="C92-mcq"),
    Q("g12-gs-mc-cx-02", "complex", "easy",
      "|1+i√3| equals:",
      ["\\(2\\)", "\\(1\\)", "\\(\\sqrt{3}\\)", "\\(4\\)"], 0,
      ["√(1+3)=2."], tag="mod-1-isqrt3"),
    Q("g12-gs-mc-fn-02", "functions", "easy",
      "If f(x)=ln x − 3x then f'(x)=:",
      ["\\(1/x-3\\)", "\\(-3/x\\)", "\\(3/x\\)", "\\(1/x\\)"], 0,
      ["Differentiate termwise."], tag="fprime-ln-3x"),
    Q("g12-gs-mc-de-02", "de", "easy",
      "A characteristic equation r²−4r−5=0 has roots:",
      ["\\(5\\) and \\(-1\\)", "\\(4\\) and \\(1\\)", "\\(2\\) and \\(2\\)", "\\(0\\) and \\(4\\)"], 0,
      ["(r−5)(r+1)=0."], tag="r2-4r-5"),
    Q("g12-gs-mc-sp-02", "space", "easy",
      "i · j in a direct orthonormal system equals:",
      ["\\(0\\)", "\\(1\\)", "\\(k\\)", "\\(-1\\)"], 0,
      ["Orthogonal."], tag="idotj-gs"),
    Q("g12-gs-mc-pr-02", "probability", "easy",
      "P(A)+P(Ā)=:",
      ["\\(1\\)", "\\(0\\)", "\\(2\\)", "P(A)"], 0,
      ["Complement."], tag="complement-gs"),
    Q("g12-gs-mc-fn-03", "functions", "easy",
      "e^{½ ln 9 − ln(1/3)} equals:",
      ["\\(9\\)", "\\(e^3\\)", "\\(6\\)", "\\(e^{3/2}\\)"], 0,
      ["½ ln 9 − ln(1/3)= ln 3 + ln 3= ln 9."], tag="exp-ln-simplify"),
    Q("g12-gs-mc-cx-03", "complex", "easy",
      "arg(e^{iθ})=θ (mod 2π). Then arg(e^{−iθ})=:",
      ["\\(-\\theta\\)", "\\(\\theta\\)", "\\(\\pi\\)", "\\(0\\)"], 0,
      ["Conjugate on the unit circle."], tag="arg-minus"),
    Q("g12-gs-mc-cx-04", "complex", "medium",
      "cos²(arccos x) for x in [−1;1] equals:",
      ["\\(x^2\\)", "\\(1+x\\)", "\\(x/2\\)", "\\((1+x)^2\\)"], 0,
      ["cos(arccos x)=x, then square. Official distractors used ½(1+x) from cos(2α)."], tag="cos-arccos"),
    Q("g12-gs-mc-de-03", "de", "medium",
      "The general solution of y''−3y'+2y=0 is y=C1 e^{x}+C2 e^{2x}. A particular solution with y(0)=1, y'(0)=0 is:",
      ["\\(y=2e^{x}-e^{2x}\\)", "\\(y=e^{x}\\)", "\\(y=e^{2x}\\)", "\\(y=0\\)"], 0,
      ["C1+C2=1, C1+2C2=0 ⇒ C1=2, C2=−1."], tag="part-DE-exp"),
    Q("g12-gs-mc-fn-04", "functions", "medium",
      "2 ln x = ln(2x) has:",
      ["one root only", "2 roots", "no roots", "3 roots"], 0,
      ["x=2."], tag="mcq-2ln"),
    Q("g12-gs-mc-sp-03", "space", "medium",
      "Planes x+2y−2z+3=0 and 2x+y+2z=0 are perpendicular because N·N'=:",
      ["\\(0\\)", "\\(1\\)", "\\(4\\)", "\\(-1\\)"], 0,
      ["2+2−4=0."], tag="planes-perp-mcq"),
    Q("g12-gs-mc-pr-03", "probability", "medium",
      "P(same colour) for 3+3+3 balls, two draws, is:",
      ["\\(1/4\\)", "\\(1/3\\)", "\\(1/2\\)", "\\(1\\)"], 0,
      ["9/36=1/4."], tag="p-same-mcq"),
    Q("g12-gs-mc-cx-05", "complex", "medium",
      "If |z|=2 then |z+ i z|=:",
      ["\\(2\\sqrt{2}\\)", "\\(2\\)", "\\(4\\)", "\\(\\sqrt{2}\\)"], 0,
      ["|1+i|·2=2√2."], tag="z-plus-iz-gs"),
    Q("g12-gs-mc-fn-05", "functions", "medium",
      "An antiderivative of ln x is:",
      ["\\(x\\ln x-x\\)", "\\(1/x\\)", "\\((\\ln x)^2/2\\)", "\\(x\\ln x\\)"], 0,
      ["By parts."], tag="F-ln"),
    Q("g12-gs-mc-de-04", "de", "medium",
      "y''+3y'+2y=2, particular constant solution y=:",
      ["\\(1\\)", "\\(2\\)", "\\(0\\)", "\\(-1\\)"], 0,
      ["2y=2."], tag="const-sol"),
    Q("g12-gs-mc-sp-04", "space", "medium",
      "Direction of x=t+1, y=−t+2, z=2t is collinear to (1;−1;2). The line meets x−y−2z−5=0 at t=−3, the point:",
      ["\\((-2;5;-6)\\)", "\\((1;2;0)\\)", "\\((0;1;1)\\)", "\\((4;-1;2)\\)"], 0,
      ["Computed substitution."], tag="meet-mcq"),
    Q("g12-gs-mc-pr-04", "probability", "medium",
      "X∼B(3;1/2), P(X≥1)=1−P(X=0)=:",
      ["\\(7/8\\)", "\\(1/8\\)", "\\(1/2\\)", "\\(3/8\\)"], 0,
      ["1−1/8=7/8."], tag="at-least-one"),
    Q("g12-gs-mc-fn-06", "functions", "medium",
      "cos²(arccos x)=x², not (1+x)/2. The trap (1+x)/2 is:",
      ["cos²(α/2) with x=cos α", "sin x", "1", "x"], 0,
      ["Half-angle formula misapplied."], tag="trap-half-angle"),
    Q("g12-gs-mc-cx-06", "complex", "hard",
      "z=−sin θ + i cos θ equals e^{i(π/2+θ)}. An argument is:",
      ["\\(\\pi/2+\\theta\\)", "\\(\\pi/2-\\theta\\)", "\\(\\theta\\)", "\\(-\\theta\\)"], 0,
      ["As proved by expanding i e^{iθ}."], tag="arg-minus-sin"),
    Q("g12-gs-mc-de-05", "de", "hard",
      "The particular solution of y''−3y'+2y=0 with f(x)=2e^x−e^{2x} is tangent at ln 2 to a line of slope f'(ln 2). f'(x)=2e^x−2e^{2x}, f'(ln 2)=2·2−2·4=4−8=−4. The slope is:",
      ["\\(-4\\)", "\\(0\\)", "\\(2\\)", "\\(1\\)"], 0,
      ["Direct substitution."], tag="slope-ln2"),
    Q("g12-gs-mc-fn-07", "functions", "hard",
      "g(x)=ln(1+√(1−x)) on a suitable interval is an inverse expression in a GS paper. Then g(0)=ln 2. This value is:",
      ["\\(\\ln 2\\)", "\\(0\\)", "\\(1\\)", "\\(e\\)"], 0,
      ["√1=1, ln(2)."], tag="g-of-0"),
    Q("g12-gs-mc-sp-05", "space", "hard",
      "d1=d2=4, perpendicular planes, d to the intersection line is 4√2. Then d² equals:",
      ["32", "16", "8", "4"], 0,
      ["16+16=32."], tag="d2-sum"),
    Q("g12-gs-mc-pr-05", "probability", "hard",
      "P(A∩B)=1/12, P(A)P(B)=(15/36)(9/36)=15/144=5/48, and 1/12=4/48. Independent?",
      ["no", "yes", "cannot decide", "only if A=B"], 0,
      ["4/48 ≠ 5/48."], tag="indep-no"),
    Q("g12-gs-mc-cx-07", "complex", "hard",
      "If Z=(1+i√3)^n − (1−i√3)^n then Z is pure imaginary. The statement «Z is real» is:",
      ["false", "true", "true only for even n", "true only for n=0"], 0,
      ["z−\\bar z is always pure imaginary."], tag="Z-not-real"),
    Q("g12-gs-mc-fn-08", "functions", "hard",
      "f(x)=ln x + x − b on (0;+∞) has f'=1/x+1>0, lim_0 f=−∞, lim_{+∞} f=+∞, so f(x)=0 has:",
      ["a unique positive root", "no root", "two roots", "infinitely many roots"], 0,
      ["Strict increase from −∞ to +∞."], tag="unique-root-ln"),
    Q("g12-gs-mc-de-06", "de", "hard",
      "z=y−1 transforms y''+3y'+2y=2 into z''+3z'+2z=0. This substitution is:",
      ["a shift by the constant particular solution", "a derivation", "a Laplace transform", "illegal"], 0,
      ["Standard reduction of a non-homogeneous linear DE with constant RHS."], tag="shift-z"),
    Q("g12-gs-mc-sp-06", "space", "hard",
      "The mixed product AB·(AG∧GF) ≠ 0 means (AB) and (d) (through G,F) are:",
      ["skew", "parallel", "intersecting", "the same line"], 0,
      ["Non-coplanar."], tag="skew-mcq"),
]


def _style(topic: str) -> str:
    return (
        "Academy-original items patterned on Lebanese Grade 12 GS (علوم عامة) "
        f"official sessions (GS-All.pdf): {topic}. Not photocopies of past papers."
    )


def gs_fn_bank() -> dict:
    return make_bank(
        bank_id="g12-gs-functions",
        track="grade-12",
        certificate="GS",
        topic="functions",
        title="Functions analysis",
        arabic_title="دراسة الدوال",
        models=M,
        style_note=_style("limits, DE, table of variations, area, inverse, inflection"),
        slices=FN_SLICES,
        questions=GS_FN,
        contest_topics=GS_TOPICS,
        contest_minutes=30,
    )


def gs_space_bank() -> dict:
    return make_bank(
        bank_id="g12-gs-space-geometry",
        track="grade-12",
        certificate="GS",
        topic="space_geometry",
        title="Space geometry",
        arabic_title="هندسة الفضاء",
        models=M,
        style_note=_style("orthonormal space, planes, skew lines, distances, space figures"),
        slices=SPACE_SLICES,
        questions=GS_SPACE,
        contest_topics=GS_TOPICS,
    )


def gs_prob_bank() -> dict:
    return make_bank(
        bank_id="g12-gs-probability",
        track="grade-12",
        certificate="GS",
        topic="probability",
        title="Probability",
        arabic_title="الاحتمالات",
        models=M,
        style_note=_style("urns, independence, binomial, two-stage experiments"),
        slices=PROB_SLICES,
        questions=GS_PROB,
        contest_topics=GS_TOPICS,
    )


def gs_cx_bank() -> dict:
    return make_bank(
        bank_id="g12-gs-complex",
        track="grade-12",
        certificate="GS",
        topic="complex",
        title="Complex numbers",
        arabic_title="الأعداد المركبة",
        models=M,
        style_note=_style("exponential form, geometric loci, z↦z', similitudes"),
        slices=CX_SLICES,
        questions=GS_CX,
        contest_topics=GS_TOPICS,
    )


def gs_mcq_bank() -> dict:
    return make_bank(
        bank_id="g12-gs-mcq-mixed",
        track="grade-12",
        certificate="GS",
        topic="mcq_mixed",
        title="Mixed MCQ",
        arabic_title="أسئلة مختلطة",
        models=M,
        style_note=_style("Problem I table — DE, logs, complex, space, probability"),
        slices=MCQ_SLICES,
        questions=GS_MCQ,
        contest_topics=GS_TOPICS,
        contest_minutes=20,
    )
