"""Grade 12 LS remaining banks: space geometry, probability, mixed MCQ."""

from __future__ import annotations

from g12_bank_common import LS_MODELS, LS_TOPICS, item, make_bank

M = LS_MODELS


ERRORS: list[str] = []


def Q(qid, slice_id, difficulty, stem, choices, answer_index, sketch, latex=None, tag=""):
    try:
        return item(qid, slice_id, difficulty, stem, choices, answer_index, sketch, M, latex, tag)
    except Exception as exc:
        ERRORS.append(f"{qid}: {exc}")
        return None


SPACE_SLICES = [
    {"id": "planes", "title": "Planes", "arabicTitle": "المستويات"},
    {"id": "lines", "title": "Lines", "arabicTitle": "المستقيمات"},
    {"id": "orthogonality", "title": "Orthogonality", "arabicTitle": "التعامد"},
    {"id": "distances", "title": "Distances", "arabicTitle": "المسافات"},
    {"id": "figures", "title": "Space figures", "arabicTitle": "الأشكال الفضائية"},
]
SPACE_RANK = {s["id"]: i for i, s in enumerate(SPACE_SLICES)}

LS_SPACE = [
    Q(
        "g12-ls-sg-pl-01",
        "planes",
        "easy",
        "In the space referred to a direct orthonormal system (O; i, j, k), a normal vector to the plane of equation x + 2y − z − 3 = 0 is:",
        ["\\((1;2;-1)\\)", "\\((1;-2;1)\\)", "\\((2;1;1)\\)", "\\((3;0;1)\\)"],
        0,
        [
            "The Cartesian equation ax+by+cz+d=0 has normal (a;b;c).",
            "Trap: swapping signs on the y-component.",
        ],
        latex="(P):\\ x+2y-z-3=0",
        tag="plane-normal",
    ),
    Q(
        "g12-ls-sg-pl-02",
        "planes",
        "easy",
        "The point A(1; 0; 2) belongs to the plane of equation x + y + z − 3 = 0. This statement is:",
        ["true, because 1+0+2−3=0", "false, because 1+0+2=3 ≠ 0", "true only if the system is not orthonormal", "false, because A lies on (Oy)"],
        0,
        ["Substitute: 1+0+2−3=0, so A ∈ (P).", "Trap: forgetting the constant term."],
        tag="point-in-plane",
    ),
    Q(
        "g12-ls-sg-ln-01",
        "lines",
        "easy",
        "A direction vector of the straight line (d) given by x=1+t, y=2−t, z=3+2t (t real) is:",
        ["\\((1;-1;2)\\)", "\\((1;2;3)\\)", "\\((1;1;2)\\)", "\\((t;-t;2t)\\)"],
        0,
        ["The coefficients of the parameter t form a direction vector.", "Trap: taking a point of (d) as a direction."],
        latex="x=1+t,\\ y=2-t,\\ z=3+2t",
        tag="line-direction",
    ),
    Q(
        "g12-ls-sg-or-01",
        "orthogonality",
        "easy",
        "The planes of equations x + y + z = 1 and x − 2y + z = 0 are perpendicular if and only if their normals N and N' satisfy N · N' = 0. Here N · N' equals:",
        ["\\(0\\)", "\\(1\\)", "\\(-1\\)", "\\(2\\)"],
        0,
        ["N=(1;1;1), N'=(1;−2;1), so N·N'=1−2+1=0.", "Trap: requiring the constant terms to match."],
        tag="planes-perp-dot",
    ),
    Q(
        "g12-ls-sg-ds-01",
        "distances",
        "easy",
        "The distance from A(1; 1; 1) to the plane of equation x + y + z − 6 = 0 equals:",
        ["\\(\\sqrt{3}\\)", "\\(1\\)", "\\(3\\)", "\\(\\dfrac{1}{\\sqrt{3}}\\)"],
        0,
        ["d = |1+1+1−6|/√3 = 3/√3 = √3.", "Trap: omitting the square root of a²+b²+c²."],
        latex="d(A,(P))=\\frac{|ax_A+by_A+cz_A+d|}{\\sqrt{a^2+b^2+c^2}}",
        tag="point-plane-dist",
    ),
    Q(
        "g12-ls-sg-fg-01",
        "figures",
        "easy",
        "The midpoint of the segment [AB] with A(2; 0; 4) and B(0; 2; 0) is:",
        ["\\((1;1;2)\\)", "\\((2;2;4)\\)", "\\((1;0;2)\\)", "\\((0;1;2)\\)"],
        0,
        ["I = ((2+0)/2; (0+2)/2; (4+0)/2) = (1;1;2)."],
        tag="midpoint",
    ),
    Q(
        "g12-ls-sg-pl-03",
        "planes",
        "easy",
        "An equation of the plane passing through O and of normal vector (1; 1; 1) is:",
        ["\\(x+y+z=0\\)", "\\(x+y+z=1\\)", "\\(x=y=z\\)", "\\(x+y-z=0\\)"],
        0,
        ["N·OM = 0 for every M in the plane through O, hence x+y+z=0."],
        tag="plane-through-origin",
    ),
    Q(
        "g12-ls-sg-ln-02",
        "lines",
        "easy",
        "A system of parametric equations of the line through A(0; 1; 2) of direction vector (1; 0; −1) is:",
        [
            "\\(x=t,\\ y=1,\\ z=2-t\\)",
            "\\(x=t,\\ y=1+t,\\ z=2-t\\)",
            "\\(x=1,\\ y=t,\\ z=2\\)",
            "\\(x=t,\\ y=0,\\ z=-t\\)",
        ],
        0,
        ["x=0+t, y=1+0·t, z=2−t."],
        tag="parametric-through-point",
    ),
    Q(
        "g12-ls-sg-or-02",
        "orthogonality",
        "easy",
        "The vectors AB=(2; 0; 0) and AC=(0; 2; 0) satisfy AB · AC = 0. Then triangle ABC is:",
        ["right-angled at A", "equilateral", "right-angled at B", "isosceles of vertex B"],
        0,
        ["A vanishing dot product of AB and AC means (AB) ⟂ (AC), so the right angle is at A."],
        tag="right-at-A",
    ),
    Q(
        "g12-ls-sg-ln-03",
        "lines",
        "easy",
        "The line of parametric equations x=t, y=t, z=t is parallel to the plane x + y − 2z = 5 because a direction vector V of the line satisfies:",
        ["\\(V\\cdot N=0\\) where N=(1;1;-2)", "\\(V\\cdot N=1\\)", "the line contains O", "the constant 5 is even"],
        0,
        ["V=(1;1;1), N=(1;1;−2), V·N=1+1−2=0, so (d) ∥ (P) (and O is not in the plane)."],
        tag="line-parallel-plane",
    ),
    Q(
        "g12-ls-sg-ds-02",
        "distances",
        "easy",
        "The distance from A(0; 0; 0) to the plane x = 4 is:",
        ["\\(4\\)", "\\(0\\)", "\\(2\\)", "\\(\\sqrt{4}\\)"],
        0,
        ["The plane x−4=0 is parallel to (yOz); the distance from O is |0−4|=4."],
        tag="coord-plane-dist",
    ),
    Q(
        "g12-ls-sg-fg-02",
        "figures",
        "easy",
        "The points A(2; 0; 0), B(0; 2; 0) and C(0; 0; 2) are the intercepts of the plane x + y + z = 2 with the coordinate axes. Then ABC is:",
        ["equilateral", "right-angled at A", "a line segment", "isosceles of vertex O"],
        0,
        ["AB=AC=BC=√8=2√2, so ABC is equilateral.", "Trap: thinking the right angles of the axes force a right triangle ABC."],
        tag="axis-intercept-triangle",
    ),
    Q(
        "g12-ls-sg-pl-04",
        "planes",
        "medium",
        "An equation of the plane determined by A(1; 0; 0), B(0; 1; 0) and C(0; 0; 1) is:",
        ["\\(x+y+z=1\\)", "\\(x+y+z=0\\)", "\\(x+y+z=3\\)", "\\(xy+yz+zx=1\\)"],
        0,
        ["AB=(−1;1;0), AC=(−1;0;1), AB∧AC=(1;1;1). Through A: 1(x−1)+1(y−0)+1(z−0)=0."],
        tag="plane-three-points",
    ),
    Q(
        "g12-ls-sg-pl-05",
        "planes",
        "medium",
        "The planes (P): x + y + z − 2 = 0 and (Q): x − z − 3 = 0 are perpendicular because:",
        [
            "N_P · N_Q = 0 with N_P=(1;1;1) and N_Q=(1;0;-1)",
            "they share the point (2;0;0)",
            "their constants 2 and 3 are different",
            "N_P is collinear to N_Q",
        ],
        0,
        ["1·1 + 1·0 + 1·(−1)=0, so (P) ⟂ (Q).", "They are distinct; perpendicularity is the vanishing of the normals' product."],
        tag="ls-perp-planes",
    ),
    Q(
        "g12-ls-sg-ln-04",
        "lines",
        "medium",
        "The intersection of the line x=t, y=t, z=t with the plane x + y + z = 3 is the point:",
        ["\\((1;1;1)\\)", "\\((3;0;0)\\)", "\\((0;0;3)\\)", "\\((1;1;0)\\)"],
        0,
        ["3t=3 so t=1, hence M(1;1;1)."],
        tag="line-plane-meet",
    ),
    Q(
        "g12-ls-sg-ln-05",
        "lines",
        "medium",
        "The line (d): x=1+t, y=t, z=1−2t lies in the plane x + y + z − 2 = 0 because:",
        [
            "every point of (d) satisfies the plane equation identically",
            "the direction of (d) is (1;1;1)",
            "the point (1;0;1) is the origin",
            "t must equal 0",
        ],
        0,
        ["(1+t)+t+(1−2t)−2=0 for every t, so (d) ⊂ (P)."],
        tag="line-in-plane",
    ),
    Q(
        "g12-ls-sg-or-03",
        "orthogonality",
        "medium",
        "A direction of the line of intersection of the planes x − y + z = 2 and x + y − z = 0 is:",
        ["\\((0;1;1)\\)", "\\((1;0;0)\\)", "\\((1;1;0)\\)", "\\((1;-1;1)\\)"],
        0,
        ["N1×N2 = |i j k; 1 −1 1; 1 1 −1| = (0;2;2), collinear to (0;1;1)."],
        tag="intersection-direction",
    ),
    Q(
        "g12-ls-sg-or-04",
        "orthogonality",
        "medium",
        "The orthogonal projection of A(1; 2; 3) on the plane x + y + z = 0 is the point H:",
        ["\\((-1;0;1)\\)", "\\((0;0;0)\\)", "\\((1;2;3)\\)", "\\((−1;−2;−3)\\)"],
        0,
        [
            "The perpendicular is A+t(1;1;1)=(1+t;2+t;3+t).",
            "1+t+2+t+3+t=0 ⇒ t=−2, so H=(−1;0;1).",
        ],
        tag="ortho-projection-plane",
    ),
    Q(
        "g12-ls-sg-ds-03",
        "distances",
        "medium",
        "The distance from A(1; 0; −1) to the plane 2x − y + 2z + 3 = 0 equals:",
        ["\\(1\\)", "\\(3\\)", "\\(2\\)", "\\(\\dfrac{3}{2}\\)"],
        0,
        ["|2−0−2+3|/√(4+1+4)=3/3=1."],
        tag="dist-plane-3",
    ),
    Q(
        "g12-ls-sg-ds-04",
        "distances",
        "medium",
        "Let A(2; 1; 0) and (d) be the line through O of direction (1; 0; 0). Then d(A,(d)) equals:",
        ["\\(1\\)", "\\(2\\)", "\\(\\sqrt{5}\\)", "\\(0\\)"],
        0,
        ["AO=(2;1;0), u=(1;0;0), |AO∧u|=|(0;0;−1)|=1, and |u|=1."],
        tag="point-line-axis",
    ),
    Q(
        "g12-ls-sg-fg-03",
        "figures",
        "medium",
        "The area of triangle ABC with A(1; 0; 0), B(0; 1; 0), C(0; 0; 1) equals:",
        ["\\(\\dfrac{\\sqrt{3}}{2}\\)", "\\(\\sqrt{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(1\\)"],
        0,
        ["AB=(−1;1;0), AC=(−1;0;1), AB∧AC=(1;1;1), area = √3 / 2."],
        tag="triangle-area-cross",
    ),
    Q(
        "g12-ls-sg-fg-04",
        "figures",
        "medium",
        "The plane x + y + z = 2 meets the axes at A(2; 0; 0), B(0; 2; 0), C(0; 0; 2). The centre of the circle circumscribed about ABC is:",
        ["\\(\\left(\\dfrac{2}{3};\\dfrac{2}{3};\\dfrac{2}{3}\\right)\\)", "\\((1;1;1)\\)", "\\((0;0;0)\\)", "\\((2;2;2)\\)"],
        0,
        [
            "That centre is the orthogonal projection of O on the plane: (t;t;t) with 3t=2, so t=2/3.",
            "It is equidistant from A, B and C.",
        ],
        tag="circumcentre-axis-triangle",
    ),
    Q(
        "g12-ls-sg-ln-06",
        "lines",
        "medium",
        "A system of parametric equations of the line (BD) with B(0; 2; 3) and D(1; −1; 3) is:",
        [
            "\\(x=s,\\ y=2-3s,\\ z=3\\)",
            "\\(x=s,\\ y=2+s,\\ z=3+s\\)",
            "\\(x=0,\\ y=2+s,\\ z=3s\\)",
            "\\(x=s,\\ y=-3s,\\ z=s\\)",
        ],
        0,
        ["BD=(1;−3;0). From B: x=s, y=2−3s, z=3."],
        tag="parametric-BD",
    ),
    Q(
        "g12-ls-sg-pl-06",
        "planes",
        "medium",
        "The planes x − 2y + z + 1 = 0 and 2x − 4y + 2z − 6 = 0 are:",
        ["distinct and parallel", "perpendicular", "the same plane", "intersecting along (Ox)"],
        0,
        ["Normals are collinear: (2;−4;2)=2(1;−2;1), but 2(+1)≠−6, so distinct parallel planes."],
        tag="parallel-distinct-planes",
    ),
    Q(
        "g12-ls-sg-ds-05",
        "distances",
        "hard",
        "Let (d) pass through A(1; 0; 0) with direction u=(1; 0; 0) and (d') through B(0; 1; 0) with direction v=(0; 0; 1). Then d((d),(d')) equals:",
        ["\\(1\\)", "\\(0\\)", "\\(\\sqrt{2}\\)", "\\(2\\)"],
        0,
        [
            "u∧v=(0;−1;0), AB=(−1;1;0), |AB·(u∧v)| / |u∧v| = 1.",
            "The lines are skew (not coplanar).",
        ],
        tag="skew-distance",
    ),
    Q(
        "g12-ls-sg-ds-06",
        "distances",
        "hard",
        "The distance from A(2; 1; 1) to the line (BC) with B(0; 2; 3) and C(−1; 0; 5) equals:",
        ["\\(\\dfrac{\\sqrt{65}}{3}\\)", "\\(3\\)", "\\(\\sqrt{65}\\)", "\\(\\dfrac{1}{3}\\)"],
        0,
        [
            "BA=(2;−1;−2), BC=(−1;−2;2), BA∧BC=(−6;−2;−5), |BA∧BC|=√65, |BC|=3.",
            "d=√65 / 3.",
        ],
        tag="dist-to-BC",
    ),
    Q(
        "g12-ls-sg-or-05",
        "orthogonality",
        "hard",
        "The foot of the perpendicular from A(2; 3; 1) to the line x=t, y=t, z=t is:",
        ["\\((2;2;2)\\)", "\\((1;1;1)\\)", "\\((2;3;1)\\)", "\\((0;0;0)\\)"],
        0,
        ["H=(t;t;t), (A−H)·(1;1;1)=0 ⇒ 6−3t=0 ⇒ t=2, so H=(2;2;2)."],
        tag="foot-on-diagonal",
    ),
    Q(
        "g12-ls-sg-fg-05",
        "figures",
        "hard",
        "Let M be a variable point of the line (d): x=t−1, y=t+1, z=t+2, and let B(1; 0; −2), C(2; 1; −1). If (d) is parallel to (BC), the area of triangle MBC is:",
        ["independent of the position of M on (d)", "equal to 0 for every M", "maximized only at t=0", "proportional to t²"],
        0,
        [
            "BC=(1;1;1) is a direction of (d), so the height from M to (BC) is constant.",
            "Hence area(MBC)=½ |MB∧BC| is constant.",
        ],
        tag="constant-area",
    ),
    Q(
        "g12-ls-sg-fg-06",
        "figures",
        "hard",
        "The volume of tetrahedron OABC with A(2; 0; 0), B(0; 2; 0), C(0; 0; 2) equals:",
        ["\\(\\dfrac{4}{3}\\)", "\\(8\\)", "\\(4\\)", "\\(\\dfrac{8}{3}\\)"],
        0,
        ["V = (1/6) |OA · (OB∧OC)| = (1/6)·8 = 4/3."],
        tag="tetra-volume",
    ),
    Q(
        "g12-ls-sg-pl-07",
        "planes",
        "hard",
        "An equation of the mediator plane of [AE] with A(3; 1; 0) and E(−1; 1; 2) is:",
        ["\\(2x-z=1\\)", "\\(x+y+z=0\\)", "\\(x-y=0\\)", "\\(2x+z=1\\)"],
        0,
        [
            "Midpoint I=(1;1;1) and AE=(−4;0;2).",
            "−4(x−1)+2(z−1)=0 ⇒ −4x+4+2z−2=0 ⇒ 2x−z=1.",
        ],
        tag="mediator-plane",
    ),
    Q(
        "g12-ls-sg-ln-07",
        "lines",
        "hard",
        "The symmetric of I(2; 1; 2) with respect to the plane x − y − 2z − 5 = 0 is a point J. The midpoint of [IJ] is the intersection of (IJ) with that plane. A direction of (IJ) is:",
        ["\\((1;-1;-2)\\)", "\\((2;1;2)\\)", "\\((1;1;0)\\)", "\\((0;1;-1)\\)"],
        0,
        [
            "The line joining a point to its symmetric with respect to a plane is orthogonal to the plane.",
            "Hence a direction of (IJ) is the normal (1;−1;−2).",
        ],
        tag="symmetric-wrt-plane",
    ),
    Q(
        "g12-ls-sg-or-06",
        "orthogonality",
        "hard",
        "Let (P): x + 2y − 2z + 3 = 0 and (P'): 2x + y + 2z = 0. Then (P) and (P') are perpendicular, and if d1=d(B,(P)), d2=d(B,(P')) for B(5; 2; 0), then d(B, (P)∩(P'))² equals:",
        ["\\(d_1^2+d_2^2\\)", "\\(d_1+d_2\\)", "\\(d_1 d_2\\)", "\\(|d_1-d_2|\\)"],
        0,
        [
            "N·N'=2+2−4=0 so the planes are perpendicular.",
            "The distance to their intersection line satisfies d² = d1² + d2².",
        ],
        tag="dist-to-intersection",
    ),
]

# Fix mediator plane calculation:
# A(1,1,1), E(-1,-1,0)
# Midpoint I = (0, 0, 0.5)
# AE = (-2, -2, -1)
# Plane: -2(x-0) -2(y-0) -1(z-0.5) = 0
# -2x -2y -z + 0.5 = 0
# 2x + 2y + z = 0.5
# Multiply by 2: 4x+4y+2z=1  -- not nice
# Or keep 2x+2y+z = 1/2
#
# Let me change points to get a clean equation.
# A(1,1,1), E(-1,-1,-1): midpoint (0,0,0), AE=(-2,-2,-2), plane x+y+z=0. Too easy.
# A(3,1,0), E(-1,1,2): midpoint (1,1,1), AE=(-4,0,2)=(-2,0,1)
# -2(x-1)+0+(z-1)=0 => -2x+2+z-1=0 => -2x+z+1=0 => 2x - z = 1
#
# I'll fix this in the item after writing - change to a cleaner pair.

PROB_SLICES = [
    {"id": "counting", "title": "Counting", "arabicTitle": "العد"},
    {"id": "conditional", "title": "Conditional probability", "arabicTitle": "الاحتمال الشرطي"},
    {"id": "total_bayes", "title": "Total probability and Bayes", "arabicTitle": "الاحتمال الكلي وبايز"},
    {"id": "random_var", "title": "Random variables", "arabicTitle": "المتغيرات العشوائية"},
    {"id": "two_stage", "title": "Two-stage experiments", "arabicTitle": "التجارب على مرحلتين"},
]

LS_PROB = [
    Q(
        "g12-ls-pr-ct-01",
        "counting",
        "easy",
        "The number of possible groups of 3 children that can be formed from 7 distinct children is:",
        ["\\(C_7^3=35\\)", "\\(7^3=343\\)", "\\(7\\times 6\\times 5=210\\)", "\\(3^7\\)"],
        0,
        ["Unordered groups: C(7,3)=35. Trap: counting arrangements P(7,3)=210."],
        tag="combinations",
    ),
    Q(
        "g12-ls-pr-ct-02",
        "counting",
        "easy",
        "An urn contains 5 distinct balls. The number of ways to draw 2 balls simultaneously is:",
        ["\\(10\\)", "\\(20\\)", "\\(25\\)", "\\(5\\)"],
        0,
        ["C(5,2)=10."],
        tag="urn-simultaneous",
    ),
    Q(
        "g12-ls-pr-cd-01",
        "conditional",
        "easy",
        "If P(M)=0.06 and P(F∩M)=0.051, then P(F/M) equals:",
        ["\\(0.85\\)", "\\(0.051\\)", "\\(0.06\\)", "\\(0.111\\)"],
        0,
        ["P(F/M)=P(F∩M)/P(M)=0.051/0.06=0.85."],
        latex="P(F/M)=\\dfrac{P(F\\cap M)}{P(M)}",
        tag="cond-def",
    ),
    Q(
        "g12-ls-pr-cd-02",
        "conditional",
        "easy",
        "Events A and B are independent with P(A)=1/3 and P(B)=1/2. Then P(A∩B) equals:",
        ["\\(\\dfrac{1}{6}\\)", "\\(\\dfrac{5}{6}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{3}\\)"],
        0,
        ["Independence: P(A∩B)=P(A)P(B)=1/6."],
        tag="independent-product",
    ),
    Q(
        "g12-ls-pr-tb-01",
        "total_bayes",
        "easy",
        "A fair coin is tossed. Then a fair die is rolled only if the coin shows heads. The probability of obtaining both heads and a 6 is:",
        ["\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{1}{6}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{7}{12}\\)"],
        0,
        ["P(H∩6)=P(H)P(6|H)=(1/2)(1/6)=1/12."],
        tag="and-two-steps",
    ),
    Q(
        "g12-ls-pr-rv-01",
        "random_var",
        "easy",
        "A fair coin is tossed twice. Let X be the number of heads. Then P(X=1) equals:",
        ["\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{4}\\)", "\\(\\dfrac{3}{4}\\)", "\\(1\\)"],
        0,
        ["Outcomes HT, TH among {HH,HT,TH,TT}, so 2/4=1/2."],
        tag="two-coins-X",
    ),
    Q(
        "g12-ls-pr-ts-01",
        "two_stage",
        "easy",
        "A bag contains 3 red and 2 blue balls. One ball is drawn at random. The probability that it is red is:",
        ["\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{2}{5}\\)", "\\(\\dfrac{3}{2}\\)", "\\(\\dfrac{1}{5}\\)"],
        0,
        ["Equiprobable: 3/5."],
        tag="simple-urn",
    ),
    Q(
        "g12-ls-pr-ct-03",
        "counting",
        "easy",
        "From a club of 50 students, two representatives are chosen at random. The number of possible choices is:",
        ["\\(C_{50}^2=1225\\)", "\\(50^2=2500\\)", "\\(50\\times 49=2450\\)", "\\(2^{50}\\)"],
        0,
        ["Unordered pairs: C(50,2)=1225. Trap: 50×49 ordered pairs."],
        tag="club-pairs",
    ),
    Q(
        "g12-ls-pr-cd-03",
        "conditional",
        "easy",
        "If P(A)=0.4 and P(B/A)=0.25, then P(A∩B) equals:",
        ["\\(0.1\\)", "\\(0.65\\)", "\\(1.6\\)", "\\(0.15\\)"],
        0,
        ["P(A∩B)=P(A)P(B/A)=0.4×0.25=0.1."],
        tag="product-rule",
    ),
    Q(
        "g12-ls-pr-rv-02",
        "random_var",
        "easy",
        "A discrete random variable X takes the values 0 and 1 with P(X=0)=2/5. Then P(X=1) equals:",
        ["\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{2}{5}\\)", "\\(1\\)", "\\(\\dfrac{1}{5}\\)"],
        0,
        ["The probabilities sum to 1."],
        tag="two-value-X",
    ),
    Q(
        "g12-ls-pr-tb-02",
        "total_bayes",
        "easy",
        "P(R)=2/3, P(L)=1/3 and P(S/R)=1/2. Then P(S∩R) equals:",
        ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{2}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{6}\\)"],
        0,
        ["P(S∩R)=P(R)P(S/R)=(2/3)(1/2)=1/3."],
        tag="intersection-from-cond",
    ),
    Q(
        "g12-ls-pr-ts-02",
        "two_stage",
        "easy",
        "Two families are chosen with equal probability; then one child is chosen at random from the chosen family. Family F2 has 1 girl among 3 children. The probability of the event A: «the chosen child is a girl of F2» is:",
        ["\\(\\dfrac{1}{6}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{4}\\)"],
        0,
        ["P(A)=P(F2)×(1/3)=(1/2)×(1/3)=1/6."],
        tag="girl-of-F2",
    ),
    Q(
        "g12-ls-pr-ct-04",
        "counting",
        "medium",
        "A family has 4 children (2 girls, 2 boys) and another has 3 children (1 girl, 2 boys). The probability of having exactly one girl among 3 children chosen at random from these 7 is:",
        ["\\(\\dfrac{18}{35}\\)", "\\(\\dfrac{3}{7}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{12}{35}\\)"],
        0,
        [
            "3 girls and 4 boys in all. Favourable: C(3,1)C(4,2)=3×6=18, total C(7,3)=35.",
        ],
        tag="exactly-one-girl",
    ),
    Q(
        "g12-ls-pr-cd-04",
        "conditional",
        "medium",
        "A club has 20 boys and 10 girls in the 1st secondary year, and 12 boys and 8 girls in the 2nd. A student is chosen at random. P(the student is a boy | 2nd year) equals:",
        ["\\(0.60\\)", "\\(0.64\\)", "\\(0.50\\)", "\\(0.24\\)"],
        0,
        ["12 boys among 20 students of the 2nd year: 12/20=0.60."],
        tag="club-cond",
    ),
    Q(
        "g12-ls-pr-tb-03",
        "total_bayes",
        "medium",
        "A man has in his right pocket 1 bill of 100 000 LL and 3 bills of 20 000 LL. He draws one bill at random from that pocket. The probability that the bill is 20 000 LL is:",
        ["\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{1}{4}\\)", "\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{1}{2}\\)"],
        0,
        ["4 bills, 3 of them 20 000 LL."],
        tag="right-pocket",
    ),
    Q(
        "g12-ls-pr-tb-04",
        "total_bayes",
        "medium",
        "Given P(M)=0.06, P(F)=0.4 and P(F/M)=0.85, then P(M/F) equals:",
        ["\\(0.1275\\)", "\\(0.051\\)", "\\(0.85\\)", "\\(0.34\\)"],
        0,
        ["P(M∩F)=0.06×0.85=0.051, P(M/F)=0.051/0.4=0.1275."],
        tag="bayes-M-given-F",
    ),
    Q(
        "g12-ls-pr-rv-03",
        "random_var",
        "medium",
        "Two balls are drawn simultaneously from an urn of 5 balls numbered 0,0,0,1,2. Let X be the product of the two numbers. Then P(X=0) equals:",
        ["\\(\\dfrac{9}{10}\\)", "\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{3}{10}\\)"],
        0,
        [
            "Total C(5,2)=10. Product 0 iff at least one 0: C(3,2)+C(3,1)C(2,1)=3+6=9, so 9/10.",
            "Trap: drawing with replacement 3/5.",
        ],
        tag="product-zero",
    ),
    Q(
        "g12-ls-pr-rv-04",
        "random_var",
        "medium",
        "A fair die is rolled. Let X be 1 if the face is a multiple of 3, and 0 otherwise. Then E(X) equals:",
        ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(1\\)", "\\(\\dfrac{2}{3}\\)"],
        0,
        ["P(X=1)=P({3,6})=1/3, so E(X)=1/3."],
        tag="indicator-expectation",
    ),
    Q(
        "g12-ls-pr-ts-03",
        "two_stage",
        "medium",
        "He draws at random one bill from a right pocket (1×100 000 and 3×20 000) and one from a left pocket (3×50 000 and 2×20 000). P(the sum equals 70 000 LL) is:",
        ["\\(\\dfrac{9}{20}\\)", "\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{6}{20}\\)"],
        0,
        [
            "70 000 = 20 000 + 50 000. P=(3/4)×(3/5)=9/20.",
        ],
        tag="sum-70000",
    ),
    Q(
        "g12-ls-pr-ct-05",
        "counting",
        "medium",
        "Two students are chosen from 32 boys and 18 girls. The probability that both are boys is:",
        ["\\(\\dfrac{C_{32}^2}{C_{50}^2}\\)", "\\(\\left(\\dfrac{32}{50}\\right)^2\\)", "\\(\\dfrac{32}{50}\\times\\dfrac{32}{49}\\)", "\\(\\dfrac{2}{50}\\)"],
        0,
        ["Without replacement, unordered: C(32,2)/C(50,2). Trap: with-replacement square."],
        tag="two-boys",
    ),
    Q(
        "g12-ls-pr-cd-05",
        "conditional",
        "medium",
        "Among 32 boys, 20 are in the 1st year. Two boys are chosen at random. The probability they are both in the 1st year, knowing that both are boys, is:",
        ["\\(\\dfrac{C_{20}^2}{C_{32}^2}\\)", "\\(\\dfrac{20}{32}\\)", "\\(\\dfrac{C_{20}^2}{C_{50}^2}\\)", "\\(\\dfrac{20\\times 19}{50\\times 49}\\)"],
        0,
        ["Conditioned on both being boys, the sample space is the 32 boys: C(20,2)/C(32,2)."],
        tag="both-first-given-boys",
    ),
    Q(
        "g12-ls-pr-tb-05",
        "total_bayes",
        "medium",
        "P(R)=2/3, P(L)=1/3, P(S/R)=1/2, P(S/L)=1/5. Then P(S) equals:",
        ["\\(\\dfrac{2}{5}\\)", "\\(\\dfrac{7}{15}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{11}{30}\\)"],
        0,
        ["P(S)=(2/3)(1/2)+(1/3)(1/5)=1/3+1/15=2/5."],
        tag="total-S",
    ),
    Q(
        "g12-ls-pr-rv-05",
        "random_var",
        "medium",
        "Let X be the number of girls among 3 children chosen from 3 girls and 4 boys. The possible values of X are:",
        ["\\(0,1,2,3\\)", "\\(1,2,3\\)", "\\(0,1,2\\)", "\\(3\\) only"],
        0,
        ["There are 3 girls and 4 boys, so X can be 0,1,2 or 3."],
        tag="support-of-X",
    ),
    Q(
        "g12-ls-pr-ts-04",
        "two_stage",
        "medium",
        "A pocket is chosen with P(R)=2/3, then two bills are drawn from the right pocket of 4 bills (1 of 100 000 and 3 of 20 000). P(the two bills are both 20 000 LL | R) equals:",
        ["\\(\\dfrac{C_3^2}{C_4^2}=\\dfrac{1}{2}\\)", "\\(\\dfrac{3}{4}\\)", "\\(\\left(\\dfrac{3}{4}\\right)^2\\)", "\\(\\dfrac{1}{4}\\)"],
        0,
        ["C(3,2)/C(4,2)=3/6=1/2."],
        tag="two-small-bills",
    ),
    Q(
        "g12-ls-pr-rv-06",
        "random_var",
        "hard",
        "From 7 children (3 girls, 4 boys) a group of 3 is chosen at random. Let X be the number of girls. Then P(X=2) equals:",
        ["\\(\\dfrac{12}{35}\\)", "\\(\\dfrac{4}{35}\\)", "\\(\\dfrac{18}{35}\\)", "\\(\\dfrac{1}{7}\\)"],
        0,
        [
            "P(X=2)=C(3,2)C(4,1)/C(7,3)=12/35.",
            "Trap: 18/35 is P(X=1).",
        ],
        tag="P-X-2",
    ),
    Q(
        "g12-ls-pr-tb-06",
        "total_bayes",
        "hard",
        "A customer chooses France, Italy or Turkey with probabilities 0.25, 0.35 and 0.40. Independently, 60% choose full-board. Then P(full-board ∩ Italy) equals:",
        ["\\(0.21\\)", "\\(0.35\\)", "\\(0.60\\)", "\\(0.145\\)"],
        0,
        ["P(B∩I)=0.35×0.60=0.21."],
        tag="voyage-intersection",
    ),
    Q(
        "g12-ls-pr-cd-06",
        "conditional",
        "hard",
        "With P(F)=0.25, P(I)=0.35, P(T)=0.40 and P(B|destination)=0.60 for each destination, the probability that a full-board customer chose Italy is:",
        ["\\(0.35\\)", "\\(0.21\\)", "\\(0.60\\)", "\\(0.145\\)"],
        0,
        [
            "P(B)=0.60, P(I/B)=P(B∩I)/P(B)=0.21/0.60=0.35.",
            "Because B is independent of the destination, P(I/B)=P(I).",
        ],
        tag="italy-given-fullboard",
    ),
    Q(
        "g12-ls-pr-ts-05",
        "two_stage",
        "hard",
        "Two balls are drawn simultaneously from 9 balls (3 white, 3 black, 3 red numbered 1,2,3 in each colour). Let A: «both numbers odd» and B: «same colour». Then P(A∩B) equals:",
        ["\\(\\dfrac{1}{12}\\)", "\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{C_3^2}{C_9^2}\\)", "\\(\\dfrac{1}{4}\\)"],
        0,
        [
            "Each colour has two odd-numbered balls. A∩B: the two odd balls of one colour, 3 colours.",
            "Favourable 3, total C(9,2)=36, so 3/36=1/12.",
            "Trap: 1/4 is P(same colour).",
        ],
        tag="odd-same-colour",
    ),
    Q(
        "g12-ls-pr-rv-07",
        "random_var",
        "hard",
        "A bag contains one red ball numbered n, two yellow balls numbered −5 and four green balls numbered 4. Two balls are drawn simultaneously. The probability of drawing one red and one green is:",
        ["\\(\\dfrac{4}{21}\\)", "\\(\\dfrac{8}{21}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{1}{7}\\)"],
        0,
        ["C(1,1)C(4,1)/C(7,2)=4/21."],
        tag="red-and-green",
    ),
    Q(
        "g12-ls-pr-ct-06",
        "counting",
        "hard",
        "Two balls from 7 (1 red, 2 yellow, 4 green). The probability they have the same colour is:",
        ["\\(\\dfrac{C_2^2+C_4^2}{C_7^2}=\\dfrac{7}{21}\\)", "\\(\\dfrac{C_2^2+C_4^2+C_1^2}{C_7^2}\\)", "\\(\\dfrac{4}{7}\\)", "\\(\\dfrac{2}{7}\\)"],
        0,
        [
            "Same colour: two yellow C(2,2)=1 or two green C(4,2)=6; red cannot pair with itself. Total 7/21=1/3.",
            "C(1,2) is 0, not 1.",
        ],
        tag="same-colour-7",
    ),
    Q(
        "g12-ls-pr-tb-07",
        "total_bayes",
        "hard",
        "A family is chosen at random from F1 (2 girls, 2 boys) and F2 (1 girl, 2 boys), then one child at random. Let C: «girl» and D: «from F1 knowing the child is a girl». Then P(D)=P(F1/C) equals:",
        ["\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{2}{3}\\)", "\\(\\dfrac{1}{3}\\)"],
        0,
        [
            "P(C∩F1)=(1/2)(2/4)=1/4, P(C∩F2)=(1/2)(1/3)=1/6, P(C)=1/4+1/6=5/12.",
            "P(F1/C)=(1/4)/(5/12)=3/5.",
        ],
        tag="F1-given-girl",
    ),
    Q(
        "g12-ls-pr-ts-06",
        "two_stage",
        "hard",
        "X is the sum drawn from one right-pocket bill (values 100 000 or 20 000 with probs 1/4, 3/4) and one left-pocket bill (50 000 or 20 000 with probs 3/5, 2/5). Then P(X < 100 000) equals:",
        ["\\(\\dfrac{3}{4}\\)", "\\(\\dfrac{17}{20}\\)", "\\(\\dfrac{9}{20}\\)", "\\(\\dfrac{1}{2}\\)"],
        0,
        [
            "Possible sums: 150000 (1/4)(3/5)=3/20; 120000 (1/4)(2/5)=2/20; 70000 (3/4)(3/5)=9/20; 40000 (3/4)(2/5)=6/20.",
            "X<100000: 70000 and 40000, probability 9/20+6/20=15/20=3/4.",
        ],
        tag="P-X-lt-100000",
    ),
]

MCQ_SLICES = [
    {"id": "complex", "title": "Complex numbers", "arabicTitle": "الأعداد المركبة"},
    {"id": "limits", "title": "Limits and calculus", "arabicTitle": "النهايات والحساب"},
    {"id": "space", "title": "Space geometry", "arabicTitle": "هندسة الفضاء"},
    {"id": "probability", "title": "Probability", "arabicTitle": "الاحتمالات"},
    {"id": "functions", "title": "Functions", "arabicTitle": "الدوال"},
]

LS_MCQ = [
    Q(
        "g12-ls-mc-cx-01",
        "complex",
        "easy",
        "In the table of mixed items of a typical LS paper, only one answer is correct. If z = e^{i π/6}, then z^6 equals:",
        ["\\(-1\\)", "\\(1\\)", "\\(i\\)", "\\(-i\\)"],
        0,
        ["z^6 = e^{iπ} = −1. Trap: confusing with z^3 = i."],
        latex="z=e^{i\\pi/6}",
        tag="exp-power",
    ),
    Q(
        "g12-ls-mc-cx-02",
        "complex",
        "easy",
        "If z = 2 e^{i π/3}, then |z| equals:",
        ["\\(2\\)", "\\(\\dfrac{\\pi}{3}\\)", "\\(2e\\)", "\\(1\\)"],
        0,
        ["The modulus of re^{iθ} is r (r>0)."],
        tag="modulus-exp",
    ),
    Q(
        "g12-ls-mc-lm-01",
        "limits",
        "easy",
        "Let f(x)=e^{x}/x for x>0. Then lim_{x→+∞} f(x) equals:",
        ["\\(+\\infty\\)", "\\(0\\)", "\\(1\\)", "\\(e\\)"],
        0,
        ["The exponential grows faster than x."],
        tag="exp-over-x",
    ),
    Q(
        "g12-ls-mc-sp-01",
        "space",
        "easy",
        "A normal vector to the plane x − 2y + z + 1 = 0 is:",
        ["\\((1;-2;1)\\)", "\\((1;2;1)\\)", "\\((1;-2;-1)\\)", "\\((0;0;1)\\)"],
        0,
        ["Read the coefficients of x, y, z."],
        tag="mcq-normal",
    ),
    Q(
        "g12-ls-mc-pr-01",
        "probability",
        "easy",
        "A fair die is rolled. The probability of obtaining a multiple of 3 is:",
        ["\\(\\dfrac{1}{3}\\)", "\\(\\dfrac{1}{2}\\)", "\\(\\dfrac{1}{6}\\)", "\\(\\dfrac{2}{3}\\)"],
        0,
        ["Faces 3 and 6: 2/6=1/3."],
        tag="die-multiple-3",
    ),
    Q(
        "g12-ls-mc-fn-01",
        "functions",
        "easy",
        "If f(x)=ln x on (0,+∞), then f'(x) equals:",
        ["\\(\\dfrac{1}{x}\\)", "\\(\\ln x\\)", "\\(x\\)", "\\(\\dfrac{1}{\\ln x}\\)"],
        0,
        ["Standard derivative of ln."],
        tag="ln-derivative",
    ),
    Q(
        "g12-ls-mc-cx-03",
        "complex",
        "easy",
        "If z = 1 + i, then |z| equals:",
        ["\\(\\sqrt{2}\\)", "\\(1\\)", "\\(2\\)", "\\(i\\)"],
        0,
        ["|1+i|=√(1+1)=√2."],
        tag="mod-1-plus-i",
    ),
    Q(
        "g12-ls-mc-lm-02",
        "limits",
        "easy",
        "lim_{x→0} (sin x)/x equals:",
        ["\\(1\\)", "\\(0\\)", "\\(+\\infty\\)", "\\(x\\)"],
        0,
        ["Standard limit."],
        tag="sinx-over-x",
    ),
    Q(
        "g12-ls-mc-sp-02",
        "space",
        "easy",
        "The vectors i and j of a direct orthonormal system satisfy i · j =",
        ["\\(0\\)", "\\(1\\)", "\\(-1\\)", "\\(k\\)"],
        0,
        ["Distinct basis vectors of an orthonormal system are orthogonal."],
        tag="i-dot-j",
    ),
    Q(
        "g12-ls-mc-pr-02",
        "probability",
        "easy",
        "If P(A)=0.3 then P(Ā) equals:",
        ["\\(0.7\\)", "\\(0.3\\)", "\\(1.3\\)", "\\(0\\)"],
        0,
        ["Complement: 1−0.3=0.7."],
        tag="complement",
    ),
    Q(
        "g12-ls-mc-fn-02",
        "functions",
        "easy",
        "An antiderivative of 2x on IR is:",
        ["\\(x^2\\)", "\\(2\\)", "\\(2x^2\\)", "\\(x^2+2x\\)"],
        0,
        ["(x²)'=2x. Any antiderivative differs by a constant; among the choices, x² works."],
        tag="antideriv-2x",
    ),
    Q(
        "g12-ls-mc-cx-04",
        "complex",
        "easy",
        "A measure of an argument of i is:",
        ["\\(\\dfrac{\\pi}{2}\\)", "\\(0\\)", "\\(\\pi\\)", "\\(\\dfrac{\\pi}{4}\\)"],
        0,
        ["i = e^{iπ/2}."],
        tag="arg-i",
    ),
    Q(
        "g12-ls-mc-cx-05",
        "complex",
        "medium",
        "If π/6 is an argument of z, then an argument of 2/z is:",
        ["\\(-\\dfrac{\\pi}{6}\\)", "\\(\\dfrac{\\pi}{6}\\)", "\\(\\dfrac{5\\pi}{6}\\)", "\\(-\\dfrac{5\\pi}{6}\\)"],
        0,
        ["arg(2/z)=arg(2)−arg(z)=0−π/6=−π/6. The factor 2 does not change the argument."],
        tag="arg-of-2-over-z",
    ),
    Q(
        "g12-ls-mc-cx-06",
        "complex",
        "medium",
        "Let z = sin(π/3) − i cos(π/3). Then z equals:",
        [
            "\\(e^{-i\\pi/6}\\)",
            "\\(e^{i\\pi/6}\\)",
            "\\(e^{i\\pi/3}\\)",
            "\\(e^{-i\\pi/3}\\)",
        ],
        0,
        [
            "sin(π/3)=√3/2, cos(π/3)=1/2, so z=√3/2 − i/2 = e^{-iπ/6}.",
            "Trap: writing e^{iπ/6} which is √3/2 + i/2.",
        ],
        tag="sin-minus-i-cos",
    ),
    Q(
        "g12-ls-mc-lm-03",
        "limits",
        "medium",
        "Let f(x)=e^{e^x / x}. Then lim_{x→+∞} f(x) equals:",
        ["\\(+\\infty\\)", "\\(1\\)", "\\(0\\)", "\\(e\\)"],
        0,
        ["e^x / x → +∞, so exp of that → +∞."],
        tag="tower-exp",
    ),
    Q(
        "g12-ls-mc-lm-04",
        "limits",
        "medium",
        "I = ∫_{−π/2}^{π/2} (sin³ x + 1) dx equals:",
        ["\\(\\pi\\)", "\\(0\\)", "\\(1\\)", "\\(\\dfrac{\\pi}{2}\\)"],
        0,
        ["sin³ x is odd, the interval is symmetric, ∫sin³=0, ∫1 dx = π."],
        tag="odd-plus-one-integral",
    ),
    Q(
        "g12-ls-mc-sp-03",
        "space",
        "medium",
        "The line x=t−1, y=t+1, z=t+2 has direction collinear to BC with B(1;0;−2) and C(2;1;−1). This statement is:",
        ["true, because BC=(1;1;1)", "false, because BC=(1;−1;1)", "true only for t=0", "false because (d) does not contain B"],
        0,
        ["Direction of (d) is (1;1;1)=BC."],
        tag="dir-collinear-BC",
    ),
    Q(
        "g12-ls-mc-pr-03",
        "probability",
        "medium",
        "C(10,2) equals:",
        ["\\(45\\)", "\\(90\\)", "\\(10\\)", "\\(20\\)"],
        0,
        ["10×9/2=45."],
        tag="C-10-2",
    ),
    Q(
        "g12-ls-mc-fn-03",
        "functions",
        "medium",
        "lim_{x→0+} x ln x equals:",
        ["\\(0\\)", "\\(-\\infty\\)", "\\(1\\)", "\\(+\\infty\\)"],
        0,
        ["Standard: x ln x → 0 (the power x wins). Trap: −∞ from ln x."],
        tag="x-ln-x",
    ),
    Q(
        "g12-ls-mc-fn-04",
        "functions",
        "medium",
        "If f(x)=(ln x)/x on (0,+∞), then lim_{x→+∞} f(x) equals:",
        ["\\(0\\)", "\\(+\\infty\\)", "\\(1\\)", "\\(-\\infty\\)"],
        0,
        ["ln x grows slower than x."],
        tag="ln-over-x",
    ),
    Q(
        "g12-ls-mc-cx-07",
        "complex",
        "medium",
        "If |z|=2 then |z + i z| equals:",
        ["\\(2\\sqrt{2}\\)", "\\(2\\)", "\\(4\\)", "\\(\\sqrt{2}\\)"],
        0,
        ["z+iz=z(1+i), |1+i|=√2, so |z||1+i|=2√2."],
        tag="z-plus-iz",
    ),
    Q(
        "g12-ls-mc-sp-04",
        "space",
        "medium",
        "If N(1;−2;1) is normal to (P) and N'(1;0;−1) is normal to (Q), then (P) ⟂ (Q) because:",
        ["\\(N\\cdot N'=0\\)", "\\(N\\wedge N'=0\\)", "N is collinear to N'", "both planes contain O"],
        0,
        ["1+0−1=0."],
        tag="N-dot-N-prime",
    ),
    Q(
        "g12-ls-mc-pr-04",
        "probability",
        "medium",
        "Two balls from 5, with replacement. The number of possible ordered draws is:",
        ["\\(25\\)", "\\(20\\)", "\\(10\\)", "\\(5\\)"],
        0,
        ["5×5=25. Trap: C(5,2) without replacement."],
        tag="with-replacement",
    ),
    Q(
        "g12-ls-mc-lm-05",
        "limits",
        "medium",
        "lim_{x→0} [∫_0^x ln(t+1) dt] / (e^x − 1) equals:",
        ["\\(0\\)", "\\(1\\)", "\\(+\\infty\\)", "\\(-1\\)"],
        0,
        [
            "0/0 form. By l'Hospital: ln(x+1)/e^x → 0/1 = 0.",
        ],
        tag="integral-limit-0",
    ),
    Q(
        "g12-ls-mc-cx-08",
        "complex",
        "hard",
        "Let z_A=1−2i, z_B=2+3i, z_C=4. Then triangle ABC is:",
        ["right and isosceles", "right and not isosceles", "isosceles and not right", "equilateral"],
        0,
        [
            "AB=|1+5i|=√26, AC=|3+2i|=√13, BC=|2−3i|=√13.",
            "AC=BC (isosceles at C) and AB²=AC²+BC² (right-angled at C).",
        ],
        tag="triangle-ABC-affixes",
    ),
    Q(
        "g12-ls-mc-fn-05",
        "functions",
        "hard",
        "An antiderivative of cos² x is, up to a constant:",
        ["\\(\\dfrac{x}{2}+\\dfrac{\\sin 2x}{4}\\)", "\\(\\dfrac{\\cos 3x}{3}\\)", "\\(\\sin^2 x\\)", "\\(\\dfrac{x\\sin 2x}{2}\\)"],
        0,
        ["cos² x = (1+cos 2x)/2, antiderivative x/2 + (sin 2x)/4."],
        tag="antideriv-cos-sq",
    ),
    Q(
        "g12-ls-mc-cx-09",
        "complex",
        "hard",
        "If z = −√3 + e^{i π/6}, the exponential form of z is:",
        [
            "\\(e^{i 5\\pi/6}\\)",
            "\\(e^{i 7\\pi/6}\\)",
            "\\(\\sqrt{3}\\, e^{-i \\pi/6}\\)",
            "\\(e^{-i 5\\pi/6}\\)",
        ],
        0,
        [
            "e^{iπ/6}=√3/2 + i/2, so z= −√3 + √3/2 + i/2 = −√3/2 + i/2 = e^{i 5π/6}.",
        ],
        tag="minus-sqrt3-plus-exp",
    ),
    Q(
        "g12-ls-mc-sp-05",
        "space",
        "hard",
        "Let (P): x−2y+z+1=0 and (Q): x−z−3=0. A(2; −2; −1) belongs to (Q), and (P) ⟂ (Q). If (BC) is the line of intersection of (P) and (Q), then d(A,(BC)) equals:",
        ["\\(d(A,(P))\\)", "\\(0\\)", "\\(d(A,(Q))\\)", "\\(AB\\)"],
        0,
        [
            "A ∈ (Q): 2−(−1)−3=0. N·N'=1+0−1=0 so (P) ⟂ (Q).",
            "The perpendicular from A to (BC) then has length d(A,(P)).",
        ],
        tag="dist-A-to-BC-via-planes",
    ),
    Q(
        "g12-ls-mc-pr-05",
        "probability",
        "hard",
        "Let X have P(X=0)=3/5 and, for k=1,…,5, P(X=k)=2/25. Then P(X=0)+…+P(X=5) equals:",
        ["\\(1\\)", "\\(\\dfrac{3}{5}\\)", "\\(\\dfrac{2}{5}\\)", "\\(\\dfrac{13}{25}\\)"],
        0,
        ["3/5 + 5×(2/25)=15/25+10/25=1, so the table is a probability distribution."],
        tag="distribution-check",
    ),
    Q(
        "g12-ls-mc-lm-06",
        "limits",
        "hard",
        "The exponential form of z = −sin θ + i cos θ (θ real) is:",
        [
            "\\(e^{i(\\pi/2+\\theta)}\\)",
            "\\(e^{i(\\pi/2-\\theta)}\\)",
            "\\(e^{i(\\theta-\\pi/2)}\\)",
            "\\(e^{-i\\theta}\\)",
        ],
        0,
        ["e^{i(π/2+θ)}=i e^{iθ}= i cos θ − sin θ = −sin θ + i cos θ."],
        tag="minus-sin-plus-i-cos",
    ),
    Q(
        "g12-ls-mc-fn-06",
        "functions",
        "hard",
        "If z is a non-zero real number with |z|=2 and z' = z − 1/z, then |z'| equals:",
        ["\\(\\dfrac{3}{2}\\)", "\\(1\\)", "\\(2\\)", "\\(\\dfrac{5}{2}\\)"],
        0,
        [
            "z=2 or z=−2. If z=2, z'=2−1/2=3/2. If z=−2, z'=−2+1/2=−3/2.",
            "In both cases |z'|=3/2. Trap: 5/2 is |z|+|1/z|.",
        ],
        tag="z-minus-1-over-z",
    ),
    Q(
        "g12-ls-mc-sp-06",
        "space",
        "hard",
        "E(2; 3; 0), A(4; 0; 0), B(0; 6; 0). Then E belongs to (AB) because there exists k such that OE = (1−k)OA + k OB, namely:",
        ["\\(k=\\dfrac{1}{2}\\)", "\\(k=0\\)", "\\(k=1\\)", "\\(k=2\\)"],
        0,
        ["Parametrize AB: (4−4s; 6s; 0). Set 4−4s=2 ⇒ s=1/2, y=3. So E is the midpoint of [AB]."],
        tag="E-on-AB",
    ),
]


def _style(topic: str) -> str:
    return (
        "Academy-original items patterned on Lebanese Grade 12 LS official sessions "
        f"(LS all sessions.pdf): {topic}. Not photocopies of past papers."
    )


def ls_space_bank() -> dict:
    return make_bank(
        bank_id="g12-ls-space-geometry",
        track="grade-12",
        certificate="LS",
        topic="space_geometry",
        title="Space geometry",
        arabic_title="هندسة الفضاء",
        models=M,
        style_note=_style("Problem II wording — orthonormal system, planes, lines, distances, orthogonality"),
        slices=SPACE_SLICES,
        questions=LS_SPACE,
        contest_topics=LS_TOPICS,
    )


def ls_prob_bank() -> dict:
    return make_bank(
        bank_id="g12-ls-probability",
        track="grade-12",
        certificate="LS",
        topic="probability",
        title="Probability",
        arabic_title="الاحتمالات",
        models=M,
        style_note=_style("Problem III wording — counting, conditional probability, Bayes, random variables"),
        slices=PROB_SLICES,
        questions=LS_PROB,
        contest_topics=LS_TOPICS,
    )


def ls_mcq_bank() -> dict:
    return make_bank(
        bank_id="g12-ls-mcq-mixed",
        track="grade-12",
        certificate="LS",
        topic="mcq_mixed",
        title="Mixed MCQ",
        arabic_title="أسئلة مختلطة",
        models=M,
        style_note=_style("Problem I wording — short mixed items, one correct answer in a table"),
        slices=MCQ_SLICES,
        questions=LS_MCQ,
        contest_topics=LS_TOPICS,
        contest_minutes=20,
    )
