"use client";

import { subscriptionLabel } from "@/lib/auth/tiers";
import type { LedgerEntry } from "@/lib/billing/store";
import { useEffect, useState } from "react";

type WalletPayload = {
  name: string;
  phone: string;
  email: string;
  subscriptionType: "AI_TIER" | "LIVE_TIER" | "BOTH" | "EXPIRED" | null;
  aiStatus: "none" | "expired" | "active";
  aiExpiresAt: string | null;
  liveCredits: number;
  ledger: LedgerEntry[];
  devices?: {
    id: string;
    deviceClass: string;
    createdAt: string;
    createdAtBeirut?: string;
    deviceName?: string;
    deviceNameAr?: string;
    current: boolean;
  }[];
  sharingExempt?: boolean;
};

export default function WalletPage() {
  const [data, setData] = useState<WalletPayload | null>(null);
  const [code, setCode] = useState("");
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  const load = () => {
    void fetch("/api/billing/wallet", { credentials: "same-origin" })
      .then((response) => response.json())
      .then(setData);
  };

  useEffect(() => {
    load();
  }, []);

  const redeem = async () => {
    setBusy(true);
    setMessage("");
    const response = await fetch("/api/billing/redeem", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify({ code }),
    });
    const payload = (await response.json()) as { ok?: boolean; message?: string; messageAr?: string; error?: string };
    setMessage(payload.message || payload.messageAr || payload.error || "");
    setBusy(false);
    if (payload.ok) {
      setOpen(false);
      setCode("");
      load();
    }
  };

  if (!data) return <main className="shell">Loading wallet…</main>;
  const label = subscriptionLabel(data.subscriptionType);
  const expires = data.aiExpiresAt
    ? new Date(data.aiExpiresAt).toLocaleDateString("en-GB", { timeZone: "Asia/Beirut" })
    : "—";

  return (
    <main className="shell">
      <p className="eyebrow">Credit balance · Prof. Munzer Haddara</p>
      <h1>المحفظة والفواتير</h1>
      <div className="grid two">
        <article className="card">
          <h2>AI Platform Access</h2>
          <p style={{ fontSize: 28 }}>{data.aiStatus === "active" ? "Active" : data.aiStatus === "expired" ? "Expired" : "None"}</p>
          <p className="muted">Expires: {expires} · {label.en}</p>
        </article>
        <article className="card">
          <h2>Live class credits</h2>
          <p style={{ fontSize: 28 }}>{data.liveCredits} h</p>
          <p className="muted">Hours remaining for 1-on-1 booking with Prof. Munzer Haddara.</p>
          <button className="btn dark" type="button" onClick={() => setOpen(true)}>
            Redeem top-up code
          </button>
        </article>
      </div>
      <section className="card" style={{ marginTop: 20 }}>
        <h2>
          {data.sharingExempt
            ? "أجهزتي النشطة / Active devices"
            : "Active devices (1 mobile + 1 desktop)"}
        </h2>
        {data.sharingExempt ? (
          <p className="muted">حساب الأستاذ يبقى مسجّلاً على أكثر من جهاز؛ الطلاب محدودون بجهاز من كل نوع.</p>
        ) : null}
        {(data.devices ?? []).length === 0 ? <p className="muted">No stored sessions.</p> : null}
        {(data.devices ?? []).map((device) => (
          <p key={device.id}>
            {device.deviceNameAr || device.deviceName || device.deviceClass}
            {device.deviceName ? ` · ${device.deviceName}` : ` · ${device.deviceClass}`}
            {" · "}
            {device.createdAtBeirut || device.createdAt.slice(0, 16).replace("T", " ")}
            {device.current ? " · this device" : ""}
          </p>
        ))}
      </section>
      <section className="card" style={{ marginTop: 20, overflowX: "auto" }}>
        <h2>Transaction history</h2>
        <table className="data-table">
          <thead>
            <tr>
              <th>When</th>
              <th>Kind</th>
              <th>Hours</th>
              <th>Code</th>
              <th>Note</th>
            </tr>
          </thead>
          <tbody>
            {data.ledger.map((row) => (
              <tr key={row.id}>
                <td>{row.createdAt.slice(0, 16).replace("T", " ")}</td>
                <td>{row.kind}</td>
                <td>{row.hoursDelta > 0 ? `+${row.hoursDelta}` : row.hoursDelta}</td>
                <td>{row.code ?? "—"}</td>
                <td>{row.description}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
      {open ? (
        <div className="modal-backdrop" role="dialog">
          <div className="card modal-card">
            <h2>Live-hour top-up</h2>
            <p className="muted">Enter a code generated by Prof. Munzer Haddara. Demo: MUNZER-HRS-2H</p>
            <label>
              Code
              <input value={code} onChange={(event) => setCode(event.target.value)} autoFocus />
            </label>
            <div className="row">
              <button className="btn dark" type="button" disabled={busy} onClick={() => void redeem()}>
                {busy ? "Redeeming…" : "Redeem"}
              </button>
              <button className="btn" type="button" onClick={() => setOpen(false)}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      ) : null}
      {message ? <p className="success">{message}</p> : null}
    </main>
  );
}
