import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { invokeLLM } from "./_core/llm";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { applyApproval, createAssignment, createManagerMessage, createManagerProposal, createSubscriptionRequest, decideManagerProposal, listApprovals, listAssignments, listContestAttempts, listDiagnosticAttempts, listHomeworkSubmissions, listLearningPaths, listManagerMessages, listManagerProposals, listPublishedContests, listAllContestContents, listQuestionsForLesson, listLessons, listProgress, listSubscriptionRequests, listTopContestAttempts, markQuestionForReview, recordAttempt, resolveManagerMessage, saveContestAttempt, saveDiagnosticAttempt, saveHomeworkSubmission, saveProgress, getMiddleSchoolDailySnapshot, createDailyStudentSummary, listDailyStudentSummaries, reviewDailyStudentSummary, recordInteractiveAttendance, getWeeklyParentReportData, createWeeklyParentReport, listWeeklyParentReports, reviewWeeklyParentReport, createParentStudentLink, listParentStudentLinks, acceptParentStudentLink, revokeParentStudentLink, updateParentReportConsent, getParentStudentLinksForUser, canDeliverWeeklyParentReport, createSchoolLead, listSchoolLeads, createSchoolOutreachDraft, listSchoolOutreachDrafts, reviewSchoolOutreachDraft, saveExamAttempt, listExamAttempts, saveLessonAttempt, listLessonAttempts, deleteLessonAttempt, deleteLessonAttempts, createSolutionAsset, listSolutionAssets, reviewSolutionAsset, reviewSolutionAssets } from "./db";
import { validateLessonClarity } from "../shared/academy";
import { storagePut } from "./storage";

const chatMessage = z.object({ role: z.enum(["system", "user", "assistant"]), content: z.string().min(1).max(5000) });
const safeText = (value: unknown) => typeof value === "string" ? value : "I could not generate a response right now. Please try again.";
const professorProcedure = protectedProcedure.use(({ ctx, next }) => {
  if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Professor approval is required for management actions." });
  return next({ ctx });
});

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  academy: router({
    paths: publicProcedure.query(() => listLearningPaths()),
    lessons: publicProcedure.input(z.object({ pathId: z.number().int().positive() })).query(({ input }) => listLessons(input.pathId)),
    progress: protectedProcedure.query(({ ctx }) => listProgress(ctx.user.id)),
    saveProgress: protectedProcedure.input(z.object({ lessonId: z.number().int().positive(), percent: z.number().int().min(0).max(100) })).mutation(({ ctx, input }) => saveProgress(ctx.user.id, input.lessonId, input.percent)),
    requestSubscription: protectedProcedure.input(z.object({ reference: z.string().max(120).optional(), receiptUrl: z.string().url().optional() })).mutation(({ ctx, input }) => createSubscriptionRequest(ctx.user.id, input.reference, input.receiptUrl)),
    subscriptionQueue: protectedProcedure.query(() => listSubscriptionRequests()),
    diagnosticHistory: protectedProcedure.query(({ ctx }) => listDiagnosticAttempts(ctx.user.id)),
    examAttemptHistory: protectedProcedure.input(z.object({ specialization: z.string().max(80).optional() }).optional()).query(({ ctx, input }) => listExamAttempts(ctx.user.id, input?.specialization)),
    saveExamAttempt: protectedProcedure.input(z.object({ examId: z.string().min(1).max(120), specialization: z.string().min(1).max(80), score: z.number().int().min(0), total: z.number().int().positive(), answered: z.number().int().min(0), percentage: z.number().int().min(0).max(100), durationSeconds: z.number().int().positive(), timeSpentSeconds: z.number().int().min(0), sectionSnapshot: z.string().max(20000), skillSnapshot: z.string().max(20000), reviewSnapshot: z.string().max(100000) })).mutation(({ ctx, input }) => saveExamAttempt({ userId: ctx.user.id, ...input })),
    saveLessonAttempt: protectedProcedure.input(z.object({ lessonSlug: z.string().min(1).max(120), skill: z.string().min(1).max(120), language: z.enum(["en", "ar"]), typedAnswer: z.string().max(5000), solutionSteps: z.string().max(20000), expectedAnswer: z.string().max(255), explanation: z.string().max(10000), isCorrect: z.number().int().min(0).max(1) })).mutation(({ ctx, input }) => saveLessonAttempt({ userId: ctx.user.id, ...input })),
    lessonAttemptHistory: protectedProcedure.input(z.object({ lessonSlug: z.string().max(120).optional() }).optional()).query(({ ctx, input }) => listLessonAttempts(ctx.user.id, input?.lessonSlug)),
    deleteLessonAttempt: protectedProcedure.input(z.object({ attemptId: z.number().int().positive() })).mutation(({ ctx, input }) => deleteLessonAttempt(ctx.user.id, input.attemptId)),
    deleteLessonAttempts: protectedProcedure.input(z.object({ attemptIds: z.array(z.number().int().positive()).min(1).max(100) })).mutation(({ ctx, input }) => deleteLessonAttempts(ctx.user.id, input.attemptIds)),
    contestLeaderboard: publicProcedure.query(() => listTopContestAttempts()),
    publishedContests: publicProcedure.query(() => listPublishedContests()),
    managementContests: protectedProcedure.query(() => listAllContestContents()),
    lessonQuestions: publicProcedure.input(z.object({ lessonId: z.number().int().positive() })).query(({ input }) => listQuestionsForLesson(input.lessonId)),
    saveDiagnostic: protectedProcedure.input(z.object({ track: z.enum(["lebanese", "sat"]), score: z.number().int().min(0), total: z.number().int().positive(), recommendedTopic: z.string().max(180).optional() })).mutation(({ ctx, input }) => saveDiagnosticAttempt({ userId: ctx.user.id, ...input })),
    uploadHomeworkAttachment: protectedProcedure.input(z.object({ name: z.string().min(1).max(255), mime: z.enum(["application/pdf", "image/jpeg", "image/png", "image/webp"]), dataUrl: z.string().startsWith("data:").max(7000000) })).mutation(async ({ ctx, input }) => { const encoded = input.dataUrl.split(",")[1]; if (!encoded) throw new Error("Invalid attachment"); const { url } = await storagePut(`${ctx.user.id}/homework/${Date.now()}-${input.name}`, Buffer.from(encoded, "base64"), input.mime); return { url, name: input.name, mime: input.mime }; }),
    submitHomework: protectedProcedure.input(z.object({ lessonId: z.number().int().positive().optional(), prompt: z.string().min(1).max(10000), attachmentUrl: z.string().url().optional(), attachmentName: z.string().max(255).optional() })).mutation(({ ctx, input }) => saveHomeworkSubmission({ userId: ctx.user.id, ...input })),
    homeworkSubmissions: protectedProcedure.query(({ ctx }) => listHomeworkSubmissions(ctx.user.id)),
    recordInteractiveAttendance: protectedProcedure.input(z.object({ sessionDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), sessionTitle: z.string().min(1).max(180), status: z.enum(["present", "absent", "late", "excused"]), joinDurationSeconds: z.number().int().min(0).max(86400).default(0), engagementEvents: z.number().int().min(0).max(10000).default(0), submittedWorkCount: z.number().int().min(0).max(1000).default(0) })).mutation(({ ctx, input }) => recordInteractiveAttendance({ userId: ctx.user.id, ...input })),
    saveContest: protectedProcedure.input(z.object({ contestId: z.number().int().positive().optional(), title: z.string().min(1).max(180), score: z.number().int().min(0), total: z.number().int().positive(), durationSeconds: z.number().int().positive() })).mutation(({ ctx, input }) => saveContestAttempt({ userId: ctx.user.id, ...input })),
    contestHistory: protectedProcedure.query(({ ctx }) => listContestAttempts(ctx.user.id)),
    requestApproval: professorProcedure.input(z.object({ contentType: z.enum(["lesson", "contest", "assignment", "access"]), contentId: z.number().int().positive().optional(), action: z.enum(["publish", "assign", "activate", "request_changes"]), note: z.string().max(5000).optional() })).mutation(({ input }) => applyApproval(input.contentType, input.contentId, input.action, input.note)),
    approvalQueue: professorProcedure.query(() => listApprovals()),
    createSolutionDraft: professorProcedure.input(z.object({ skill: z.string().min(1).max(120), questionRef: z.string().min(1).max(160), videoScript: z.string().min(1).max(20000), videoUrl: z.string().url().optional(), printableSolution: z.string().min(1).max(30000), language: z.enum(["en", "ar"]) })).mutation(({ input }) => createSolutionAsset({ ...input, status: "awaiting_approval" })),
    solutionApprovalQueue: professorProcedure.input(z.object({ status: z.enum(["draft", "awaiting_approval", "approved", "rejected", "changes_requested"]).optional() }).optional()).query(({ input }) => listSolutionAssets(input?.status)),
    reviewSolutionDraft: professorProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected", "changes_requested"]), professorNote: z.string().max(5000).optional() })).mutation(({ ctx, input }) => reviewSolutionAsset(input.id, ctx.user.id, input.status, input.professorNote)),
    reviewSolutionDrafts: professorProcedure.input(z.object({ ids: z.array(z.number().int().positive()).min(1).max(100), status: z.enum(["approved", "rejected"]), professorNote: z.string().max(5000).optional() })).mutation(({ ctx, input }) => reviewSolutionAssets(input.ids, ctx.user.id, input.status, input.professorNote)),
    publishedSolutionAssets: protectedProcedure.input(z.object({ skill: z.string().max(120).optional() }).optional()).query(({ input }) => listSolutionAssets("approved").then((items) => input?.skill ? items.filter((item) => item.skill === input.skill) : items)),
    managerProposals: professorProcedure.query(() => listManagerProposals()),
    schoolLeads: professorProcedure.query(() => listSchoolLeads()),
    schoolOutreachDrafts: professorProcedure.query(() => listSchoolOutreachDrafts()),
    createSchoolLead: professorProcedure.input(z.object({ schoolName: z.string().min(1).max(180), market: z.enum(["lebanon", "gulf"]), country: z.string().min(1).max(80), contactName: z.string().max(180).optional(), contactEmail: z.string().email().optional(), contactChannel: z.string().max(40).optional(), notes: z.string().max(5000).optional() })).mutation(({ input }) => createSchoolLead({ ...input, status: "new" })),
    createSchoolOutreachDraft: professorProcedure.input(z.object({ leadId: z.number().int().positive(), language: z.enum(["en", "ar"]), subject: z.string().min(1).max(180), body: z.string().min(1).max(12000), channel: z.enum(["email", "whatsapp", "in_app"]).default("email") })).mutation(({ input }) => createSchoolOutreachDraft({ ...input, status: "awaiting_approval" })),
    reviewSchoolOutreachDraft: professorProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected", "awaiting_approval"]), professorNote: z.string().max(5000).optional() })).mutation(({ input }) => reviewSchoolOutreachDraft(input.id, input.status, input.professorNote)),
    managerMessages: professorProcedure.query(() => listManagerMessages()),
    createManagerProposal: professorProcedure.input(z.object({ proposalType: z.enum(["pricing", "campaign", "operations"]), audience: z.enum(["grade9", "grade12", "sat", "all"]), title: z.string().min(1).max(180), summary: z.string().min(1).max(12000), suggestedAmount: z.number().int().min(0).optional(), currency: z.string().max(8).default("USD"), suggestedBudget: z.number().int().min(0).optional(), campaignChannel: z.string().max(40).optional(), campaignCopy: z.string().max(12000).optional() })).mutation(async ({ input }) => { await createManagerProposal({ ...input, status: "awaiting_approval" }); await createManagerMessage({ direction: "manager", subject: `Decision needed: ${input.title}`, body: `${input.summary}\n\nNo financial, publishing, messaging, or access action will be taken until you approve it.`, status: "open" }); return { success: true, status: "awaiting_approval" as const }; }),
    decideManagerProposal: professorProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected"]), decisionNote: z.string().max(5000).optional() })).mutation(async ({ input }) => { await decideManagerProposal(input.id, input.status, input.decisionNote); await createManagerMessage({ direction: "professor", subject: `Decision recorded for proposal #${input.id}`, body: input.decisionNote || `Proposal #${input.id} marked ${input.status}.`, relatedProposalId: input.id, status: "resolved" }); return { success: true, status: input.status }; }),
    sendManagerMessage: professorProcedure.input(z.object({ subject: z.string().min(1).max(180), body: z.string().min(1).max(12000), relatedProposalId: z.number().int().positive().optional() })).mutation(({ input }) => createManagerMessage({ direction: "professor", ...input })),
    resolveManagerMessage: professorProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => resolveManagerMessage(input.id)),
    checkAnswer: protectedProcedure.input(z.object({ questionId: z.number().int().positive(), expectedAnswer: z.string().max(255), submittedAnswer: z.string().max(1000), explanation: z.string().max(5000) })).mutation(async ({ ctx, input }) => { const isCorrect = input.submittedAnswer.trim().toLowerCase() === input.expectedAnswer.trim().toLowerCase(); await recordAttempt({ userId: ctx.user.id, questionId: input.questionId, submittedAnswer: input.submittedAnswer, isCorrect: isCorrect ? 1 : 0 }); return { isCorrect, feedback: isCorrect ? "Correct. Now explain why this method works." : input.explanation }; }),
    requestQuestionReview: protectedProcedure.input(z.object({ questionId: z.number().int().positive(), feedback: z.string().min(1).max(5000) })).mutation(({ input }) => markQuestionForReview(input.questionId, input.feedback)),
    assignWork: professorProcedure.input(z.object({ userId: z.number().int().positive(), lessonId: z.number().int().positive().optional(), title: z.string().min(1).max(180), dueDate: z.coerce.date().optional() })).mutation(({ input }) => createAssignment({ userId: input.userId, lessonId: input.lessonId, title: input.title, dueDate: input.dueDate })),
    assignments: protectedProcedure.query(({ ctx }) => listAssignments(ctx.user.id)),
    middleSchoolDailySnapshot: professorProcedure.query(() => getMiddleSchoolDailySnapshot()),
    dailyMiddleSchoolSummaries: professorProcedure.query(() => listDailyStudentSummaries()),
    createDailyMiddleSchoolSummary: professorProcedure.mutation(async () => {
      const snapshot = await getMiddleSchoolDailySnapshot();
      const response = await invokeLLM({ model: "gpt-5-mini", messages: [
        { role: "system", content: "You are the daily student-success assistant for Professor Munzer Haddara. Use only the supplied database snapshot. Do not invent students, grades, attendance, emotions, or progress. When attendance data exists, include attendance and engagement patterns such as absence, lateness, low participation, join duration, and submitted in-session work in the overview or priorities. Return JSON with overview, priorities, studentsNeedingAttention, and professorQuestions. Each priority must be a concise actionable review item. Each student needing attention must include userId, name, reason, proposedAction, and draftMessage. Draft messages are for Professor Munzer to review only; do not claim they were sent. Mention that all follow-up actions require professor approval." },
        { role: "user", content: JSON.stringify(snapshot) },
      ], response_format: { type: "json_schema", json_schema: { name: "daily_middle_school_summary", strict: true, schema: { type: "object", properties: { overview: { type: "string" }, priorities: { type: "array", items: { type: "string" } }, studentsNeedingAttention: { type: "array", items: { type: "object", properties: { userId: { type: "integer" }, name: { type: "string" }, reason: { type: "string" }, proposedAction: { type: "string" }, draftMessage: { type: "string" } }, required: ["userId", "name", "reason", "proposedAction", "draftMessage"], additionalProperties: false } }, professorQuestions: { type: "array", items: { type: "string" } } }, required: ["overview", "priorities", "studentsNeedingAttention", "professorQuestions"], additionalProperties: false } } } });
      const summary = safeText(response.choices[0]?.message?.content);
      await createDailyStudentSummary({ summaryDate: snapshot.summaryDate, cohort: "middle_school", snapshot: JSON.stringify(snapshot), summary, status: "awaiting_approval" });
      await createManagerMessage({ direction: "manager", subject: `Daily middle-school review · ${snapshot.summaryDate}`, body: `${summary}\n\nThis is a review draft. No student message, assignment, access change, or other action has been executed. Professor approval is required.`, status: "open" });
      return { summaryDate: snapshot.summaryDate, status: "awaiting_approval" as const, snapshot, summary };
    }),
    reviewDailyMiddleSchoolSummary: professorProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["reviewed", "awaiting_approval"]) })).mutation(async ({ input }) => { await reviewDailyStudentSummary(input.id, input.status); return { success: true, status: input.status }; }),
    weeklyParentReports: professorProcedure.query(() => listWeeklyParentReports()),
    parentStudentLinks: professorProcedure.query(() => listParentStudentLinks()),
    createParentStudentLink: professorProcedure.input(z.object({ studentId: z.number().int().positive(), inviteEmail: z.string().email(), expiresAt: z.coerce.date() })).mutation(async ({ input }) => { const result = await createParentStudentLink(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Parent link could not be created." }); return { success: true, inviteToken: result.inviteToken, status: "pending" as const }; }),
    revokeParentStudentLink: professorProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { await revokeParentStudentLink(input.id); return { success: true, status: "revoked" as const }; }),
    acceptParentStudentLink: protectedProcedure.input(z.object({ token: z.string().regex(/^[a-f0-9]{64}$/), consent: z.boolean() })).mutation(async ({ ctx, input }) => { if (!ctx.user.email) throw new TRPCError({ code: "BAD_REQUEST", message: "A verified parent email is required." }); const result = await acceptParentStudentLink(input.token, ctx.user.id, ctx.user.email, input.consent); if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "This invitation is invalid, expired, or does not match your account email." }); return { success: true, status: result.status, reportConsent: result.reportConsent, studentId: result.studentId }; }),
    myParentStudentLinks: protectedProcedure.query(({ ctx }) => getParentStudentLinksForUser(ctx.user.id)),
    updateParentReportConsent: protectedProcedure.input(z.object({ id: z.number().int().positive(), consent: z.boolean() })).mutation(async ({ ctx, input }) => { const result = await updateParentReportConsent(input.id, ctx.user.id, input.consent); if (!result) throw new TRPCError({ code: "FORBIDDEN", message: "Only the linked parent can change report consent." }); return { success: true, consent: input.consent }; }),
    createWeeklyParentReport: professorProcedure.input(z.object({ studentId: z.number().int().positive(), weekStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), weekEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), recipientLabel: z.string().max(180).optional(), consentStatus: z.enum(["unknown", "confirmed", "revoked"]).default("unknown") })).mutation(async ({ input }) => {
      const data = await getWeeklyParentReportData(input.studentId, input.weekStart, input.weekEnd);
      if (!data) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Weekly report data is unavailable." });
      const response = await invokeLLM({ model: "gpt-5-mini", messages: [
        { role: "system", content: "You are a careful parent-report assistant for Munzer Haddara Math Academy. Use only the supplied recorded student metrics. Do not invent grades, attendance, emotions, causes, or achievements. Write a concise, warm weekly report in English and Arabic. Mention performance, attendance and participation, strengths only when supported by metrics, one support area, and a practical next-week plan. Make clear it is a draft for Professor Munzer review and has not been sent." },
        { role: "user", content: JSON.stringify(data) },
      ], response_format: { type: "json_schema", json_schema: { name: "weekly_parent_report", strict: true, schema: { type: "object", properties: { englishSummary: { type: "string" }, arabicSummary: { type: "string" } }, required: ["englishSummary", "arabicSummary"], additionalProperties: false } } } });
      const content = response.choices[0]?.message?.content;
      const parsed = typeof content === "string" ? JSON.parse(content) as { englishSummary: string; arabicSummary: string } : { englishSummary: "A weekly report draft could not be generated.", arabicSummary: "تعذر إنشاء مسودة التقرير الأسبوعي." };
      const snapshot = JSON.stringify(data);
      await createWeeklyParentReport({ studentId: input.studentId, weekStart: input.weekStart, weekEnd: input.weekEnd, snapshot, englishSummary: parsed.englishSummary, arabicSummary: parsed.arabicSummary, recipientLabel: input.recipientLabel, consentStatus: input.consentStatus, deliveryChannel: "in_app", status: "awaiting_approval" });
      await createManagerMessage({ direction: "manager", subject: `Parent report review · ${data.student.name}`, body: `A bilingual weekly parent report draft is ready for ${data.student.name}. It has not been sent. Professor review and approval are required before any delivery.`, status: "open" });
      return { status: "awaiting_approval" as const, student: data.student, weekStart: input.weekStart, weekEnd: input.weekEnd, englishSummary: parsed.englishSummary, arabicSummary: parsed.arabicSummary };
    }),
    reviewWeeklyParentReport: professorProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected", "awaiting_approval"]), professorNote: z.string().max(5000).optional(), englishSummary: z.string().max(12000).optional(), arabicSummary: z.string().max(12000).optional() })).mutation(async ({ input }) => { if (input.status === "approved" && !(await canDeliverWeeklyParentReport(input.id))) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "An accepted parent link with active report consent is required before approval for delivery." }); await reviewWeeklyParentReport(input.id, input.status, input.professorNote, input.englishSummary, input.arabicSummary); return { success: true, status: input.status }; }),
  }),
  ai: router({
    tutor: publicProcedure.input(z.object({ messages: z.array(chatMessage).min(1).max(20), attachment: z.object({ url: z.string().url(), mime: z.enum(["application/pdf", "image/jpeg", "image/png", "image/webp"]) }).optional() })).mutation(async ({ input }) => { const messages = input.messages.map((message, index) => index === input.messages.length - 1 && message.role === "user" && input.attachment ? { role: message.role, content: [{ type: "text", text: message.content }, input.attachment.mime === "application/pdf" ? { type: "file_url", file_url: { url: input.attachment.url, mime_type: input.attachment.mime } } : { type: "image_url", image_url: { url: input.attachment.url, detail: "auto" } }] } : message); const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "You are the Munzer Haddara Math Academy tutor. Explain mathematics in clear, encouraging English for middle-school and high-school learners. Work step by step, show the reasoning, identify common mistakes, and ask a short check-for-understanding question. If a student attaches homework, use the image/PDF content as available context, transcribe visible mathematical work when possible, interpret handwritten steps cautiously, and state when anything is unreadable or uncertain. Never just give a bare answer." }, ...messages] as any, reasoning: { effort: "low" } }); return safeText(response.choices[0]?.message?.content); }),
    management: publicProcedure.input(z.object({ summary: z.string().max(12000) })).mutation(async ({ input }) => { const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "You are the management assistant for Professor Munzer Haddara. Review the supplied learning summary and respond in clear English with three sections: Progress snapshot, Teaching priorities, and Suggested content actions. Be concise, evidence-based, and never invent student records." }, { role: "user", content: input.summary }], reasoning: { effort: "low" } }); return safeText(response.choices[0]?.message?.content); }),
    paymentReview: publicProcedure.input(z.object({ submission: z.string().min(1).max(8000) })).mutation(async ({ input }) => { const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "You are a cautious payment-operations assistant for Munzer Haddara Math Academy in Lebanon. Review a student's Whish Money payment submission and return: Recommendation (approve, request-more-information, or reject), Evidence found, and Professor action. Never claim a transfer is verified from text alone and always state that Professor approval is required before access is granted." }, { role: "user", content: input.submission }], reasoning: { effort: "low" } }); return safeText(response.choices[0]?.message?.content); }),
    generateLesson: publicProcedure.input(z.object({ topic: z.string().min(2).max(160), level: z.enum(["middle", "secondary", "sat"]) })).mutation(async ({ input }) => { const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "Create an original English mathematics lesson draft for Munzer Haddara Math Academy. Do not reproduce textbook wording. Return a concise lesson goal, explanation, worked example, interactive check, recap, and one common mistake." }, { role: "user", content: `Topic: ${input.topic}. Level: ${input.level}.` }], response_format: { type: "json_schema", json_schema: { name: "lesson_draft", strict: true, schema: { type: "object", properties: { goal: { type: "string" }, explanation: { type: "string" }, example: { type: "string" }, interactiveCheck: { type: "string" }, recap: { type: "string" }, commonMistake: { type: "string" } }, required: ["goal", "explanation", "example", "interactiveCheck", "recap", "commonMistake"], additionalProperties: false } } } }); return response.choices[0]?.message?.content ?? "{}"; }),
    validateLesson: publicProcedure.input(z.object({ goal: z.string().optional(), explanation: z.string().optional(), example: z.string().optional(), interactiveCheck: z.string().optional(), recap: z.string().optional() })).query(({ input }) => validateLessonClarity(input)),
    operationsDraft: professorProcedure.input(z.object({ proposalType: z.enum(["pricing", "campaign"]), audience: z.enum(["grade9", "grade12", "sat", "all"]), context: z.string().max(6000).optional() })).mutation(async ({ input }) => { const audience = { grade9: "Lebanese Grade 9 Certificate", grade12: "Lebanese Grade 12 Certificate", sat: "SAT Math", all: "Grade 9, Grade 12, and SAT Math" }[input.audience]; const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: `You are the Academy Operations Manager for Munzer Haddara Math Academy. Prepare a concise proposal for Professor Munzer, never execute it, never claim market research you did not perform, and explicitly request professor approval before any financial, publishing, messaging, or access action. The academy serves Lebanese Certificate students in Grades 9 and 12 and SAT Math learners. Return JSON with title, summary, suggestedAmount, currency, suggestedBudget, campaignChannel, campaignCopy, and questionForProfessor. For pricing, state assumptions and use a cautious suggested amount; for campaigns, write original English copy and a modest test budget suggestion.` }, { role: "user", content: `Proposal type: ${input.proposalType}. Audience: ${audience}. Additional context: ${input.context || "No additional context supplied."}` }], response_format: { type: "json_schema", json_schema: { name: "operations_proposal", strict: true, schema: { type: "object", properties: { title: { type: "string" }, summary: { type: "string" }, suggestedAmount: { type: "integer" }, currency: { type: "string" }, suggestedBudget: { type: "integer" }, campaignChannel: { type: "string" }, campaignCopy: { type: "string" }, questionForProfessor: { type: "string" } }, required: ["title", "summary", "suggestedAmount", "currency", "suggestedBudget", "campaignChannel", "campaignCopy", "questionForProfessor"], additionalProperties: false } } } }); return safeText(response.choices[0]?.message?.content); }),
    generateContest: publicProcedure.input(z.object({ topic: z.string().min(2).max(160), difficulty: z.enum(["foundation", "standard", "challenge"]), questionCount: z.number().int().min(3).max(20) })).mutation(async ({ input }) => { const response = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "Create an original English SAT Math mini-contest for Munzer Haddara Math Academy. Return an array of concise multiple-choice questions with four options, correct option index, a short explanation, difficulty, and a suggested time limit. Do not reproduce official test questions." }, { role: "user", content: `Topic: ${input.topic}; difficulty: ${input.difficulty}; questions: ${input.questionCount}.` }], response_format: { type: "json_schema", json_schema: { name: "sat_contest", strict: true, schema: { type: "object", properties: { title: { type: "string" }, timeLimitMinutes: { type: "number" }, questions: { type: "array", items: { type: "object", properties: { prompt: { type: "string" }, options: { type: "array", items: { type: "string" } }, correctIndex: { type: "number" }, explanation: { type: "string" } }, required: ["prompt", "options", "correctIndex", "explanation"], additionalProperties: false } } }, required: ["title", "timeLimitMinutes", "questions"], additionalProperties: false } } } }); return response.choices[0]?.message?.content ?? "{}"; }),
  }),
});

export type AppRouter = typeof appRouter;
